apiVersion: v2
name: rsctf
description: A security-conscious Helm chart for the rsctf CTF platform
type: application
version: 0.1.12
appVersion: "0.1.12"
kubeVersion: ">=1.25.0-0"
home: https://github.com/dimasma0305/rsctf
sources:
  - https://github.com/dimasma0305/rsctf
keywords:
  - ctf
  - security
  - rust
maintainers:
  - name: rsctf contributors
