//! Attack & Defense rounds, flags, checks, and rollups.

use super::*;

pub(super) const ATTACK_DEFENSE: &[TableSpec] = &[
    TableSpec {
        name: "adRounds",
        table: "AdRounds",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "number",
            "start_time_utc",
            "end_time_utc",
            "finalized",
            "pipeline_completed_at",
            "flags_published_at",
            "flag_delivery_failures",
        ],
        restore: rows(Some(Map::AdRound), true, &[]),
    },
    TableSpec {
        name: "adTeamServices",
        table: "AdTeamServices",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "participation_id",
            "challenge_id",
            "host",
            "port",
            "status",
            "last_reset_at",
        ],
        restore: rows(Some(Map::AdTeamService), true, &[PARTICIPATION, CHALLENGE]),
    },
    TableSpec {
        name: "adFlags",
        table: "AdFlags",
        from: None,
        scope: VIA_AD_ROUND,
        order: "t.id",
        columns: &[
            "id",
            "round_id",
            "team_service_id",
            "flag",
            "planted_at",
            "checker_qualified",
            "service_weight",
        ],
        restore: rows(Some(Map::AdFlag), false, &[ROUND, TEAM_SERVICE]),
    },
    TableSpec {
        name: "adAttacks",
        table: "AdAttacks",
        from: None,
        scope: VIA_AD_ROUND,
        order: "t.id",
        columns: &[
            "id",
            "round_id",
            "attacker_participation_id",
            "victim_team_service_id",
            "flag_id",
            "submitted_at",
        ],
        restore: rows(
            None,
            false,
            &[
                ROUND,
                ("attacker_participation_id", Map::Participation),
                ("victim_team_service_id", Map::AdTeamService),
                ("flag_id", Map::AdFlag),
            ],
        ),
    },
    TableSpec {
        name: "adCheckResults",
        table: "AdCheckResults",
        from: None,
        scope: VIA_AD_ROUND,
        order: "t.id",
        columns: &[
            "id",
            "round_id",
            "team_service_id",
            "status",
            "message",
            "checked_at",
            "sla_credit",
            "flag_verified",
        ],
        restore: rows(None, false, &[ROUND, TEAM_SERVICE]),
    },
    TableSpec {
        name: "adEpochRollups",
        table: "AdEpochRollups",
        from: None,
        scope: GAME,
        order: "t.epoch",
        columns: &[
            "epoch",
            "start_round",
            "end_round",
            "round_count",
            "epoch_weight",
            "finalized_round",
            "eligible_flags",
            "captured_flags",
            "accepted_captures",
            "defense_opportunities",
            "protected_opportunities",
            "cumulative_eligible_flags",
            "cumulative_captured_flags",
            "cumulative_accepted_captures",
            "cumulative_defense_opportunities",
            "cumulative_protected_opportunities",
            "created_at",
        ],
        restore: rows(None, true, &[]),
    },
    TableSpec {
        name: "adEpochTeamRollups",
        table: "AdEpochTeamRollups",
        from: None,
        scope: GAME,
        order: "t.epoch, t.participation_id",
        columns: &[
            "epoch",
            "participation_id",
            "points",
            "epoch_weight",
            "cumulative_points_numerator",
            "cumulative_epoch_weight",
            "cumulative_offense_numerator",
            "cumulative_defense_numerator",
            "cumulative_sla_numerator",
            "cumulative_rate_weight",
        ],
        restore: rows(None, true, &[PARTICIPATION]),
    },
    TableSpec {
        name: "adEpochServiceRollups",
        table: "AdEpochServiceRollups",
        from: None,
        scope: GAME,
        order: "t.epoch, t.participation_id, t.challenge_id",
        columns: &[
            "epoch",
            "participation_id",
            "challenge_id",
            "service_weight",
            "opportunity_count",
            "capture_count",
            "rarity_sum",
            "defense_opportunity_count",
            "protected_opportunity_count",
            "sla_credit_sum",
            "sla_tick_count",
            "closing_sla_status",
            "closing_sla_credit",
            "local_points",
            "offense_rate",
            "defense_rate",
            "sla_rate",
            "cumulative_points_numerator",
            "cumulative_epoch_weight",
            "cumulative_offense_numerator",
            "cumulative_defense_numerator",
            "cumulative_sla_numerator",
            "cumulative_capture_count",
        ],
        restore: rows(None, true, &[PARTICIPATION, CHALLENGE]),
    },
];
