//! Tables exported for reference only.

use super::*;

pub(super) const EXPORT_ONLY: &[TableSpec] = &[
    TableSpec {
        name: "solveReceiptAudit",
        table: "SolveReceiptAudit",
        from: None,
        scope: GAME,
        order: "t.receipt_id",
        columns: &[
            "receipt_id",
            "challenge_id",
            "participation_id",
            "user_id",
            "variant_id",
            "issuer_identity",
            "consumed_submission_id",
            "issued_at_utc",
            "outcome",
            "archived_at_utc",
        ],
        restore: Restore::ExportOnly,
    },
    TableSpec {
        name: "adFlagDeliveryResults",
        table: "AdFlagDeliveryResults",
        from: None,
        scope: VIA_AD_ROUND,
        order: "t.round_id, t.team_service_id",
        columns: &[
            "round_id",
            "team_service_id",
            "delivery_kind",
            "delivered",
            "attempts",
            "failure_reason",
            "completed_at",
            "created_at",
        ],
        restore: Restore::ExportOnly,
    },
    TableSpec {
        name: "buildRecords",
        table: "BuildRecords",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "challenge_title",
            "enqueued_at_utc",
            "started_at_utc",
            "finished_at_utc",
            "trigger",
            "kind",
            "attempt",
            "status",
            "digest",
            "image_ref",
        ],
        restore: Restore::ExportOnly,
    },
    TableSpec {
        name: "challengeVariants",
        table: "ChallengeVariants",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "participation_id",
            "revision",
            "generator_image",
            "generator_digest",
            "manifest",
            "created_at_utc",
            "frozen_at_utc",
        ],
        restore: Restore::ExportOnly,
    },
    TableSpec {
        name: "vpnFlagTransportEvents",
        table: "VpnFlagTransportEvents",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "receiving_user_id",
            "receiving_participation_id",
            "owning_participation_id",
            "flag_value_hash",
            "transport",
            "direction",
            "observed_at_utc",
            "created_at_utc",
        ],
        restore: Restore::ExportOnly,
    },
    TableSpec {
        name: "vpnFlowTelemetryBuckets",
        table: "VpnFlowTelemetryBuckets",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "user_id",
            "participation_id",
            "challenge_id",
            "container_generation",
            "bucket_start_utc",
            "packets_up",
            "packets_down",
            "bytes_up",
            "bytes_down",
            "distinct_destinations",
            "connection_count",
            "active_seconds",
            "created_at_utc",
        ],
        restore: Restore::ExportOnly,
    },
    TableSpec {
        name: "vpnDnsProviderBuckets",
        table: "VpnDnsProviderBuckets",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "user_id",
            "participation_id",
            "provider_category",
            "bucket_start_utc",
            "query_count",
            "first_seen_at_utc",
            "last_seen_at_utc",
            "created_at_utc",
        ],
        restore: Restore::ExportOnly,
    },
    TableSpec {
        name: "vpnPeerNetworkObservations",
        table: "VpnPeerNetworkObservations",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "user_id",
            "participation_id",
            "endpoint_hash",
            "source_asn",
            "network_class",
            "first_seen_at_utc",
            "last_seen_at_utc",
            "handshake_count",
            "created_at_utc",
        ],
        restore: Restore::ExportOnly,
    },
];
