//! Jeopardy results and evidence.

use super::*;

pub(super) const JEOPARDY: &[TableSpec] = &[
    TableSpec {
        name: "submissions",
        table: "Submissions",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "answer",
            "status",
            "submit_time_utc",
            "user_id",
            "team_id",
            "participation_id",
            "challenge_id",
            "submit_remote_ip_hash",
            "container_id",
            "container_last_operation_at_submit",
            "container_was_loaded_at_submit",
            "first_open_at_submit",
            "first_download_at_submit",
            "first_container_start_at_submit",
        ],
        restore: rows(
            Some(Map::Submission),
            true,
            &[USER, ("team_id", Map::Team), PARTICIPATION, CHALLENGE],
        ),
    },
    TableSpec {
        name: "firstSolves",
        table: "FirstSolves",
        from: None,
        scope: r#"t.participation_id IN (SELECT p.id FROM "Participations" p WHERE p.game_id = $1)"#,
        order: "t.participation_id, t.challenge_id",
        columns: &["participation_id", "challenge_id", "submission_id"],
        restore: rows(
            None,
            false,
            &[PARTICIPATION, CHALLENGE, ("submission_id", Map::Submission)],
        ),
    },
    TableSpec {
        name: "gameEvents",
        table: "GameEvents",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "Type",
            "values",
            "publish_time_utc",
            "user_id",
            "team_id",
        ],
        restore: rows(None, true, &[USER, ("team_id", Map::Team)]),
    },
    TableSpec {
        name: "gameNotices",
        table: "GameNotices",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &["id", "Type", "values", "publish_time_utc"],
        restore: rows(None, true, &[]),
    },
    TableSpec {
        name: "challengeReviews",
        table: "ChallengeReviews",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "user_id",
            "rating",
            "comment",
            "submit_time_utc",
        ],
        restore: rows(None, true, &[CHALLENGE, USER]),
    },
    TableSpec {
        name: "writeupGrades",
        table: "WriteupGrades",
        from: None,
        scope: GAME,
        order: "t.participation_id, t.challenge_id",
        columns: &[
            "participation_id",
            "challenge_id",
            "percentage",
            "revision",
            "operation_id",
            "graded_by",
            "updated_at",
        ],
        restore: rows(
            None,
            true,
            &[PARTICIPATION, CHALLENGE, ("graded_by", Map::User)],
        ),
    },
    TableSpec {
        name: "cheatInfo",
        table: "CheatInfo",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "submit_team_id",
            "source_team_id",
            "submission_id",
            "submit_participation_id",
            "source_participation_id",
            "challenge_id",
            "evidence_key",
            "observed_at_utc",
            "evidence_payload",
            "evidence_version",
        ],
        restore: rows(
            None,
            true,
            &[
                ("submit_team_id", Map::Team),
                ("source_team_id", Map::Team),
                ("submission_id", Map::Submission),
                ("submit_participation_id", Map::Participation),
                ("source_participation_id", Map::Participation),
                CHALLENGE,
            ],
        ),
    },
    TableSpec {
        name: "suspicionEvents",
        table: "SuspicionEvents",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "participation_id",
            "challenge_id",
            "kind",
            "evidence_key",
            "score_delta",
            "created_at",
        ],
        restore: rows(None, true, &[PARTICIPATION, CHALLENGE]),
    },
    TableSpec {
        name: "antiCheatFindings",
        table: "AntiCheatFindings",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "participation_id",
            "user_id",
            "challenge_id",
            "detector_code",
            "detector_version",
            "evidence_family",
            "evidence_tier",
            "score_delta",
            "evidence_key",
            "occurred_at_utc",
            "details",
            "shadow",
            "created_at_utc",
        ],
        restore: rows(Some(Map::Finding), true, &[PARTICIPATION, USER, CHALLENGE]),
    },
    TableSpec {
        name: "antiCheatFindingReviews",
        table: "AntiCheatFindingReviews",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "finding_id",
            "status",
            "reviewed_by_user_id",
            "note",
            "created_at_utc",
        ],
        restore: rows(
            None,
            true,
            &[
                ("finding_id", Map::Finding),
                ("reviewed_by_user_id", Map::User),
            ],
        ),
    },
    TableSpec {
        name: "antiCheatEvidenceRelationships",
        table: "AntiCheatEvidenceRelationships",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "finding_id",
            "related_finding_id",
            "relation_kind",
            "related_source_type",
            "related_source_key",
            "created_at_utc",
        ],
        restore: rows(
            None,
            true,
            &[
                ("finding_id", Map::Finding),
                ("related_finding_id", Map::Finding),
            ],
        ),
    },
    TableSpec {
        name: "aiChatLinks",
        table: "AiChatLinks",
        from: None,
        scope: GAME,
        order: "t.participation_id, t.challenge_id",
        columns: &[
            "participation_id",
            "challenge_id",
            "links",
            "revision",
            "submitted_by",
            "updated_at",
        ],
        restore: rows(
            None,
            true,
            &[PARTICIPATION, CHALLENGE, ("submitted_by", Map::User)],
        ),
    },
];
