//! King of the Hill cycles, tokens, control evidence, and rollups.

use super::*;

pub(super) const KOTH: &[TableSpec] = &[
    TableSpec {
        name: "kothOfficialConfigs",
        table: "KothOfficialConfigs",
        from: None,
        scope: GAME,
        order: "t.game_id",
        columns: &[
            "scoring_start_round",
            "epoch_ticks",
            "cycle_ticks",
            "champion_cooldown_ticks",
            "claim_confirmation_ticks",
            "roster_snapshot",
            "hills_snapshot",
            "created_at",
        ],
        restore: Restore::Rows(RowsRestore {
            id: None,
            game_column: true,
            remaps: &[],
            json_rewrite: Some(JsonRewrite::KothOfficialConfig),
        }),
    },
    TableSpec {
        name: "kothTargets",
        table: "KothTargets",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "host",
            "port",
            "holder_participation_id",
            "held_since",
        ],
        restore: rows(
            Some(Map::KothTarget),
            true,
            &[CHALLENGE, ("holder_participation_id", Map::Participation)],
        ),
    },
    TableSpec {
        name: "kothCrownCycles",
        table: "KothCrownCycles",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "cycle_number",
            "epoch",
            "planned_start_round",
            "planned_end_round",
            "actual_start_round",
            "actual_end_round",
            "phase",
            "expected_image",
            "champion_participation_id",
            "provisional_participation_id",
            "confirmed_participation_id",
            "confirmation_progress",
            "reset_attempt",
            "readiness_attempt",
            "readiness_failures",
            "readiness_error",
            "last_error",
            "audit_receipt",
            "filesystem_diff",
            "finalized_at",
            "reset_started_at",
            "activated_at",
            "completed_at",
            "created_at",
            "updated_at",
        ],
        restore: rows(
            Some(Map::KothCycle),
            true,
            &[
                CHALLENGE,
                ("champion_participation_id", Map::Participation),
                ("provisional_participation_id", Map::Participation),
                ("confirmed_participation_id", Map::Participation),
            ],
        ),
    },
    TableSpec {
        name: "kothTokens",
        table: "KothTokens",
        from: None,
        scope: VIA_KOTH_CYCLE,
        order: "t.id",
        columns: &[
            "id",
            "target_id",
            "participation_id",
            "token",
            "submitted_at",
            "round_number",
            "ad_round_id",
            "revoked_at",
            "cycle_id",
            "challenge_id",
            "reset_attempt",
        ],
        restore: rows(
            Some(Map::KothToken),
            false,
            &[
                ("target_id", Map::KothTarget),
                PARTICIPATION,
                AD_ROUND,
                CYCLE,
                CHALLENGE,
            ],
        ),
    },
    TableSpec {
        name: "kothControlResults",
        table: "KothControlResults",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "ad_round_id",
            "controlling_participation_id",
            "responsible_participation_id",
            "marker_observed",
            "status",
            "error_message",
            "checked_at",
            "dead_container_id",
            "token_window_attempt",
            "cycle_id",
            "container_id",
            "token_id",
            "token_window_round",
            "provisional_participation_id",
            "confirmed_participation_id",
            "confirmation_streak",
            "is_scorable",
            "void_reason",
        ],
        restore: rows(
            None,
            true,
            &[
                CHALLENGE,
                AD_ROUND,
                ("controlling_participation_id", Map::Participation),
                ("responsible_participation_id", Map::Participation),
                CYCLE,
                TOKEN,
                ("provisional_participation_id", Map::Participation),
                ("confirmed_participation_id", Map::Participation),
            ],
        ),
    },
    TableSpec {
        name: "kothAcquisitions",
        table: "KothAcquisitions",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "cycle_id",
            "token_id",
            "challenge_id",
            "target_id",
            "participation_id",
            "container_id",
            "token_window_round",
            "ad_round_id",
            "confirmed_at",
        ],
        restore: rows(
            None,
            true,
            &[
                CYCLE,
                TOKEN,
                CHALLENGE,
                ("target_id", Map::KothTarget),
                PARTICIPATION,
                AD_ROUND,
            ],
        ),
    },
    TableSpec {
        name: "kothCycleCooldowns",
        table: "KothCycleCooldowns",
        from: None,
        scope: VIA_KOTH_CYCLE,
        order: "t.cycle_id, t.participation_id",
        columns: &[
            "cycle_id",
            "participation_id",
            "lead_healthy_controlled_ticks",
            "starts_round",
            "expires_after_round",
            "network_enforced",
            "network_enforced_at",
            "network_released_at",
            "created_at",
        ],
        restore: rows(None, false, &[CYCLE, PARTICIPATION]),
    },
    TableSpec {
        name: "kothEpochRollups",
        table: "KothEpochRollups",
        from: None,
        scope: GAME,
        order: "t.epoch",
        columns: &[
            "epoch",
            "start_round",
            "end_round",
            "round_count",
            "epoch_weight",
            "finalized_round",
            "evidence_finalized_at",
            "scorable_ticks",
            "eligible_windows",
            "cumulative_scorable_ticks",
            "cumulative_eligible_windows",
            "created_at",
        ],
        restore: rows(None, true, &[]),
    },
    TableSpec {
        name: "kothEpochTeamRollups",
        table: "KothEpochTeamRollups",
        from: None,
        scope: GAME,
        order: "t.epoch, t.participation_id",
        columns: &[
            "epoch",
            "participation_id",
            "points",
            "epoch_weight",
            "acquisition_rate",
            "control_rate",
            "sla_rate",
            "acquisition_windows",
            "controlled_ticks",
            "responsible_ticks",
            "healthy_responsible_ticks",
            "cumulative_points_numerator",
            "cumulative_epoch_weight",
            "cumulative_acquisition_numerator",
            "cumulative_control_numerator",
            "cumulative_sla_numerator",
            "cumulative_rate_weight",
            "cumulative_acquisition_windows",
            "cumulative_controlled_ticks",
            "cumulative_responsible_ticks",
            "cumulative_healthy_responsible_ticks",
        ],
        restore: rows(None, true, &[PARTICIPATION]),
    },
    TableSpec {
        name: "kothEpochHillRollups",
        table: "KothEpochHillRollups",
        from: None,
        scope: GAME,
        order: "t.epoch, t.participation_id, t.challenge_id",
        columns: &[
            "epoch",
            "participation_id",
            "challenge_id",
            "service_weight",
            "evidence_fraction",
            "epoch_fraction",
            "local_points",
            "acquisition_rate",
            "control_rate",
            "sla_rate",
            "acquisition_windows",
            "controlled_ticks",
            "responsible_ticks",
            "healthy_responsible_ticks",
            "cumulative_points_numerator",
            "cumulative_score_weight",
            "cumulative_acquisition_numerator",
            "cumulative_control_numerator",
            "cumulative_sla_numerator",
            "cumulative_rate_weight",
            "cumulative_acquisition_windows",
            "cumulative_controlled_ticks",
            "cumulative_responsible_ticks",
            "cumulative_healthy_responsible_ticks",
        ],
        restore: rows(None, true, &[PARTICIPATION, CHALLENGE]),
    },
    TableSpec {
        name: "kothApiScoreResults",
        table: "KothApiScoreResults",
        from: None,
        scope: GAME,
        order: "t.challenge_id, t.ad_round_id, t.participation_id",
        columns: &[
            "challenge_id",
            "ad_round_id",
            "participation_id",
            "activity_earned",
            "activity_possible",
            "objective_earned",
            "objective_possible",
            "objective_count",
            "activity_rate",
            "objective_rate",
            "core_rate",
            "performance_rate",
            "lead_credit",
        ],
        restore: rows(None, true, &[CHALLENGE, AD_ROUND, PARTICIPATION]),
    },
    TableSpec {
        name: "kothApiArenaSchemes",
        table: "KothApiArenaSchemes",
        from: None,
        scope: GAME,
        order: "t.challenge_id",
        columns: &[
            "challenge_id",
            "objective_count",
            "frozen_at",
            "objective_ids",
            "objective_schema_hash",
        ],
        restore: rows(None, true, &[CHALLENGE]),
    },
];
