//! Roster tables restored by identity-aware code.

use super::*;

pub(super) const ROSTER: &[TableSpec] = &[
    TableSpec {
        name: "gameState",
        table: "Games",
        from: None,
        scope: "t.id = $1",
        order: "t.id",
        columns: &[
            "t.ad_scoring_start_round AS adScoringStartRound",
            "t.koth_scoring_start_round AS kothScoringStartRound",
            "t.ad_scoring_paused AS adScoringPaused",
        ],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "users",
        table: "AspNetUsers",
        from: None,
        scope: USERS_SCOPE,
        order: "t.id",
        columns: &["id", "user_name", "email", "real_name", "std_number", "bio"],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "teams",
        table: "Teams",
        from: None,
        scope: r#"t.id IN (SELECT p.team_id FROM "Participations" p WHERE p.game_id = $1)"#,
        order: "t.id",
        columns: &["id", "name", "bio", "locked", "captain_id"],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "teamMembers",
        table: "TeamMembers",
        from: None,
        scope: VIA_TEAM,
        order: "t.team_id, t.user_id",
        columns: &["team_id", "user_id"],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "divisions",
        table: "Divisions",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &["id", "name"],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "participations",
        table: "Participations",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "status",
            "team_id",
            "division_id",
            "suspicion_score",
            "competitive_admitted_at_utc",
        ],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "userParticipations",
        table: "UserParticipations",
        from: None,
        scope: GAME,
        order: "t.user_id",
        columns: &["user_id", "team_id", "participation_id"],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "writeups",
        table: "Participations",
        from: Some(r#""Participations" t JOIN "Files" f ON f.id = t.writeup_id"#),
        scope: GAME,
        order: "t.id",
        columns: &[
            "t.id AS participationId",
            "f.hash AS hash",
            "f.name AS fileName",
            "f.file_size AS fileSize",
        ],
        restore: Restore::Roster,
    },
    TableSpec {
        name: "challengeStates",
        table: "GameChallenges",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "t.id AS challengeId",
            "t.is_enabled AS isEnabled",
            "t.accepted_count AS acceptedCount",
            "t.submission_count AS submissionCount",
        ],
        restore: Restore::Roster,
    },
];
