//! Forensic evidence and telemetry that restore generically.

use super::*;

pub(super) const TELEMETRY: &[TableSpec] = &[
    TableSpec {
        name: "containerAccessEvents",
        table: "ContainerAccessEvents",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "challenge_id",
            "container_owner_participation_id",
            "container_id",
            "accessing_user_id",
            "accessing_user_name",
            "accessing_participation_id",
            "remote_ip",
            "user_agent",
            "connected_at_utc",
            "remote_ip_hash",
            "is_monitor",
        ],
        restore: rows(
            None,
            true,
            &[
                CHALLENGE,
                ("container_owner_participation_id", Map::Participation),
                ("accessing_user_id", Map::User),
                ("accessing_participation_id", Map::Participation),
            ],
        ),
    },
    TableSpec {
        name: "flagEgressEvents",
        table: "FlagEgressEvents",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "participation_id",
            "challenge_id",
            "container_id",
            "remote_ip",
            "remote_port",
            "hit_count",
            "first_seen_utc",
            "last_seen_utc",
        ],
        restore: rows(None, true, &[PARTICIPATION, CHALLENGE]),
    },
    TableSpec {
        name: "honeypotHits",
        table: "HoneypotHits",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "participation_id",
            "user_id",
            "bait",
            "remote_ip",
            "user_agent",
            "hit_at_utc",
            "bucket_start_utc",
            "source_hash",
            "hit_count",
            "sampled_count",
            "last_hit_at_utc",
        ],
        restore: rows(None, true, &[PARTICIPATION, USER]),
    },
    TableSpec {
        name: "identityObservations",
        table: "IdentityObservations",
        from: None,
        scope: GAME,
        order: "t.id",
        columns: &[
            "id",
            "user_id",
            "team_id",
            "participation_id",
            "kind",
            "value_hash",
            "subnet_group_hash",
            "broad_network_hash",
            "value_hint",
            "source",
            "observed_at_utc",
        ],
        restore: rows(None, true, &[USER, ("team_id", Map::Team), PARTICIPATION]),
    },
];
