use super::*;

use std::str::FromStr;

use sqlx::postgres::{PgConnectOptions, PgPoolOptions};

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn create_and_transfer_recheck_live_accounts_atomically() {
    let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
        .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
    let admin_pool = PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
        .unwrap();
    let schema = format!("rsctf_team_accounts_{}", Uuid::new_v4().simple());
    sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
        .execute(&admin_pool)
        .await
        .unwrap();
    let options = PgConnectOptions::from_str(&database_url)
        .unwrap()
        .options([("search_path", schema.as_str())]);
    let pool = PgPoolOptions::new()
        .max_connections(2)
        .connect_with(options)
        .await
        .unwrap();
    sqlx::raw_sql(
        r#"
        CREATE TABLE "AspNetUsers" (
          id UUID PRIMARY KEY,
          email_confirmed BOOLEAN NOT NULL DEFAULT TRUE,
          role SMALLINT NOT NULL,
          security_stamp TEXT
        );
        CREATE TABLE "Teams" (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          bio TEXT,
          avatar_hash TEXT,
          locked BOOLEAN NOT NULL DEFAULT FALSE,
          deletion_pending BOOLEAN NOT NULL DEFAULT FALSE,
          invite_token TEXT NOT NULL,
          captain_id UUID NOT NULL REFERENCES "AspNetUsers"(id)
        );
        CREATE TABLE "TeamMembers" (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          team_id INTEGER NOT NULL,
          user_id UUID NOT NULL
        );
        CREATE TABLE "Configs" (
          config_key TEXT PRIMARY KEY,
          value TEXT
        );
        CREATE TABLE "Games" (id INTEGER PRIMARY KEY, end_time_utc TIMESTAMPTZ NOT NULL);
        CREATE TABLE "Participations" (team_id INTEGER NOT NULL, game_id INTEGER NOT NULL);
        "#,
    )
    .execute(&pool)
    .await
    .unwrap();

    let captain = Uuid::new_v4();
    let member = Uuid::new_v4();
    let banned = Uuid::new_v4();
    for (id, role) in [
        (captain, crate::utils::enums::Role::User),
        (member, crate::utils::enums::Role::User),
        (banned, crate::utils::enums::Role::Banned),
    ] {
        sqlx::query(
            r#"INSERT INTO "AspNetUsers" (id, role, security_stamp)
               VALUES ($1, $2, 'stamp')"#,
        )
        .bind(id)
        .bind(role as i16)
        .execute(&pool)
        .await
        .unwrap();
    }

    let team_id = create_team_rows(&pool, captain, "stamp", "atomic", Some("bio"))
        .await
        .unwrap();
    assert_eq!(
        sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM "TeamMembers" WHERE team_id = $1"#)
            .bind(team_id)
            .fetch_one(&pool)
            .await
            .unwrap(),
        1
    );
    let error = create_team_rows(&pool, banned, "stamp", "forbidden", None)
        .await
        .expect_err("banned account created a team");
    assert_eq!(error.status(), StatusCode::FORBIDDEN);

    let mut policy_transaction = pool.begin().await.unwrap();
    ensure_player_team_creation_allowed(&mut policy_transaction)
        .await
        .expect("missing policy should preserve self-service team creation");
    policy_transaction.rollback().await.unwrap();
    sqlx::query(
        r#"INSERT INTO "Configs" (config_key, value)
           VALUES ('AccountPolicy:AllowTeamCreation', 'false')"#,
    )
    .execute(&pool)
    .await
    .unwrap();
    let mut policy_transaction = pool.begin().await.unwrap();
    let error = ensure_player_team_creation_allowed(&mut policy_transaction)
        .await
        .expect_err("disabled self-service policy allowed player team creation");
    assert_eq!(error.status(), StatusCode::FORBIDDEN);
    assert_eq!(
        error.to_string(),
        "Team creation is managed by an administrator"
    );
    policy_transaction.rollback().await.unwrap();

    for user_id in [member, banned] {
        sqlx::query(r#"INSERT INTO "TeamMembers" (team_id, user_id) VALUES ($1, $2)"#)
            .bind(team_id)
            .bind(user_id)
            .execute(&pool)
            .await
            .unwrap();
    }
    let key = format!("team-roster:{team_id}");
    let mut control = crate::utils::single_flight::PgAdvisoryLock::acquire(&pool, &key)
        .await
        .unwrap();
    let error =
        transfer_captain_locked(control.transaction_mut(), team_id, captain, "stamp", banned)
            .await
            .expect_err("banned account became captain");
    assert_eq!(error.status(), StatusCode::BAD_REQUEST);
    control.release().await.unwrap();

    let mut control = crate::utils::single_flight::PgAdvisoryLock::acquire(&pool, &key)
        .await
        .unwrap();
    transfer_captain_locked(control.transaction_mut(), team_id, captain, "stamp", member)
        .await
        .unwrap();
    control.release().await.unwrap();
    assert_eq!(
        sqlx::query_scalar::<_, Uuid>(r#"SELECT captain_id FROM "Teams" WHERE id = $1"#)
            .bind(team_id)
            .fetch_one(&pool)
            .await
            .unwrap(),
        member
    );

    // A durable account change that wins the row lock invalidates the cached
    // principal before either a new team or captain transfer can commit.
    let stale_creator = Uuid::new_v4();
    sqlx::query(
        r#"INSERT INTO "AspNetUsers" (id, role, security_stamp)
           VALUES ($1, $2, 'stale')"#,
    )
    .bind(stale_creator)
    .bind(crate::utils::enums::Role::User as i16)
    .execute(&pool)
    .await
    .unwrap();
    let mut account_update = pool.begin().await.unwrap();
    sqlx::query(
        r#"UPDATE "AspNetUsers"
              SET email_confirmed = FALSE, security_stamp = 'rotated'
            WHERE id = $1"#,
    )
    .bind(stale_creator)
    .execute(&mut *account_update)
    .await
    .unwrap();
    let create_pool = pool.clone();
    let create = tokio::spawn(async move {
        create_team_rows(&create_pool, stale_creator, "stale", "stale-create", None).await
    });
    tokio::time::sleep(std::time::Duration::from_millis(25)).await;
    account_update.commit().await.unwrap();
    let error = tokio::time::timeout(std::time::Duration::from_secs(5), create)
        .await
        .expect("team creation did not resume after account update")
        .unwrap()
        .expect_err("stale principal created a team");
    assert_eq!(error.status(), StatusCode::FORBIDDEN);
    assert_eq!(
        sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM "Teams" WHERE captain_id = $1"#)
            .bind(stale_creator)
            .fetch_one(&pool)
            .await
            .unwrap(),
        0
    );

    let mut account_update = pool.begin().await.unwrap();
    sqlx::query(
        r#"UPDATE "AspNetUsers"
              SET email_confirmed = FALSE, security_stamp = 'rotated'
            WHERE id = $1"#,
    )
    .bind(member)
    .execute(&mut *account_update)
    .await
    .unwrap();
    let transfer_pool = pool.clone();
    let transfer_key = key.clone();
    let transfer = tokio::spawn(async move {
        let mut control =
            crate::utils::single_flight::PgAdvisoryLock::acquire(&transfer_pool, &transfer_key)
                .await
                .unwrap();
        let result =
            transfer_captain_locked(control.transaction_mut(), team_id, member, "stamp", captain)
                .await;
        control.release().await.unwrap();
        result
    });
    tokio::time::sleep(std::time::Duration::from_millis(25)).await;
    account_update.commit().await.unwrap();
    let error = tokio::time::timeout(std::time::Duration::from_secs(5), transfer)
        .await
        .expect("captain transfer did not resume after account update")
        .unwrap()
        .expect_err("stale principal transferred captaincy");
    assert_eq!(error.status(), StatusCode::FORBIDDEN);
    assert_eq!(
        sqlx::query_scalar::<_, Uuid>(r#"SELECT captain_id FROM "Teams" WHERE id = $1"#)
            .bind(team_id)
            .fetch_one(&pool)
            .await
            .unwrap(),
        member
    );

    sqlx::query(r#"UPDATE "Teams" SET deletion_pending = TRUE WHERE id = $1"#)
        .bind(team_id)
        .execute(&pool)
        .await
        .unwrap();
    let mut control = crate::utils::single_flight::PgAdvisoryLock::acquire(&pool, &key)
        .await
        .unwrap();
    let error = transfer_captain_locked(
        control.transaction_mut(),
        team_id,
        member,
        "rotated",
        captain,
    )
    .await
    .expect_err("captain changed after team deletion started");
    assert_eq!(error.status(), StatusCode::CONFLICT);
    control.release().await.unwrap();

    pool.close().await;
    sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
        .execute(&admin_pool)
        .await
        .unwrap();
}
