use super::*;

use std::str::FromStr;

use sqlx::postgres::{PgConnectOptions, PgPoolOptions};

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn create_and_transfer_recheck_live_accounts_atomically() {
    let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
        .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
    let admin_pool = PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
        .unwrap();
    let schema = format!("rsctf_team_accounts_{}", Uuid::new_v4().simple());
    sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
        .execute(&admin_pool)
        .await
        .unwrap();
    let options = PgConnectOptions::from_str(&database_url)
        .unwrap()
        .options([("search_path", schema.as_str())]);
    let pool = PgPoolOptions::new()
        .max_connections(2)
        .connect_with(options)
        .await
        .unwrap();
    sqlx::raw_sql(
        r#"
        CREATE TABLE "AspNetUsers" (id UUID PRIMARY KEY, role SMALLINT NOT NULL);
        CREATE TABLE "Teams" (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          bio TEXT,
          avatar_hash TEXT,
          locked BOOLEAN NOT NULL DEFAULT FALSE,
          deletion_pending BOOLEAN NOT NULL DEFAULT FALSE,
          invite_token TEXT NOT NULL,
          captain_id UUID NOT NULL REFERENCES "AspNetUsers"(id)
        );
        CREATE TABLE "TeamMembers" (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          team_id INTEGER NOT NULL,
          user_id UUID NOT NULL
        );
        CREATE TABLE "Games" (id INTEGER PRIMARY KEY, end_time_utc TIMESTAMPTZ NOT NULL);
        CREATE TABLE "Participations" (team_id INTEGER NOT NULL, game_id INTEGER NOT NULL);
        "#,
    )
    .execute(&pool)
    .await
    .unwrap();

    let captain = Uuid::new_v4();
    let member = Uuid::new_v4();
    let banned = Uuid::new_v4();
    for (id, role) in [
        (captain, crate::utils::enums::Role::User),
        (member, crate::utils::enums::Role::User),
        (banned, crate::utils::enums::Role::Banned),
    ] {
        sqlx::query(r#"INSERT INTO "AspNetUsers" (id, role) VALUES ($1, $2)"#)
            .bind(id)
            .bind(role as i16)
            .execute(&pool)
            .await
            .unwrap();
    }

    let team_id = create_team_rows(&pool, captain, "atomic", Some("bio"))
        .await
        .unwrap();
    assert_eq!(
        sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM "TeamMembers" WHERE team_id = $1"#)
            .bind(team_id)
            .fetch_one(&pool)
            .await
            .unwrap(),
        1
    );
    let error = create_team_rows(&pool, banned, "forbidden", None)
        .await
        .expect_err("banned account created a team");
    assert_eq!(error.status(), StatusCode::FORBIDDEN);

    for user_id in [member, banned] {
        sqlx::query(r#"INSERT INTO "TeamMembers" (team_id, user_id) VALUES ($1, $2)"#)
            .bind(team_id)
            .bind(user_id)
            .execute(&pool)
            .await
            .unwrap();
    }
    let key = format!("team-roster:{team_id}");
    let mut control = crate::utils::single_flight::PgAdvisoryLock::acquire(&pool, &key)
        .await
        .unwrap();
    let error = transfer_captain_locked(control.transaction_mut(), team_id, captain, banned)
        .await
        .expect_err("banned account became captain");
    assert_eq!(error.status(), StatusCode::BAD_REQUEST);
    control.release().await.unwrap();

    let mut control = crate::utils::single_flight::PgAdvisoryLock::acquire(&pool, &key)
        .await
        .unwrap();
    transfer_captain_locked(control.transaction_mut(), team_id, captain, member)
        .await
        .unwrap();
    control.release().await.unwrap();
    assert_eq!(
        sqlx::query_scalar::<_, Uuid>(r#"SELECT captain_id FROM "Teams" WHERE id = $1"#)
            .bind(team_id)
            .fetch_one(&pool)
            .await
            .unwrap(),
        member
    );

    sqlx::query(r#"UPDATE "Teams" SET deletion_pending = TRUE WHERE id = $1"#)
        .bind(team_id)
        .execute(&pool)
        .await
        .unwrap();
    let mut control = crate::utils::single_flight::PgAdvisoryLock::acquire(&pool, &key)
        .await
        .unwrap();
    let error = transfer_captain_locked(control.transaction_mut(), team_id, member, captain)
        .await
        .expect_err("captain changed after team deletion started");
    assert_eq!(error.status(), StatusCode::CONFLICT);
    control.release().await.unwrap();

    pool.close().await;
    sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
        .execute(&admin_pool)
        .await
        .unwrap();
}
