use std::str::FromStr;

use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
use uuid::Uuid;

use super::{backfill_terminal_build_records, bulk_retry_status_eligible, terminal_audit_status};
use crate::utils::enums::ChallengeBuildStatus;

#[test]
fn synchronous_audit_status_is_always_terminal() {
    assert_eq!(
        terminal_audit_status(ChallengeBuildStatus::Queued),
        ChallengeBuildStatus::Failed
    );
    assert_eq!(
        terminal_audit_status(ChallengeBuildStatus::Building),
        ChallengeBuildStatus::Failed
    );
    assert_eq!(
        terminal_audit_status(ChallengeBuildStatus::Success),
        ChallengeBuildStatus::Success
    );
}

#[test]
fn bulk_retries_only_failed_terminal_states() {
    assert!(bulk_retry_status_eligible(
        ChallengeBuildStatus::Failed as i16
    ));
    assert!(bulk_retry_status_eligible(
        ChallengeBuildStatus::MissingDockerfile as i16
    ));
    assert!(!bulk_retry_status_eligible(
        ChallengeBuildStatus::Success as i16
    ));
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn backfill_only_creates_terminal_history_and_is_idempotent() {
    let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
        .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
    let admin = PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
        .unwrap();
    let schema = format!("build_backfill_{}", Uuid::new_v4().simple());
    sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
        .execute(&admin)
        .await
        .unwrap();
    let options = PgConnectOptions::from_str(&database_url)
        .unwrap()
        .options([("search_path", schema.as_str())]);
    let pool = PgPoolOptions::new()
        .max_connections(2)
        .connect_with(options)
        .await
        .unwrap();

    sqlx::raw_sql(
        r#"
        CREATE TABLE "GameChallenges" (
            id INTEGER PRIMARY KEY,
            game_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            build_status SMALLINT NOT NULL,
            build_image_digest TEXT,
            container_image TEXT,
            last_build_log TEXT
        );
        CREATE TABLE "BuildRecords" (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            challenge_id INTEGER NOT NULL,
            game_id INTEGER NOT NULL,
            challenge_title TEXT NOT NULL,
            enqueued_at_utc TIMESTAMPTZ NOT NULL,
            started_at_utc TIMESTAMPTZ,
            finished_at_utc TIMESTAMPTZ,
            trigger TEXT NOT NULL,
            kind TEXT NOT NULL,
            attempt INTEGER NOT NULL,
            status SMALLINT NOT NULL,
            digest TEXT,
            image_ref TEXT,
            log_tail TEXT
        );
        INSERT INTO "GameChallenges"
            (id, game_id, title, build_status, build_image_digest, container_image, last_build_log)
        VALUES
            (10, 1, 'success', 1, 'sha256:success', 'registry/success@sha256:success', 'ok'),
            (11, 1, 'failed', 2, NULL, 'registry/failed:latest', 'failed'),
            (12, 1, 'missing', 6, NULL, NULL, 'missing Dockerfile'),
            (13, 1, 'building', 3, NULL, NULL, 'building'),
            (14, 1, 'queued', 5, NULL, NULL, 'queued'),
            (15, 1, 'never built', 0, NULL, NULL, NULL);
        INSERT INTO "BuildRecords"
            (challenge_id, game_id, challenge_title, enqueued_at_utc,
             started_at_utc, finished_at_utc, trigger, kind, attempt, status)
        VALUES
            (11, 1, 'failed', now(), now(), now(), 'Manual', 'Challenge', 1, 2);
        "#,
    )
    .execute(&pool)
    .await
    .unwrap();

    let (first, second) = tokio::join!(
        backfill_terminal_build_records(&pool),
        backfill_terminal_build_records(&pool)
    );
    assert_eq!(first + second, 2);
    assert_eq!(backfill_terminal_build_records(&pool).await, 0);

    let rows = sqlx::query_as::<_, (i32, i16, Option<String>, bool)>(
        r#"SELECT challenge_id, status, image_ref, finished_at_utc IS NOT NULL
             FROM "BuildRecords"
            WHERE trigger = 'Backfill'
            ORDER BY challenge_id"#,
    )
    .fetch_all(&pool)
    .await
    .unwrap();
    assert_eq!(
        rows,
        vec![
            (
                10,
                ChallengeBuildStatus::Success as i16,
                Some("registry/success@sha256:success".to_string()),
                true,
            ),
            (
                12,
                ChallengeBuildStatus::MissingDockerfile as i16,
                None,
                true,
            ),
        ]
    );
    assert_eq!(
        sqlx::query_scalar::<_, i64>(
            r#"SELECT COUNT(*) FROM "BuildRecords" WHERE status IN (3, 5)"#,
        )
        .fetch_one(&pool)
        .await
        .unwrap(),
        0
    );

    pool.close().await;
    sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
        .execute(&admin)
        .await
        .unwrap();
    admin.close().await;
}
