use std::str::FromStr;

use chrono::{DateTime, Utc};
use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
use uuid::Uuid;

use super::{load_builds_in_progress, MAX_IN_PROGRESS_BUILDS};

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn in_progress_excludes_finished_and_terminal_rows() {
    let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
        .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
    let admin = PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
        .unwrap();
    let schema = format!("build_in_progress_{}", Uuid::new_v4().simple());
    sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
        .execute(&admin)
        .await
        .unwrap();
    let options = PgConnectOptions::from_str(&database_url)
        .unwrap()
        .options([("search_path", schema.as_str())]);
    let pool = PgPoolOptions::new()
        .max_connections(2)
        .connect_with(options)
        .await
        .unwrap();

    sqlx::raw_sql(
        r#"
        CREATE TABLE "BuildRecords" (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            challenge_id INTEGER NOT NULL,
            game_id INTEGER NOT NULL,
            challenge_title TEXT NOT NULL,
            enqueued_at_utc TIMESTAMPTZ NOT NULL,
            started_at_utc TIMESTAMPTZ,
            finished_at_utc TIMESTAMPTZ,
            trigger TEXT NOT NULL,
            kind TEXT NOT NULL,
            attempt INTEGER NOT NULL,
            status SMALLINT NOT NULL
        );
        INSERT INTO "BuildRecords"
            (id, challenge_id, game_id, challenge_title, enqueued_at_utc,
             started_at_utc, finished_at_utc, trigger, kind, attempt, status)
        VALUES
            (1, 10, 1, 'queued', '2026-01-01T00:00:00Z',
             NULL, NULL, 'Manual', 'Challenge', 1, 5),
            (2, 20, 1, 'building', '2026-01-01T00:01:00Z',
             '2026-01-01T00:01:05Z', NULL, 'Manual', 'Challenge', 2, 3),
            (3, 30, 1, 'stale-finished', '2026-01-01T00:02:00Z',
             '2026-01-01T00:02:05Z', '2026-01-01T00:03:00Z',
             'Backfill', 'Challenge', 1, 5),
            (4, 40, 1, 'success', '2026-01-01T00:04:00Z',
             '2026-01-01T00:04:05Z', NULL, 'Manual', 'Challenge', 1, 1);
        "#,
    )
    .execute(&pool)
    .await
    .unwrap();

    let rows = load_builds_in_progress(&pool).await.unwrap();
    assert_eq!(
        rows.iter().map(|row| row.audit_id).collect::<Vec<_>>(),
        vec![2, 1]
    );
    assert_eq!(rows[0].slug, "building");
    assert_eq!(
        rows[0].started_at_utc,
        "2026-01-01T00:01:05Z".parse::<DateTime<Utc>>().unwrap()
    );
    assert_eq!(
        rows[1].started_at_utc,
        "2026-01-01T00:00:00Z".parse::<DateTime<Utc>>().unwrap()
    );

    sqlx::query(
        r#"INSERT INTO "BuildRecords"
             (id, challenge_id, game_id, challenge_title, enqueued_at_utc,
              trigger, kind, attempt, status)
           SELECT 1000 + item, 1000 + item, 1, 'bulk-' || item,
                  '2026-02-01T00:00:00Z'::timestamptz + item * interval '1 second',
                  'Manual', 'Challenge', 1, 5
             FROM generate_series(1, 250) item"#,
    )
    .execute(&pool)
    .await
    .unwrap();
    let bounded = load_builds_in_progress(&pool).await.unwrap();
    assert_eq!(bounded.len(), MAX_IN_PROGRESS_BUILDS as usize);
    assert_eq!(bounded.first().unwrap().audit_id, 1250);
    assert_eq!(bounded.last().unwrap().audit_id, 1051);

    pool.close().await;
    sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
        .execute(&admin)
        .await
        .unwrap();
    admin.close().await;
}
