use super::*;

use std::str::FromStr;

use crate::services::cache::{Cache, InMemoryCache};
use sqlx::postgres::{PgConnectOptions, PgPoolOptions};

struct Harness {
    admin: sqlx::PgPool,
    pool: sqlx::PgPool,
    cache: InMemoryCache,
    schema: String,
}

impl Harness {
    async fn new() -> Self {
        let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
            .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
        let admin = PgPoolOptions::new()
            .max_connections(1)
            .connect(&database_url)
            .await
            .unwrap();
        let schema = format!("rsctf_bulk_identity_{}", Uuid::new_v4().simple());
        sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
            .execute(&admin)
            .await
            .unwrap();
        let options = PgConnectOptions::from_str(&database_url)
            .unwrap()
            .options([("search_path", schema.as_str())]);
        let pool = PgPoolOptions::new()
            .max_connections(4)
            .connect_with(options)
            .await
            .unwrap();
        sqlx::raw_sql(
            r#"
            CREATE TABLE "AspNetUsers" (
              id UUID PRIMARY KEY,
              user_name TEXT,
              normalized_user_name TEXT UNIQUE,
              email TEXT,
              normalized_email TEXT,
              email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
              password_hash TEXT,
              security_stamp TEXT,
              concurrency_stamp TEXT,
              phone_number TEXT,
              phone_number_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
              two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
              lockout_end TIMESTAMPTZ,
              lockout_enabled BOOLEAN NOT NULL DEFAULT FALSE,
              access_failed_count INTEGER NOT NULL DEFAULT 0,
              role SMALLINT NOT NULL,
              ip TEXT NOT NULL DEFAULT '0.0.0.0',
              browser_fingerprint TEXT,
              last_signed_in_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
              last_visited_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
              register_time_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
              bio TEXT NOT NULL DEFAULT '',
              real_name TEXT NOT NULL DEFAULT '',
              std_number TEXT NOT NULL DEFAULT '',
              exercise_visible BOOLEAN NOT NULL DEFAULT TRUE,
              avatar_hash TEXT
            );
            CREATE TABLE "Teams" (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name TEXT NOT NULL,
              bio TEXT,
              avatar_hash TEXT,
              locked BOOLEAN NOT NULL DEFAULT FALSE,
              deletion_pending BOOLEAN NOT NULL DEFAULT FALSE,
              invite_token TEXT NOT NULL,
              captain_id UUID NOT NULL
            );
            CREATE TABLE "TeamMembers" (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              team_id INTEGER NOT NULL,
              user_id UUID NOT NULL,
              UNIQUE (team_id, user_id)
            );
            "#,
        )
        .execute(&pool)
        .await
        .unwrap();
        Self {
            admin,
            pool,
            cache: InMemoryCache::new(),
            schema,
        }
    }

    async fn cleanup(self) {
        self.pool.close().await;
        sqlx::query(&format!(r#"DROP SCHEMA "{}" CASCADE"#, self.schema))
            .execute(&self.admin)
            .await
            .unwrap();
    }
}

async fn insert_user(
    executor: impl sqlx::Executor<'_, Database = sqlx::Postgres>,
    id: Uuid,
    user_name: &str,
    email: &str,
    role: Role,
    password_hash: &str,
    security_stamp: &str,
) {
    sqlx::query(
        r#"INSERT INTO "AspNetUsers"
             (id, user_name, normalized_user_name, email, normalized_email,
              password_hash, security_stamp, role)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8)"#,
    )
    .bind(id)
    .bind(user_name)
    .bind(user_name.to_uppercase())
    .bind(email)
    .bind(email.to_uppercase())
    .bind(password_hash)
    .bind(security_stamp)
    .bind(role as i16)
    .execute(executor)
    .await
    .unwrap();
}

fn explicit_write<'a>(
    user_name: &'a str,
    email: &'a str,
    password_hash: &'a str,
) -> ExplicitUserWrite<'a> {
    ExplicitUserWrite {
        user_name,
        normalized_user_name: user_name,
        email,
        normalized_email: email,
        password_hash,
        phone: None,
        create_real_name: "",
        create_std_number: "",
        update_real_name: None,
        update_std_number: None,
        update_phone: None,
        now: Utc::now(),
    }
}

fn import_write<'a>(email: &'a str, password_hash: &'a str) -> ImportUserWrite<'a> {
    ImportUserWrite {
        email,
        normalized_email: email,
        base_user_name: "imported",
        password_hash,
        email_confirmed: true,
        create_real_name: "Imported User",
        create_std_number: "",
        create_phone: None,
        update_real_name: Some("Imported User"),
        update_std_number: None,
        update_phone: None,
        now: Utc::now(),
    }
}

fn credential_write<'a>(harness: &'a Harness, password: &'a str) -> ImportCredentialWrite<'a> {
    ImportCredentialWrite {
        cache: &harness.cache,
        password,
    }
}

struct BlockingSetCache {
    inner: InMemoryCache,
    set_started: std::sync::Mutex<Option<tokio::sync::oneshot::Sender<()>>>,
    release_set: tokio::sync::Mutex<Option<tokio::sync::oneshot::Receiver<()>>>,
}

impl BlockingSetCache {
    fn new() -> (
        Self,
        tokio::sync::oneshot::Receiver<()>,
        tokio::sync::oneshot::Sender<()>,
    ) {
        let (set_started, wait_for_set) = tokio::sync::oneshot::channel();
        let (release_set, wait_for_release) = tokio::sync::oneshot::channel();
        (
            Self {
                inner: InMemoryCache::new(),
                set_started: std::sync::Mutex::new(Some(set_started)),
                release_set: tokio::sync::Mutex::new(Some(wait_for_release)),
            },
            wait_for_set,
            release_set,
        )
    }
}

#[async_trait::async_trait]
impl Cache for BlockingSetCache {
    async fn get(&self, key: &str) -> Option<bytes::Bytes> {
        self.inner.get(key).await
    }

    async fn get_and_remove(&self, key: &str) -> Option<bytes::Bytes> {
        self.inner.get_and_remove(key).await
    }

    async fn compare_and_remove(&self, key: &str, expected: &[u8]) -> bool {
        self.inner.compare_and_remove(key, expected).await
    }

    async fn set_if_absent(
        &self,
        key: &str,
        value: &[u8],
        ttl: Option<std::time::Duration>,
    ) -> bool {
        self.inner.set_if_absent(key, value, ttl).await
    }

    async fn set(&self, key: &str, value: &[u8], ttl: Option<std::time::Duration>) {
        if let Some(set_started) = self.set_started.lock().unwrap().take() {
            let _ = set_started.send(());
        }
        let release_set = { self.release_set.lock().await.take() };
        if let Some(release_set) = release_set {
            release_set.await.unwrap();
        }
        self.inner.set(key, value, ttl).await;
    }

    async fn remove(&self, key: &str) {
        self.inner.remove(key).await;
    }
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn explicit_bulk_identity_rejects_cross_owner_matches() {
    let harness = Harness::new().await;
    let alice = Uuid::new_v4();
    let bob = Uuid::new_v4();
    insert_user(
        &harness.pool,
        alice,
        "alice",
        "alice@example.test",
        Role::User,
        "alice-old",
        "alice-stamp",
    )
    .await;
    insert_user(
        &harness.pool,
        bob,
        "bob",
        "bob@example.test",
        Role::User,
        "bob-old",
        "bob-stamp",
    )
    .await;

    let error = provision_explicit_user(
        &harness.pool,
        explicit_write("ALICE", "BOB@EXAMPLE.TEST", "new-hash"),
        None,
        None,
    )
    .await
    .expect_err("username owner was re-credentialed with another account's email");
    assert_eq!(error.status(), axum::http::StatusCode::CONFLICT);
    let rows: Vec<(Uuid, Option<String>, Option<String>)> = sqlx::query_as(
        r#"SELECT id, password_hash, security_stamp FROM "AspNetUsers" ORDER BY id"#,
    )
    .fetch_all(&harness.pool)
    .await
    .unwrap();
    assert!(rows.contains(&(alice, Some("alice-old".into()), Some("alice-stamp".into()))));
    assert!(rows.contains(&(bob, Some("bob-old".into()), Some("bob-stamp".into()))));
    harness.cleanup().await;
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn registration_lock_closes_bulk_creation_precheck_race() {
    let harness = Harness::new().await;
    let public_id = Uuid::new_v4();
    let mut public_registration = crate::utils::database::begin_sqlx_transaction(&harness.pool)
        .await
        .unwrap();
    sqlx::query("SELECT pg_advisory_xact_lock($1)")
        .bind(crate::controllers::account::REGISTRATION_LOCK_ID)
        .execute(&mut *public_registration)
        .await
        .unwrap();

    let contender = tokio::spawn({
        let pool = harness.pool.clone();
        async move {
            provision_explicit_user(
                &pool,
                explicit_write("RACER", "RACER@EXAMPLE.TEST", "bulk-hash"),
                None,
                None,
            )
            .await
        }
    });
    tokio::task::yield_now().await;
    insert_user(
        &mut *public_registration,
        public_id,
        "racer",
        "racer@example.test",
        Role::User,
        "public-hash",
        "public-stamp",
    )
    .await;
    public_registration.commit().await.unwrap();

    let result = contender.await.unwrap().unwrap();
    assert_eq!(result.id, public_id);
    assert!(!result.created);
    let count: i64 = sqlx::query_scalar(
        r#"SELECT COUNT(*)::bigint FROM "AspNetUsers" WHERE normalized_email = 'RACER@EXAMPLE.TEST'"#,
    )
    .fetch_one(&harness.pool)
    .await
    .unwrap();
    assert_eq!(count, 1);
    harness.cleanup().await;
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn failed_team_assignment_rolls_back_recredential_and_creation() {
    let harness = Harness::new().await;
    let captain = Uuid::new_v4();
    let existing = Uuid::new_v4();
    for (id, name, email) in [
        (captain, "captain", "captain@example.test"),
        (existing, "existing", "existing@example.test"),
    ] {
        insert_user(
            &harness.pool,
            id,
            name,
            email,
            Role::User,
            "old-hash",
            "old-stamp",
        )
        .await;
    }
    sqlx::query(
        r#"INSERT INTO "Teams"
             (id, name, deletion_pending, invite_token, captain_id)
           VALUES (1, 'deleting', TRUE, 'token', $1),
                  (2, 'full', FALSE, 'token', $1)"#,
    )
    .bind(captain)
    .execute(&harness.pool)
    .await
    .unwrap();
    let synthetic_members: Vec<Uuid> = (0..99).map(|_| Uuid::new_v4()).collect();
    sqlx::query(
        r#"INSERT INTO "TeamMembers" (team_id, user_id)
           SELECT 2, member_id FROM UNNEST($1::uuid[]) AS member_id"#,
    )
    .bind(&synthetic_members)
    .execute(&harness.pool)
    .await
    .unwrap();

    let deleting = provision_import_user(
        &harness.pool,
        import_write("EXISTING@EXAMPLE.TEST", "new-delete-hash"),
        credential_write(&harness, "new-delete-password"),
        Some("deleting"),
        None,
    )
    .await
    .expect_err("deletion-pending team accepted an import");
    assert_eq!(deleting.status(), axum::http::StatusCode::CONFLICT);
    let full = provision_import_user(
        &harness.pool,
        import_write("EXISTING@EXAMPLE.TEST", "new-full-hash"),
        credential_write(&harness, "new-full-password"),
        Some("full"),
        None,
    )
    .await
    .expect_err("full team accepted an import");
    assert_eq!(full.status(), axum::http::StatusCode::BAD_REQUEST);
    let identity: (Option<String>, Option<String>) =
        sqlx::query_as(r#"SELECT password_hash, security_stamp FROM "AspNetUsers" WHERE id = $1"#)
            .bind(existing)
            .fetch_one(&harness.pool)
            .await
            .unwrap();
    assert_eq!(
        identity,
        (Some("old-hash".into()), Some("old-stamp".into()))
    );

    let error = provision_import_user(
        &harness.pool,
        import_write("NEW@EXAMPLE.TEST", "undisclosed-hash"),
        credential_write(&harness, "undisclosed-password"),
        Some("full"),
        None,
    )
    .await
    .expect_err("full team left a newly-created account behind");
    assert_eq!(error.status(), axum::http::StatusCode::BAD_REQUEST);
    let orphan_count: i64 = sqlx::query_scalar(
        r#"SELECT COUNT(*)::bigint FROM "AspNetUsers" WHERE normalized_email = 'NEW@EXAMPLE.TEST'"#,
    )
    .fetch_one(&harness.pool)
    .await
    .unwrap();
    assert_eq!(orphan_count, 0);
    assert!(
        harness
            .cache
            .get(
                &crate::controllers::admin::users_credentials::credential_cache_key(
                    "existing@example.test",
                )
            )
            .await
            .is_none(),
        "a rolled-back recredential published plaintext"
    );
    assert!(
        harness
            .cache
            .get(
                &crate::controllers::admin::users_credentials::credential_cache_key(
                    "new@example.test",
                )
            )
            .await
            .is_none(),
        "a rolled-back account creation published plaintext"
    );
    harness.cleanup().await;
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn later_full_team_failure_is_a_skipped_row_without_losing_other_results() {
    use super::super::users::{import_row_step, ImportUserResult};
    use crate::controllers::admin::users_credentials::credential_cache_key;

    let harness = Harness::new().await;
    let captain = Uuid::new_v4();
    insert_user(
        &harness.pool,
        captain,
        "captain",
        "captain@example.test",
        Role::User,
        "captain-hash",
        "captain-stamp",
    )
    .await;
    sqlx::query(
        r#"INSERT INTO "Teams"
             (id, name, deletion_pending, invite_token, captain_id)
           VALUES (1, 'full', FALSE, 'token', $1)"#,
    )
    .bind(captain)
    .execute(&harness.pool)
    .await
    .unwrap();
    let synthetic_members: Vec<Uuid> = (0..99).map(|_| Uuid::new_v4()).collect();
    sqlx::query(
        r#"INSERT INTO "TeamMembers" (team_id, user_id)
           SELECT 1, member_id FROM UNNEST($1::uuid[]) AS member_id"#,
    )
    .bind(&synthetic_members)
    .execute(&harness.pool)
    .await
    .unwrap();

    let first = import_row_step(
        provision_import_user(
            &harness.pool,
            import_write("FIRST@EXAMPLE.TEST", "first-hash"),
            credential_write(&harness, "first-password"),
            None,
            None,
        )
        .await,
        1,
        "provision",
    )
    .unwrap();
    let ImportProvision::Provisioned(first) = first else {
        panic!("first row was unexpectedly skipped");
    };
    let mut response_rows = vec![ImportUserResult {
        email: "first@example.test".to_string(),
        real_name: "First".to_string(),
        user_name: first.user_name,
        password: "first-password".to_string(),
        team_name: None,
        status: "created".to_string(),
        error: None,
    }];

    let second_reason = import_row_step(
        provision_import_user(
            &harness.pool,
            import_write("SECOND@EXAMPLE.TEST", "second-hash"),
            credential_write(&harness, "second-password"),
            Some("full"),
            Some(1),
        )
        .await,
        2,
        "provision",
    )
    .expect_err("full team unexpectedly accepted the second row");
    response_rows.push(ImportUserResult {
        email: "second@example.test".to_string(),
        real_name: "Second".to_string(),
        user_name: "imported.2".to_string(),
        password: String::new(),
        team_name: Some("full".to_string()),
        status: "skipped".to_string(),
        error: Some(second_reason),
    });

    let third = import_row_step(
        provision_import_user(
            &harness.pool,
            import_write("THIRD@EXAMPLE.TEST", "third-hash"),
            credential_write(&harness, "third-password"),
            None,
            None,
        )
        .await,
        3,
        "provision",
    )
    .unwrap();
    let ImportProvision::Provisioned(third) = third else {
        panic!("third row did not continue after the second row was skipped");
    };
    response_rows.push(ImportUserResult {
        email: "third@example.test".to_string(),
        real_name: "Third".to_string(),
        user_name: third.user_name,
        password: "third-password".to_string(),
        team_name: None,
        status: "created".to_string(),
        error: None,
    });

    assert_eq!(response_rows.len(), 3);
    assert_eq!(response_rows[0].password, "first-password");
    assert_eq!(response_rows[1].status, "skipped");
    assert_eq!(response_rows[1].password, "");
    assert_eq!(response_rows[1].error.as_deref(), Some("Team is full"));
    assert_eq!(response_rows[2].password, "third-password");
    assert!(
        harness
            .cache
            .get(&credential_cache_key("first@example.test"))
            .await
            .is_some(),
        "later failure removed the first committed credential"
    );
    assert!(
        harness
            .cache
            .get(&credential_cache_key("second@example.test"))
            .await
            .is_none(),
        "rolled-back second row published plaintext"
    );

    harness.cleanup().await;
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn credential_publication_precedes_a_concurrent_email_mutation() {
    use crate::controllers::admin::users_credentials::{
        credential_cache_key, CachedImportCredential,
    };

    let harness = Harness::new().await;
    let user_id = Uuid::new_v4();
    insert_user(
        &harness.pool,
        user_id,
        "alice",
        "old@example.test",
        Role::User,
        "old-hash",
        "old-stamp",
    )
    .await;

    let (cache, publication_started, release_publication) = BlockingSetCache::new();
    let cache = std::sync::Arc::new(cache);
    let import_pool = harness.pool.clone();
    let import_cache = cache.clone();
    let import = tokio::spawn(async move {
        provision_import_user(
            &import_pool,
            import_write("OLD@EXAMPLE.TEST", "new-hash"),
            ImportCredentialWrite {
                cache: import_cache.as_ref(),
                password: "new-password",
            },
            None,
            None,
        )
        .await
    });
    publication_started.await.unwrap();

    let mutation_pool = harness.pool.clone();
    let (mutation_started, wait_for_mutation) = tokio::sync::oneshot::channel();
    let mut mutation = tokio::spawn(async move {
        mutation_started.send(()).unwrap();
        let mut transaction = registration_transaction(&mutation_pool).await.unwrap();
        sqlx::query(
            r#"UPDATE "AspNetUsers"
                  SET email = 'new@example.test',
                      normalized_email = 'NEW@EXAMPLE.TEST'
                WHERE id = $1"#,
        )
        .bind(user_id)
        .execute(&mut *transaction)
        .await
        .unwrap();
        transaction.commit().await.unwrap();
    });
    wait_for_mutation.await.unwrap();
    assert!(
        tokio::time::timeout(std::time::Duration::from_millis(100), &mut mutation)
            .await
            .is_err(),
        "email mutation crossed the import's publication/commit boundary"
    );

    release_publication.send(()).unwrap();
    let provision = import.await.unwrap().unwrap();
    let ImportProvision::Provisioned(provision) = provision else {
        panic!("the import was hidden after committing its generated password");
    };
    assert_eq!(provision.id, user_id);
    assert!(!provision.created);
    tokio::time::timeout(std::time::Duration::from_secs(2), mutation)
        .await
        .expect("email mutation stayed blocked after the import committed")
        .unwrap();

    let identity: (Option<String>, Option<String>, Option<String>) = sqlx::query_as(
        r#"SELECT normalized_email, password_hash, security_stamp
             FROM "AspNetUsers" WHERE id = $1"#,
    )
    .bind(user_id)
    .fetch_one(&harness.pool)
    .await
    .unwrap();
    assert_eq!(identity.0.as_deref(), Some("NEW@EXAMPLE.TEST"));
    assert_eq!(identity.1.as_deref(), Some("new-hash"));
    assert_eq!(
        identity.2.as_deref(),
        Some(provision.security_stamp.as_str())
    );

    // This is the worst case if a caller mutates the email but crashes before
    // invalidating the old key: delivery still rejects it because its embedded
    // id/email/stamp tuple no longer matches the live row.
    let value = cache
        .get(&credential_cache_key("old@example.test"))
        .await
        .expect("credential was not published before commit");
    let credential: CachedImportCredential = serde_json::from_slice(&value).unwrap();
    assert_eq!(credential.user_id, user_id);
    assert_eq!(credential.security_stamp, provision.security_stamp);
    assert_eq!(credential.password, "new-password");

    harness.cleanup().await;
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn failed_commit_removes_the_just_published_plaintext() {
    use crate::controllers::admin::users_credentials::credential_cache_key;

    let harness = Harness::new().await;
    sqlx::raw_sql(
        r#"
        CREATE FUNCTION reject_import_commit() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.password_hash = 'commit-fail-hash' THEN
            RAISE EXCEPTION 'forced deferred import failure';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE CONSTRAINT TRIGGER reject_import_commit
          AFTER INSERT OR UPDATE ON "AspNetUsers"
          DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION reject_import_commit();
        "#,
    )
    .execute(&harness.pool)
    .await
    .unwrap();

    let error = provision_import_user(
        &harness.pool,
        import_write("ROLLBACK@EXAMPLE.TEST", "commit-fail-hash"),
        credential_write(&harness, "must-not-survive"),
        None,
        None,
    )
    .await
    .expect_err("deferred constraint unexpectedly allowed the import to commit");
    assert_eq!(
        error.status(),
        axum::http::StatusCode::INTERNAL_SERVER_ERROR
    );
    let user_count: i64 = sqlx::query_scalar(
        r#"SELECT COUNT(*)::bigint FROM "AspNetUsers"
            WHERE normalized_email = 'ROLLBACK@EXAMPLE.TEST'"#,
    )
    .fetch_one(&harness.pool)
    .await
    .unwrap();
    assert_eq!(user_count, 0, "failed commit left the account live");
    assert!(
        harness
            .cache
            .get(&credential_cache_key("rollback@example.test"))
            .await
            .is_none(),
        "failed commit left its plaintext cache publication live"
    );

    harness.cleanup().await;
}

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn credential_publication_tracks_the_last_committed_import() {
    use crate::controllers::admin::users_credentials::{
        credential_cache_key, CachedImportCredential,
    };

    let harness = Harness::new().await;
    let email = "race@example.test";
    let normalized_email = "RACE@EXAMPLE.TEST";
    let first = provision_import_user(
        &harness.pool,
        import_write(normalized_email, "first-hash"),
        credential_write(&harness, "first-password"),
        None,
        None,
    )
    .await
    .unwrap();
    let ImportProvision::Provisioned(first) = first else {
        panic!("first import was unexpectedly skipped");
    };
    let second = provision_import_user(
        &harness.pool,
        import_write(normalized_email, "second-hash"),
        credential_write(&harness, "second-password"),
        None,
        None,
    )
    .await
    .unwrap();
    let ImportProvision::Provisioned(second) = second else {
        panic!("second import was unexpectedly skipped");
    };
    assert_eq!(first.id, second.id);
    assert_ne!(first.security_stamp, second.security_stamp);

    let value = harness
        .cache
        .get(&credential_cache_key(email))
        .await
        .expect("newest credential disappeared");
    let credential: CachedImportCredential = serde_json::from_slice(&value).unwrap();
    assert_eq!(credential.user_id, second.id);
    assert_eq!(credential.security_stamp, second.security_stamp);
    assert_eq!(credential.password, "second-password");
    harness.cleanup().await;
}
