import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'

const provider = readFileSync('src/components/guide/PlayerGuide.tsx', 'utf8')
const spotlight = readFileSync('src/components/guide/GuideSpotlightModal.tsx', 'utf8')
const spotlightStyles = readFileSync('src/styles/components/PlayerGuide.module.css', 'utf8')
const guideLayout = readFileSync('src/utils/GuideLayout.ts', 'utf8')
const guideState = readFileSync('src/utils/GuideState.ts', 'utf8')
const page = readFileSync('src/pages/guide/Index.tsx', 'utf8')
const app = readFileSync('src/App.tsx', 'utf8')
const navigation = readFileSync('src/components/navigation.ts', 'utf8')
const challengeModal = readFileSync('src/components/GameChallengeModal.tsx', 'utf8')
const challengeModalShell = readFileSync('src/components/ChallengeModal.tsx', 'utf8')
const instanceEntry = readFileSync('src/components/InstanceEntry.tsx', 'utf8')
const eventPage = readFileSync('src/pages/games/[id]/Index.tsx', 'utf8')
const appHeader = readFileSync('src/components/AppHeader.tsx', 'utf8')
const appNavbar = readFileSync('src/components/AppNavbar.tsx', 'utf8')
const teamsPage = readFileSync('src/pages/Teams.tsx', 'utf8')
const profilePage = readFileSync('src/pages/account/Profile.tsx', 'utf8')
const accountView = readFileSync('src/components/AccountView.tsx', 'utf8')
const loginPage = readFileSync('src/pages/account/Login.tsx', 'utf8')
const oauthButtons = readFileSync('src/components/OAuthButtons.tsx', 'utf8')
const teamCreateModal = readFileSync('src/components/TeamCreateModal.tsx', 'utf8')
const teamJoinModal = readFileSync('src/components/TeamJoinModal.tsx', 'utf8')
const gameJoinModal = readFileSync('src/components/GameJoinModal.tsx', 'utf8')
const accessibleModal = readFileSync('src/components/AccessibleModal.tsx', 'utf8')
const challengeCard = readFileSync('src/components/ChallengeCard.tsx', 'utf8')
const config = readFileSync('src/hooks/useConfig.ts', 'utf8')
const pageStyles = readFileSync('src/styles/pages/PlayerGuidePage.module.css', 'utf8')

test('interactive guide is account-scoped, restartable, dismissible, and storage-failure safe', () => {
  assert.match(provider, /guideStorageKey\(identity\)/)
  assert.match(provider, /user\?\.userId/)
  assert.match(provider, /resolveGuideIdentity\(user\?\.userId, userError\?\.status\)/)
  assert.match(provider, /interactiveEnabled/)
  assert.match(provider, /resetGuideProgress/)
  assert.match(provider, /preferences\.activeTourStep/)
  assert.match(provider, /updatePreferences\(pauseGuide\)/)
  assert.match(provider, /setGuideTourStep/)
  assert.doesNotMatch(provider, /setTourOpen/)
  assert.match(provider, /Stop guide/)
  assert.match(provider, /preferencesRef\.current/)
  assert.match(provider, /persistGuidePreferenceUpdate\(preferencesRef\.current/)
  assert.match(guideState, /try \{[\s\S]*persist\(JSON\.stringify\(next\)\)[\s\S]*\} catch/)
  assert.match(spotlight, /<Modal\.Root[\s\S]*returnFocus[\s\S]*trapFocus/)
  assert.match(spotlight, /trapFocus=\{!target && !yielding\}/)
  assert.match(spotlight, /setAttribute\('aria-modal', target \|\| yielding \? 'false' : 'true'\)/)
  assert.match(spotlight, /data-autofocus/)
  assert.match(spotlight, /bodyRef\.current\?\.focus\(\{ preventScroll: true \}\)/)
  assert.match(spotlight, /onEnterTransitionEnd=/)
  assert.match(spotlight, /<Modal\.Title>/)
  assert.match(spotlight, /<Modal\.Header role="presentation"/)
  assert.match(app, /<PlayerGuideProvider>/)
})

test('interactive guide spotlights real controls and provides a reduced-motion game cursor', () => {
  assert.match(provider, /targetSelector:/)
  assert.match(instanceEntry, /data-guide="instance-start"/)
  assert.match(instanceEntry, /data-guide="instance-entry"/)
  assert.match(appHeader, /data-guide="more-navigation"/)
  assert.match(appHeader, /<Drawer\.Header role="presentation">/)
  assert.match(appHeader, /<Drawer\.Title>/)
  assert.match(appHeader, /<Drawer\.CloseButton aria-label=/)
  assert.match(
    appNavbar,
    /width=\{240\}[\s\S]*withinPortal=\{false\}[\s\S]*withInitialFocusPlaceholder=\{false\}[\s\S]*data-guide="account-menu"/
  )
  assert.match(guideState, /guide-navigation[\s\S]*more-navigation/)
  assert.match(spotlight, /selector[\s\S]*\.split\(','\)[\s\S]*querySelectorAll<HTMLElement>\(candidate\)/)
  assert.match(spotlight, /scrollIntoView\(/)
  assert.match(spotlight, /separationAttempt/)
  assert.match(spotlight, /scrollableAncestor/)
  assert.match(spotlight, /scrollParent\.scrollBy\(\{ top: scrollDelta/)
  assert.match(spotlight, /targetVisibleRatio\(element\) >= 0\.75/)
  assert.match(spotlight, /document\.elementsFromPoint/)
  assert.match(spotlight, /renderedTargets\(selector\)\?\.find\(isUsableTarget\)/)
  assert.match(spotlight, /let selectedTarget: HTMLElement \| null = null/)
  assert.match(
    spotlight,
    /selectedTarget && \(!selectedTarget\.isConnected \|\| !targets\.includes\(selectedTarget\)\)/
  )
  assert.match(spotlight, /targetIsElevated\(usableTarget\)[\s\S]*!targetIsElevated\(selectedTarget\)/)
  assert.match(spotlight, /const preferredTarget = stableTarget\(\)/)
  assert.match(spotlight, /prefers-reduced-motion: reduce/)
  assert.match(spotlight, /mdiCursorDefaultClickOutline/)
  assert.match(spotlight, /showTargetCursor &&/)
  assert.match(spotlight, /data-guide-layer="spotlight"/)
  assert.match(spotlight, /data-guide-layer="cursor"/)
  assert.match(spotlight, /data-guide-layer="interaction-blocker"/)
  assert.match(spotlight, /!target\.elevated[\s\S]*!surroundingInteractionAllowed/)
  assert.match(spotlight, /data-guide-surface="coachmark"/)
  assert.match(spotlight, /data-guide-placement=/)
  assert.match(spotlight, /data-guide-target=/)
  assert.match(spotlight, /document\.addEventListener\('click', handleTargetClick, true\)/)
  assert.match(spotlight, /document\.addEventListener\('focusin', handleTargetFocus, true\)/)
  assert.match(spotlight, /guideTargetAcceptsKeyboardEntry\(element\)/)
  assert.match(spotlight, /guideTargetKeyboardActivation\(focusedElement, document\.activeElement\)/)
  assert.match(spotlight, /guideTargetKeyboardActivation\(element, event\.target instanceof Element/)
  assert.match(spotlight, /const guideTarget = element\.dataset\.guide/)
  assert.match(spotlight, /onTargetActivate\(guideTarget\)/)
  assert.doesNotMatch(spotlight, /requestAnimationFrame\(\(\) => onTargetActivate/)
  assert.match(spotlight, /new MutationObserver\(update\)/)
  assert.match(spotlight, /observer\.observe\(document\.body, \{ childList: true, subtree: true \}\)/)
  assert.match(spotlight, /onTargetActivate\(guideTarget\)/)
  assert.match(spotlight, /onTargetChange\?\.\(opened \? target\?\.guideTarget : undefined\)/)
  assert.match(spotlight, /guideLayerZIndex\(target\)/)
  assert.match(spotlight, /\[role="dialog"\]/)
  assert.match(spotlight, /externalSurface && !target\?\.elevated/)
  assert.match(spotlight, /trapFocus=\{!target && !yielding\}/)
  assert.match(spotlight, /lockScroll=\{!target && !yielding\}/)
  assert.match(spotlight, /data-guide-yielding=\{yielding \|\| undefined\}/)
  assert.match(spotlight, /aria-hidden=\{yielding \|\| undefined\}/)
  assert.match(spotlight, /closeOnClickOutside=\{false\}/)
  assert.match(spotlight, /pointerEvents: target \|\| yielding \? 'none'/)
  assert.match(spotlight, /<Modal\.Body[\s\S]*tabIndex=\{0\}[\s\S]*aria-label=\{title\}/)
  assert.match(spotlight, /fillRule="evenodd"/)
  assert.match(spotlightStyles, /\.tutorialSpotlight/)
  assert.match(spotlightStyles, /\.tutorialCursor/)
  assert.match(spotlightStyles, /\.tutorialBlocker/)
  assert.match(spotlightStyles, /prefers-reduced-motion[\s\S]*\.tutorialSpotlight/)
  assert.match(spotlightStyles, /height: auto/)
  assert.match(spotlightStyles, /flex: 0 1 auto/)
  assert.match(spotlightStyles, /max-height: min\(18rem, calc\(100dvh - 10rem\)\)/)
  assert.match(spotlightStyles, /\.modalProgress/)
  assert.match(spotlightStyles, /\.targetPrompt/)
  assert.match(spotlightStyles, /@media \(max-height: 40em\)[\s\S]*\.note/)
  assert.match(provider, /size="min\(21rem, calc\(100vw - 1rem\)\)"/)
  assert.doesNotMatch(provider, /size="min\(36rem/)
  assert.match(guideLayout, /target\.viewportHeight \* 0\.42/)
  assert.match(guideLayout, /GUIDE_PAGE_Z_INDEX = 150/)
  assert.match(guideLayout, /GUIDE_ELEVATED_Z_INDEX = 500/)
  assert.match(guideLayout, /MOBILE_TOP_SAFE_INSET = 76/)
  assert.match(guideLayout, /MOBILE_BOTTOM_SAFE_INSET = 82/)
  assert.match(guideLayout, /placement: 'docked'/)
  assert.doesNotMatch(guideLayout, /placement: 'center'/)
  assert.match(guideLayout, /dockAtTop/)
  assert.match(guideLayout, /targetSideBudget/)
  assert.doesNotMatch(spotlightStyles, /z-index: 700/)
  assert.match(provider, /requiresTargetActivation: true/)
  assert.match(provider, /Select the highlighted control to continue/)
  assert.doesNotMatch(provider, /disabled=\{needsNavigation \|\| needsTargetActivation\}/)
})

test('guide content follows the effective platform and event connection settings', () => {
  for (const field of [
    'allowRegister',
    'allowPasswordRegistration',
    'emailConfirmationRequired',
    'enableGoogleAuth',
    'enableDiscordAuth',
    'portMapping',
  ]) {
    assert.match(provider, new RegExp(`config\\.${field}`), field)
  }
  assert.match(config, /allowRegister: true/)
  assert.match(config, /emailConfirmationRequired: false/)
  assert.match(challengeModal, /ChallengeType\.StaticAttachment/)
  assert.match(challengeModal, /resolveChallengeDeliveryGuide/)
  assert.match(challengeModalShell, /useComputedColorScheme\('dark'\)/)
  assert.match(challengeModalShell, /reviewOutlineShade = colorScheme === 'dark' \? 4 : 8/)
  assert.match(challengeModal, /useFeatureGuide\(deliveryFeature/)
  assert.match(eventPage, /useFeatureGuide\([\s\S]*'event-vpn'/)
})

test('delivery tutorials follow the real static, direct, VPN, and WSRX controls', () => {
  for (const feature of ['static-challenge', 'container-direct', 'container-wsrx', 'container-vpn']) {
    assert.match(provider, new RegExp(`feature === '${feature}'`), feature)
  }
  assert.match(provider, /featureStepIndex/)
  assert.match(provider, /onFeatureTargetActivate/)
  assert.match(provider, /challenge-material/)
  assert.match(provider, /challenge-attachment/)
  assert.match(provider, /challenge-attachment-download/)
  assert.match(provider, /wsrx-setup/)
  assert.match(provider, /wsrx-download/)
  assert.match(provider, /instance-copy/)
  assert.match(provider, /127\.0\.0\.1/)
  assert.match(provider, /WSS URL is not a netcat address/)
  assert.match(instanceEntry, /data-guide="wsrx-setup"/)
  assert.match(instanceEntry, /data-guide="instance-copy"/)
  assert.match(instanceEntry, /descriptionProps=\{isPlatformProxy \? \{ component: 'div' \} : undefined\}/)
  assert.match(challengeModalShell, /withCloseButton = true/)
  assert.match(challengeModalShell, /withOverlay && <Modal\.Overlay/)
})

test('permanent guide uses real, described screenshots and remains directly navigable', () => {
  assert.match(navigation, /common\.tab\.guide[\s\S]*\/guide/)
  assert.match(page, /<PageHeader/)
  assert.match(page, /<section[\s\S]*id=\{id\}/)
  assert.match(page, /<img src=\{image\} alt=\{imageAlt \?\? ''\}/)
  assert.match(page, /<ol className=\{classes\.instructionGrid\}/)
  assert.match(page, /<figcaption className=\{classes\.instructionCaption\}/)
  assert.match(page, /<img src=\{step\.image\} alt=\{step\.imageAlt\}/)
  assert.match(page, /mdiCursorDefaultClickOutline/)
  assert.match(page, /className=\{classes\.instructionCursor\}/)
  assert.match(page, /Static challenge/)
  assert.match(page, /Direct host and port/)
  assert.match(page, /Platform Proxy with Local WSRX/)
  assert.match(page, /Event VPN host and port/)
  assert.match(page, /WebSocketReflectorX\/releases/)
  assert.doesNotMatch(page, /<Badge[^>]*circle/)
  assert.match(pageStyles, /prefers-reduced-motion/)
  for (const name of [
    'login.webp',
    'games.webp',
    'challenge.webp',
    'join-event.webp',
    'join-confirm.webp',
    'join-team.webp',
    'join-status.webp',
  ]) {
    assert.ok(existsSync(`public/static/guide/${name}`), name)
  }
})

test('the event tutorial resumes with destination-specific instructions after a game-card navigation', () => {
  assert.match(guideState, /isGameDetailPage[\s\S]*event-join-confirm[\s\S]*event-challenges/)
  assert.match(guideState, /event-card[\s\S]*games-search/)
  assert.match(provider, /Review the schedule and rules/)
  assert.match(eventPage, /data-guide="event-briefing"/)
  assert.match(eventPage, /data-guide="event-join"/)
  assert.match(eventPage, /data-guide="event-challenges"/)
  assert.match(eventPage, /event-join-confirm/)
  assert.match(eventPage, /previousJoinScope[\s\S]*setJoinModalOpen\(false\)/)
  assert.match(eventPage, /key=\{joinScope\}/)
  assert.match(gameJoinModal, /event-join-team/)
  assert.match(gameJoinModal, /event-join-submit/)
  assert.match(gameJoinModal, /validationAbort\.current\?\.abort\(\)/)
  assert.match(gameJoinModal, /submissionInFlight\.current/)
})

test('the novice path teaches every action on the real player controls', () => {
  assert.match(provider, /id: 'team'/)
  assert.match(provider, /Create or join a team/)
  assert.match(guideState, /team-create-workflow[\s\S]*team-create-name[\s\S]*team-join-workflow[\s\S]*team-join-code/)
  assert.match(guideState, /team-create-submit[\s\S]*:not\(:disabled\)/)
  assert.match(guideState, /team-join-submit[\s\S]*:not\(:disabled\)/)
  assert.match(guideState, /challenge-card/)
  assert.match(guideState, /instance-start[\s\S]*instance-entry/)
  assert.match(guideState, /flag-submit/)
  assert.match(appNavbar, /team-navigation/)
  assert.match(appHeader, /team-navigation/)
  assert.match(appNavbar, /account-profile/)
  assert.match(appNavbar, /account-login/)
  assert.match(appHeader, /account-profile/)
  assert.match(appHeader, /account-login/)
  assert.match(profilePage, /data-guide="account-access"/)
  assert.match(accountView, /data-guide-interaction-scope/)
  assert.match(loginPage, /data-guide="account-access"/)
  assert.match(oauthButtons, /data-guide="account-oauth"/)
  assert.match(provider, /GUIDE_ACCOUNT_HANDOFF_KEY/)
  assert.match(provider, /resumeGuideAfterAccountHandoff/)
  assert.match(teamsPage, /data-guide="team-create"/)
  assert.match(teamsPage, /data-guide="team-join"/)
  assert.match(teamsPage, /<TeamJoinModal/)
  assert.match(
    teamJoinModal,
    /component="form"[\s\S]*data-guide="team-join-workflow"[\s\S]*data-guide-stage=[\s\S]*data-guide-interaction-scope/
  )
  assert.match(teamJoinModal, /data-guide="team-join-code"/)
  assert.match(teamJoinModal, /data-guide="team-join-submit"/)
  assert.match(teamJoinModal, /const validCode = isValidTeamInviteCode\(code\)/)
  assert.match(teamJoinModal, /data-guide-stage=\{validCode \? 'submit' : 'input'\}/)
  assert.match(teamJoinModal, /disabled=\{joining \|\| !validCode\}/)
  assert.match(
    teamJoinModal,
    /onAccepted:[\s\S]*onTeamReady\?\.\(\)[\s\S]*mutate\(\)[\s\S]*onCodeChange\(''\)[\s\S]*modalProps\.onClose\(\)/
  )
  assert.match(teamJoinModal, /onRejected: \(error\) => \{[\s\S]*setJoinError\([\s\S]*showErrorMsg\(error, t\)/)
  assert.match(teamJoinModal, /attemptInFlight\.current/)
  assert.match(teamJoinModal, /role="alert"/)
  assert.doesNotMatch(teamJoinModal, /finally[\s\S]*onCodeChange\(''\)/)
  assert.match(teamsPage, /mutate=\{mutateTeams\}/)
  assert.match(teamsPage, /activeAccountId[\s\S]*setJoinTeamCode\(''\)[\s\S]*setJoinOpened\(false\)/)
  assert.match(teamJoinModal, /<AccessibleModal/)
  assert.match(
    teamCreateModal,
    /component="form"[\s\S]*data-guide="team-create-workflow"[\s\S]*data-guide-stage=[\s\S]*data-guide-interaction-scope/
  )
  assert.match(teamCreateModal, /data-guide="team-create-name"/)
  assert.match(teamCreateModal, /data-guide="team-create-submit"/)
  assert.match(teamCreateModal, /onTeamReady\?\.\(\)[\s\S]*mutate\(\)/)
  assert.match(teamsPage, /onTeamReady=\{completeTeamSetup\}/)
  assert.match(teamCreateModal, /<AccessibleModal/)
  assert.match(gameJoinModal, /<AccessibleModal/)
  assert.match(accessibleModal, /<Modal\.Header role="presentation">/)
  assert.match(accessibleModal, /<Modal\.Title>/)
  assert.match(accessibleModal, /aria-label=\{closeButtonProps\?\.\['aria-label'\]/)
  assert.match(challengeCard, /data-guide="challenge-card"/)
  assert.match(provider, /requiresTargetActivation/)
  assert.match(provider, /The cursor moves to the button when it is ready/)
  assert.match(provider, /When the cursor moves to Create or Join, select it/)
  assert.match(provider, /Good—now type your team name/)
  assert.match(provider, /Good—now paste the invite code/)
  assert.match(provider, /teamGuideNeedsKeyboard/)
  assert.match(provider, /teamGuideKeyboardActive/)
  assert.match(provider, /retainTeamGuideActivation\(activeTourTarget, current, tourOpen\)/)
  assert.match(provider, /mdiKeyboardOutline/)
  assert.match(provider, /showTargetCursor={!teamGuideKeyboardActive}/)
  assert.match(provider, /Select the highlighted control to continue/)
})
