use std::str::FromStr;
use std::time::Duration;

use chrono::{DateTime, Utc};
use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
use uuid::Uuid;

use super::{persist_access_audit, AccessAudit};

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn concurrent_accesses_timestamp_in_participation_lock_order() {
    let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
        .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
    let admin = PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
        .expect("connect test database");
    let schema = format!("access_ordering_{}", Uuid::new_v4().simple());
    sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
        .execute(&admin)
        .await
        .expect("create test schema");
    let options = PgConnectOptions::from_str(&database_url)
        .expect("parse test database URL")
        .options([("search_path", schema.as_str())]);
    let pool = PgPoolOptions::new()
        .max_connections(4)
        .connect_with(options)
        .await
        .expect("connect isolated pool");

    sqlx::raw_sql(
        r#"
        CREATE TABLE "Games" (
          id INTEGER PRIMARY KEY,
          start_time_utc TIMESTAMPTZ NOT NULL,
          end_time_utc TIMESTAMPTZ NOT NULL,
          deletion_pending BOOLEAN NOT NULL DEFAULT FALSE
        );
        CREATE TABLE "Teams" (
          id INTEGER PRIMARY KEY,
          deletion_pending BOOLEAN NOT NULL DEFAULT FALSE
        );
        CREATE TABLE "Participations" (
          id INTEGER PRIMARY KEY,
          game_id INTEGER NOT NULL,
          team_id INTEGER NOT NULL,
          status SMALLINT NOT NULL
        );
        CREATE TABLE "GameChallenges" (
          id INTEGER PRIMARY KEY,
          game_id INTEGER NOT NULL,
          is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
          deletion_pending BOOLEAN NOT NULL DEFAULT FALSE
        );
        CREATE TABLE "SuspicionReconciliationState" (
          game_id INTEGER PRIMARY KEY,
          evidence_closed_at_utc TIMESTAMPTZ
        );
        CREATE TABLE "ContainerAccessEvents" (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          game_id INTEGER NOT NULL,
          challenge_id INTEGER NOT NULL,
          container_owner_participation_id INTEGER NOT NULL,
          container_id UUID NOT NULL,
          accessing_user_id UUID,
          accessing_user_name TEXT,
          accessing_participation_id INTEGER,
          remote_ip TEXT NOT NULL,
          remote_ip_hash BYTEA,
          user_agent TEXT,
          is_monitor BOOLEAN NOT NULL,
          connected_at_utc TIMESTAMPTZ NOT NULL
        );
        CREATE TABLE "SuspicionEvaluationOutbox" (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_kind SMALLINT NOT NULL,
          source_kind SMALLINT NOT NULL,
          source_id INTEGER NOT NULL,
          game_id INTEGER NOT NULL,
          participation_id INTEGER NOT NULL,
          challenge_id INTEGER,
          rule_kind SMALLINT,
          evidence_key TEXT NOT NULL,
          observed_at_utc TIMESTAMPTZ NOT NULL,
          evidence_payload JSONB NOT NULL,
          evidence_version SMALLINT NOT NULL
        );
        "#,
    )
    .execute(&pool)
    .await
    .expect("create ordering fixture");
    let now = Utc::now();
    sqlx::query(
        r#"INSERT INTO "Games" (id, start_time_utc, end_time_utc)
           VALUES (1, $1, $2)"#,
    )
    .bind(now - chrono::Duration::hours(1))
    .bind(now + chrono::Duration::hours(1))
    .execute(&pool)
    .await
    .expect("insert live game");
    sqlx::raw_sql(
        r#"
        INSERT INTO "Teams" (id) VALUES (2), (3);
        INSERT INTO "Participations" (id, game_id, team_id, status)
          VALUES (10, 1, 2, 1), (11, 1, 3, 1);
        INSERT INTO "GameChallenges" (id, game_id) VALUES (20, 1);
        "#,
    )
    .execute(&pool)
    .await
    .expect("insert evidence identities");

    let user_id = Uuid::new_v4();
    let hash = [7_u8; 32];
    let first_container = Uuid::new_v4();
    let second_container = Uuid::new_v4();
    let make_audit = |container_id| AccessAudit {
        game_id: 1,
        challenge_id: 20,
        owner_participation_id: 10,
        accessing_participation_id: 11,
        container_id,
        accessing_user_id: user_id,
        accessing_user_name: "accessor",
        remote_ip: "192.0.2.1",
        remote_ip_hash: Some(&hash),
        user_agent: None,
        is_monitor: false,
    };

    let mut blocker = pool.begin().await.expect("begin suspicion lock blocker");
    crate::services::suspicion::lock_participation_suspicion_writes(&mut blocker, 11)
        .await
        .expect("hold participation suspicion lock");
    let first_writer = persist_access_audit(&pool, make_audit(first_container));
    tokio::pin!(first_writer);
    assert!(
        tokio::time::timeout(Duration::from_millis(100), first_writer.as_mut())
            .await
            .is_err()
    );
    let second_writer = persist_access_audit(&pool, make_audit(second_container));
    tokio::pin!(second_writer);
    assert!(
        tokio::time::timeout(Duration::from_millis(100), second_writer.as_mut())
            .await
            .is_err()
    );
    let released_at: DateTime<Utc> = sqlx::query_scalar("SELECT clock_timestamp()")
        .fetch_one(&mut *blocker)
        .await
        .expect("capture lock release time");
    blocker.commit().await.expect("release suspicion lock");
    tokio::time::timeout(Duration::from_secs(5), first_writer.as_mut())
        .await
        .expect("first writer did not resume")
        .expect("persist first access");
    tokio::time::timeout(Duration::from_secs(5), second_writer.as_mut())
        .await
        .expect("second writer did not resume")
        .expect("persist second access");

    let ordered: Vec<(Uuid, DateTime<Utc>, i32, i32, DateTime<Utc>)> = sqlx::query_as(
        r#"SELECT event.container_id, event.connected_at_utc, event.id,
                  job.source_id, job.observed_at_utc
             FROM "ContainerAccessEvents" event
             JOIN "SuspicionEvaluationOutbox" job ON job.source_id = event.id
            ORDER BY event.connected_at_utc, event.id"#,
    )
    .fetch_all(&pool)
    .await
    .expect("load ordered access evidence");
    assert_eq!(ordered.len(), 2);
    assert_eq!(ordered[0].0, first_container);
    assert_eq!(ordered[1].0, second_container);
    assert!(ordered[0].1 >= released_at);
    assert!(ordered[1].1 >= ordered[0].1);
    assert_eq!(ordered[0].2, ordered[0].3);
    assert_eq!(ordered[1].2, ordered[1].3);
    assert_eq!(ordered[0].1, ordered[0].4);
    assert_eq!(ordered[1].1, ordered[1].4);

    pool.close().await;
    sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
        .execute(&admin)
        .await
        .expect("drop test schema");
}
