use super::*;

use std::str::FromStr;

use sqlx::postgres::{PgConnectOptions, PgPoolOptions};

#[tokio::test]
#[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
async fn accepted_team_can_enroll_after_scoring_starts() {
    let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
        .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
    let admin = PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
        .unwrap();
    let schema = format!("rsctf_late_team_{}", Uuid::new_v4().simple());
    sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
        .execute(&admin)
        .await
        .unwrap();
    let options = PgConnectOptions::from_str(&database_url)
        .unwrap()
        .options([("search_path", schema.as_str())]);
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect_with(options)
        .await
        .unwrap();
    sqlx::raw_sql(
        r#"
        CREATE TABLE "Participations" (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          status SMALLINT NOT NULL, token TEXT NOT NULL, writeup_id INTEGER,
          game_id INTEGER NOT NULL, team_id INTEGER NOT NULL, division_id INTEGER,
          suspicion_score INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE "UserParticipations" (
          user_id UUID NOT NULL, game_id INTEGER NOT NULL, team_id INTEGER NOT NULL,
          participation_id INTEGER NOT NULL, PRIMARY KEY (user_id, game_id)
        );
        CREATE TABLE "KothOfficialConfigs" (
          game_id INTEGER PRIMARY KEY, roster_snapshot JSONB NOT NULL
        );
        CREATE TABLE "KothEpochRollups" (
          game_id INTEGER NOT NULL, epoch INTEGER NOT NULL,
          epoch_weight FLOAT8 NOT NULL, PRIMARY KEY (game_id, epoch)
        );
        CREATE TABLE "KothEpochTeamRollups" (
          game_id INTEGER, epoch INTEGER, participation_id INTEGER, points FLOAT8,
          epoch_weight FLOAT8, acquisition_rate FLOAT8, control_rate FLOAT8,
          sla_rate FLOAT8, acquisition_windows BIGINT, controlled_ticks BIGINT,
          responsible_ticks BIGINT, healthy_responsible_ticks BIGINT,
          cumulative_points_numerator FLOAT8, cumulative_epoch_weight FLOAT8,
          cumulative_acquisition_numerator FLOAT8, cumulative_control_numerator FLOAT8,
          cumulative_sla_numerator FLOAT8, cumulative_rate_weight FLOAT8,
          cumulative_acquisition_windows BIGINT, cumulative_controlled_ticks BIGINT,
          cumulative_responsible_ticks BIGINT, cumulative_healthy_responsible_ticks BIGINT,
          PRIMARY KEY (game_id, epoch, participation_id)
        );
        CREATE TABLE "KothEpochHillRollups" (
          game_id INTEGER, epoch INTEGER, participation_id INTEGER, challenge_id INTEGER,
          service_weight FLOAT8, evidence_fraction FLOAT8, epoch_fraction FLOAT8,
          local_points FLOAT8, acquisition_rate FLOAT8, control_rate FLOAT8,
          sla_rate FLOAT8, acquisition_windows BIGINT, controlled_ticks BIGINT,
          responsible_ticks BIGINT, healthy_responsible_ticks BIGINT,
          cumulative_points_numerator FLOAT8, cumulative_score_weight FLOAT8,
          cumulative_acquisition_numerator FLOAT8, cumulative_control_numerator FLOAT8,
          cumulative_sla_numerator FLOAT8, cumulative_rate_weight FLOAT8,
          cumulative_acquisition_windows BIGINT, cumulative_controlled_ticks BIGINT,
          cumulative_responsible_ticks BIGINT, cumulative_healthy_responsible_ticks BIGINT,
          PRIMARY KEY (game_id, epoch, participation_id, challenge_id)
        );
        "#,
    )
    .execute(&pool)
    .await
    .unwrap();

    let user_id = Uuid::new_v4();
    let mut locks = MembershipMutationLocks::acquire(&pool, user_id, 7, 9, true)
        .await
        .unwrap();
    locks.acquire_game_advisory().await.unwrap();
    let joined = persist_game_join_locked(
        locks.transaction_mut(),
        JoinMutation {
            user_id,
            game_id: 7,
            team_id: 9,
            division_id: None,
            target_status: ParticipationStatus::Accepted,
            token: "late",
            member_limit: 4,
            scoring_started: true,
        },
    )
    .await
    .expect("late accepted team was rejected");
    assert!(joined.is_accepted());
    assert!(joined.created_participation());
    locks.release().await.unwrap();
    assert_eq!(
        sqlx::query_scalar::<_, i64>(
            r#"SELECT COUNT(*) FROM "UserParticipations"
                WHERE user_id = $1 AND game_id = 7 AND participation_id = $2"#,
        )
        .bind(user_id)
        .bind(joined.participation_id)
        .fetch_one(&pool)
        .await
        .unwrap(),
        1
    );

    pool.close().await;
    sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
        .execute(&admin)
        .await
        .unwrap();
}
