//! Make flag-egress aggregation atomic and preserve the remote endpoint as part
//! of each forensic event's identity.

use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::ConnectionTrait;

const UP_SQL: &str = r#"
    LOCK TABLE "FlagEgressEvents" IN SHARE ROW EXCLUSIVE MODE;

    WITH merged AS (
        SELECT MIN(id) AS keep_id,
               GREATEST(
                   1::BIGINT,
                   LEAST(
                       SUM(GREATEST(hit_count, 0)::BIGINT),
                       2147483647::BIGINT
                   )
               )::INTEGER AS hit_count,
               MIN(first_seen_utc) AS first_seen_utc,
               MAX(last_seen_utc) AS last_seen_utc
          FROM "FlagEgressEvents"
         GROUP BY game_id,
                  participation_id,
                  challenge_id,
                  container_id,
                  remote_ip,
                  remote_port
    )
    UPDATE "FlagEgressEvents" event
       SET hit_count = merged.hit_count,
           first_seen_utc = merged.first_seen_utc,
           last_seen_utc = merged.last_seen_utc
      FROM merged
     WHERE event.id = merged.keep_id;

    WITH ranked AS (
        SELECT id,
               row_number() OVER (
                   PARTITION BY game_id,
                                participation_id,
                                challenge_id,
                                container_id,
                                remote_ip,
                                remote_port
                       ORDER BY id
               ) AS occurrence
          FROM "FlagEgressEvents"
    )
    DELETE FROM "FlagEgressEvents" event
     USING ranked
     WHERE event.id = ranked.id
       AND ranked.occurrence > 1;

    CREATE UNIQUE INDEX IF NOT EXISTS ux_flagegress_event_endpoint
        ON "FlagEgressEvents"(
            game_id,
            participation_id,
            challenge_id,
            COALESCE(container_id::TEXT, ''::TEXT),
            remote_ip,
            remote_port
        );
"#;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(UP_SQL).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(r#"DROP INDEX IF EXISTS ux_flagegress_event_endpoint;"#)
            .await?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::UP_SQL;
    use sqlx::postgres::PgPoolOptions;

    #[test]
    fn deduplicates_before_adding_the_remote_endpoint_identity() {
        let aggregate = UP_SQL.find("WITH merged AS").unwrap();
        let delete = UP_SQL.find("DELETE FROM \"FlagEgressEvents\"").unwrap();
        let index = UP_SQL.find("CREATE UNIQUE INDEX").unwrap();

        assert!(aggregate < delete && delete < index);
        assert!(UP_SQL.contains("SUM(GREATEST(hit_count, 0)::BIGINT)"));
        assert!(UP_SQL.contains(
            "GROUP BY game_id,\n                  participation_id,\n                  challenge_id,\n                  container_id,\n                  remote_ip,\n                  remote_port"
        ));
        assert!(UP_SQL.contains(
            "PARTITION BY game_id,\n                                participation_id,\n                                challenge_id,\n                                container_id,\n                                remote_ip,\n                                remote_port"
        ));
        assert!(UP_SQL.contains("COALESCE(container_id::TEXT, ''::TEXT)"));
        assert!(!UP_SQL.contains("NULLS NOT DISTINCT"));
    }

    #[tokio::test]
    #[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
    async fn merges_legacy_duplicates_and_keeps_remote_ips_distinct() {
        let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
            .expect("RSCTF_TEST_DATABASE_URL must point to PostgreSQL");
        let admin = PgPoolOptions::new()
            .max_connections(1)
            .connect(&database_url)
            .await
            .expect("connect test database");
        let schema = format!("flag_egress_identity_{}", uuid::Uuid::new_v4().simple());
        let setup = format!(
            r#"
            CREATE SCHEMA "{schema}";
            CREATE TABLE "{schema}"."FlagEgressEvents" (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                game_id INTEGER NOT NULL,
                participation_id INTEGER NOT NULL,
                challenge_id INTEGER NOT NULL,
                container_id UUID,
                remote_ip TEXT NOT NULL,
                remote_port INTEGER NOT NULL,
                hit_count INTEGER NOT NULL,
                first_seen_utc TIMESTAMPTZ NOT NULL,
                last_seen_utc TIMESTAMPTZ NOT NULL
            );
            INSERT INTO "{schema}"."FlagEgressEvents"
                (game_id, participation_id, challenge_id, container_id,
                 remote_ip, remote_port, hit_count, first_seen_utc, last_seen_utc)
            VALUES
                (1, 2, 3, NULL, '192.0.2.1', 0, 2,
                 '2026-01-02T00:00:00Z', '2026-01-03T00:00:00Z'),
                (1, 2, 3, NULL, '192.0.2.1', 0, 3,
                 '2026-01-01T00:00:00Z', '2026-01-04T00:00:00Z'),
                (1, 2, 3, NULL, '192.0.2.2', 0, 7,
                 '2026-01-01T00:00:00Z', '2026-01-05T00:00:00Z'),
                (1, 2, 3, '00000000-0000-0000-0000-000000000000',
                 '192.0.2.1', 0, 11,
                 '2026-01-01T00:00:00Z', '2026-01-06T00:00:00Z');
            "#
        );
        sqlx::raw_sql(&setup).execute(&admin).await.unwrap();

        let search_path_schema = schema.clone();
        let pool = PgPoolOptions::new()
            .max_connections(2)
            .after_connect(move |connection, _metadata| {
                let statement = format!(r#"SET search_path TO "{search_path_schema}""#);
                Box::pin(async move {
                    sqlx::query(&statement).execute(connection).await?;
                    Ok(())
                })
            })
            .connect(&database_url)
            .await
            .unwrap();

        sqlx::raw_sql(UP_SQL).execute(&pool).await.unwrap();
        sqlx::raw_sql(UP_SQL).execute(&pool).await.unwrap();

        let rows = sqlx::query_as::<_, (Option<uuid::Uuid>, String, i32)>(
            r#"SELECT container_id, remote_ip, hit_count
                 FROM "FlagEgressEvents"
                ORDER BY container_id NULLS FIRST, remote_ip"#,
        )
        .fetch_all(&pool)
        .await
        .unwrap();
        assert_eq!(
            rows,
            vec![
                (None, "192.0.2.1".to_owned(), 5),
                (None, "192.0.2.2".to_owned(), 7),
                (Some(uuid::Uuid::nil()), "192.0.2.1".to_owned(), 11,),
            ]
        );

        let duplicate = sqlx::query(
            r#"INSERT INTO "FlagEgressEvents"
                (game_id, participation_id, challenge_id, container_id,
                 remote_ip, remote_port, hit_count, first_seen_utc, last_seen_utc)
               VALUES (1, 2, 3, NULL, '192.0.2.1', 0, 1, now(), now())"#,
        )
        .execute(&pool)
        .await
        .unwrap_err();
        assert!(matches!(
            duplicate,
            sqlx::Error::Database(database) if database.code().as_deref() == Some("23505")
        ));

        pool.close().await;
        let cleanup = format!(r#"DROP SCHEMA "{schema}" CASCADE"#);
        sqlx::query(&cleanup).execute(&admin).await.unwrap();
    }
}
