//! Persist one immutable final filesystem snapshot for each hosted A&D service.

use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::ConnectionTrait;

const UP_SQL: &str = r#"
CREATE TABLE IF NOT EXISTS "AdServiceSnapshots" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_service_id INTEGER NOT NULL,
    local_file_id INTEGER NOT NULL,
    source_container_id VARCHAR NOT NULL,
    captured_at_utc TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    expires_at_utc TIMESTAMPTZ NULL,
    CONSTRAINT fk_ad_service_snapshots_service
        FOREIGN KEY (team_service_id)
        REFERENCES "AdTeamServices"(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ad_service_snapshots_file
        FOREIGN KEY (local_file_id)
        REFERENCES "Files"(id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_ad_service_snapshots_source
        CHECK (BTRIM(source_container_id) <> ''),
    CONSTRAINT ck_ad_service_snapshots_expiry
        CHECK (expires_at_utc IS NULL OR expires_at_utc > captured_at_utc)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ad_service_snapshots_service
    ON "AdServiceSnapshots"(team_service_id);

CREATE INDEX IF NOT EXISTS ix_ad_service_snapshots_expiry
    ON "AdServiceSnapshots"(expires_at_utc, id)
 WHERE expires_at_utc IS NOT NULL;

CREATE OR REPLACE FUNCTION rsctf_release_ad_service_snapshot_file()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $snapshot_release$
BEGIN
    UPDATE "Files"
       SET reference_count = GREATEST(reference_count - 1, 0)
     WHERE id = OLD.local_file_id;
    RETURN OLD;
END
$snapshot_release$;

DROP TRIGGER IF EXISTS trg_ad_service_snapshot_release
    ON "AdServiceSnapshots";
CREATE TRIGGER trg_ad_service_snapshot_release
AFTER DELETE ON "AdServiceSnapshots"
FOR EACH ROW
EXECUTE FUNCTION rsctf_release_ad_service_snapshot_file();
"#;

const DOWN_SQL: &str = r#"
DELETE FROM "AdServiceSnapshots";
DROP TABLE IF EXISTS "AdServiceSnapshots";
DROP FUNCTION IF EXISTS rsctf_release_ad_service_snapshot_file();
"#;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(UP_SQL).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(DOWN_SQL)
            .await?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::UP_SQL;

    #[test]
    fn snapshot_owner_is_unique_bounded_and_indexed_for_expiry() {
        assert!(UP_SQL.contains("REFERENCES \"AdTeamServices\"(id)"));
        assert!(UP_SQL.contains("REFERENCES \"Files\"(id)"));
        assert!(UP_SQL.contains("ux_ad_service_snapshots_service"));
        assert!(UP_SQL.contains("ix_ad_service_snapshots_expiry"));
        assert!(UP_SQL.contains("expires_at_utc IS NULL OR expires_at_utc > captured_at_utc"));
        assert!(UP_SQL.contains("trg_ad_service_snapshot_release"));
        assert!(UP_SQL.contains("GREATEST(reference_count - 1, 0)"));
    }
}
