//! Repair orphaned build states and enforce the live-build timestamp invariant.

use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::ConnectionTrait;

const CONSTRAINT_NAME: &str = "ck_build_records_pending_unfinished";
const INDEX_NAME: &str = "ix_build_records_in_progress";
#[cfg(test)]
const REPAIR_MESSAGE: &str =
    "Build marked failed during upgrade: no background worker owns this queued/building attempt. Retry manually.";

const UP_SQL: &str = r#"
LOCK TABLE "BuildRecords" IN SHARE ROW EXCLUSIVE MODE;
LOCK TABLE "GameChallenges" IN SHARE ROW EXCLUSIVE MODE;

UPDATE "GameChallenges"
   SET build_status = 2,
       last_build_log = right(
           concat_ws(
               E'\n',
               nullif(last_build_log, ''),
               'Build marked failed during upgrade: no background worker owns this queued/building attempt. Retry manually.'
           ),
           16384
       )
 WHERE build_status IN (3, 5);

UPDATE "BuildRecords"
   SET status = 2,
       finished_at_utc = COALESCE(finished_at_utc, clock_timestamp()),
       log_tail = right(
           concat_ws(
               E'\n',
               nullif(log_tail, ''),
               'Build marked failed during upgrade: no background worker owns this queued/building attempt. Retry manually.'
           ),
           4096
       )
 WHERE status IN (3, 5);

DO $migration$
BEGIN
  IF NOT EXISTS (
      SELECT 1
        FROM pg_constraint
       WHERE conname = 'ck_build_records_pending_unfinished'
         AND conrelid = '"BuildRecords"'::regclass
  ) THEN
    ALTER TABLE "BuildRecords"
      ADD CONSTRAINT ck_build_records_pending_unfinished
      CHECK (status NOT IN (3, 5) OR finished_at_utc IS NULL);
  END IF;
END
$migration$;

CREATE INDEX IF NOT EXISTS ix_build_records_in_progress
    ON "BuildRecords" (enqueued_at_utc DESC, id DESC)
 WHERE status IN (3, 5)
   AND finished_at_utc IS NULL;
"#;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(UP_SQL).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(&format!(
                r#"
                DROP INDEX IF EXISTS {INDEX_NAME};
                ALTER TABLE "BuildRecords"
                    DROP CONSTRAINT IF EXISTS {CONSTRAINT_NAME};
                "#
            ))
            .await?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
    use uuid::Uuid;

    use super::{CONSTRAINT_NAME, INDEX_NAME, REPAIR_MESSAGE, UP_SQL};

    #[test]
    fn repair_precedes_the_constraint_and_partial_index() {
        let challenge_repair = UP_SQL.find("UPDATE \"GameChallenges\"").unwrap();
        let record_repair = UP_SQL.find("UPDATE \"BuildRecords\"").unwrap();
        let constraint = UP_SQL.find("ADD CONSTRAINT").unwrap();
        let index = UP_SQL.find("CREATE INDEX").unwrap();
        assert!(challenge_repair < record_repair);
        assert!(record_repair < constraint);
        assert!(constraint < index);
        assert!(UP_SQL.contains(CONSTRAINT_NAME));
        assert!(UP_SQL.contains(INDEX_NAME));
        assert!(UP_SQL.contains(REPAIR_MESSAGE));
        assert!(UP_SQL.contains("finished_at_utc IS NULL"));
    }

    #[tokio::test]
    #[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
    async fn migration_repairs_orphans_and_is_idempotent() {
        let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
            .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
        let admin = PgPoolOptions::new()
            .max_connections(1)
            .connect(&database_url)
            .await
            .unwrap();
        let schema = format!("build_lifecycle_{}", Uuid::new_v4().simple());
        sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
            .execute(&admin)
            .await
            .unwrap();
        let options = PgConnectOptions::from_str(&database_url)
            .unwrap()
            .options([("search_path", schema.as_str())]);
        let pool = PgPoolOptions::new()
            .max_connections(2)
            .connect_with(options)
            .await
            .unwrap();

        sqlx::raw_sql(
            r#"
            CREATE TABLE "GameChallenges" (
                id INTEGER PRIMARY KEY,
                build_status SMALLINT NOT NULL,
                last_build_log TEXT
            );
            CREATE TABLE "BuildRecords" (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                challenge_id INTEGER NOT NULL,
                game_id INTEGER NOT NULL,
                challenge_title TEXT NOT NULL,
                enqueued_at_utc TIMESTAMPTZ NOT NULL,
                started_at_utc TIMESTAMPTZ,
                finished_at_utc TIMESTAMPTZ,
                trigger TEXT NOT NULL,
                kind TEXT NOT NULL,
                attempt INTEGER NOT NULL,
                status SMALLINT NOT NULL,
                digest TEXT,
                image_ref TEXT,
                log_tail TEXT
            );
            INSERT INTO "GameChallenges" (id, build_status, last_build_log) VALUES
                (1, 5, 'queued challenge'),
                (2, 3, NULL),
                (3, 1, 'successful challenge'),
                (4, 2, 'failed challenge');
            INSERT INTO "BuildRecords"
                (id, challenge_id, game_id, challenge_title, enqueued_at_utc,
                 started_at_utc, finished_at_utc, trigger, kind, attempt, status, log_tail)
            VALUES
                (1, 1, 1, 'queued-finished', '2026-01-01T00:00:00Z',
                 '2026-01-01T00:00:01Z', '2026-01-01T00:00:02Z',
                 'Backfill', 'Challenge', 1, 5, 'legacy'),
                (2, 2, 1, 'building', '2026-01-01T00:01:00Z',
                 '2026-01-01T00:01:01Z', NULL,
                 'Manual', 'Challenge', 1, 3, NULL),
                (3, 3, 1, 'old-queued', '2026-01-01T00:02:00Z',
                 NULL, NULL, 'Manual', 'Challenge', 1, 5, NULL),
                (4, 3, 1, 'new-success', '2026-01-01T00:03:00Z',
                 '2026-01-01T00:03:01Z', '2026-01-01T00:03:02Z',
                 'Manual', 'Challenge', 2, 1, 'ok'),
                (5, 4, 1, 'failed', '2026-01-01T00:04:00Z',
                 '2026-01-01T00:04:01Z', '2026-01-01T00:04:02Z',
                 'Manual', 'Challenge', 1, 2, 'failed');
            "#,
        )
        .execute(&pool)
        .await
        .unwrap();

        for _ in 0..2 {
            let mut transaction = pool.begin().await.unwrap();
            sqlx::raw_sql(UP_SQL)
                .execute(&mut *transaction)
                .await
                .unwrap();
            transaction.commit().await.unwrap();
        }

        assert_eq!(
            sqlx::query_as::<_, (i32, i16)>(
                r#"SELECT id, build_status FROM "GameChallenges" ORDER BY id"#,
            )
            .fetch_all(&pool)
            .await
            .unwrap(),
            vec![(1, 2), (2, 2), (3, 1), (4, 2)]
        );
        let records = sqlx::query_as::<_, (i32, i16, bool)>(
            r#"SELECT id, status, finished_at_utc IS NOT NULL
                 FROM "BuildRecords"
                ORDER BY id"#,
        )
        .fetch_all(&pool)
        .await
        .unwrap();
        assert_eq!(
            records,
            vec![
                (1, 2, true),
                (2, 2, true),
                (3, 2, true),
                (4, 1, true),
                (5, 2, true),
            ]
        );
        assert_eq!(
            sqlx::query_scalar::<_, i64>(
                r#"SELECT COUNT(*) FROM "BuildRecords" WHERE log_tail LIKE '%' || $1"#,
            )
            .bind(REPAIR_MESSAGE)
            .fetch_one(&pool)
            .await
            .unwrap(),
            3
        );

        let invalid_pending = sqlx::query(
            r#"INSERT INTO "BuildRecords"
                (challenge_id, game_id, challenge_title, enqueued_at_utc,
                 finished_at_utc, trigger, kind, attempt, status)
               VALUES (9, 1, 'invalid', now(), now(), 'Manual', 'Challenge', 1, 5)"#,
        )
        .execute(&pool)
        .await
        .unwrap_err();
        assert!(matches!(
            invalid_pending,
            sqlx::Error::Database(ref error)
                if error.code().as_deref() == Some("23514")
        ));
        assert_eq!(
            sqlx::query_scalar::<_, Option<String>>(
                "SELECT to_regclass('ix_build_records_in_progress')::TEXT",
            )
            .fetch_one(&pool)
            .await
            .unwrap(),
            Some(INDEX_NAME.to_string())
        );

        pool.close().await;
        sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
            .execute(&admin)
            .await
            .unwrap();
        admin.close().await;
    }
}
