//! Bounded aggregate storage for public HTTP and TCP honeypot telemetry.

use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::ConnectionTrait;

#[derive(DeriveMigrationName)]
pub struct Migration;

pub(crate) const UP_SQL: &str = r#"
ALTER TABLE "HoneypotHits"
    ADD COLUMN IF NOT EXISTS bucket_start_utc TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS source_hash BYTEA NULL,
    ADD COLUMN IF NOT EXISTS hit_count BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS sampled_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_hit_at_utc TIMESTAMPTZ NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_honeypot_hits_aggregate_bucket
    ON "HoneypotHits" (bucket_start_utc, bait, source_hash)
    WHERE bucket_start_utc IS NOT NULL AND source_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_honeypot_hits_global_retention
    ON "HoneypotHits" ((COALESCE(bucket_start_utc, hit_at_utc)), id)
    WHERE game_id IS NULL
      AND participation_id IS NULL;
"#;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(UP_SQL).await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        // Forward-only. Once writers aggregate into these columns, removing
        // them would silently reinterpret counts as individual raw hits.
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn aggregate_identity_and_retention_are_indexed_and_idempotent() {
        assert!(UP_SQL.contains("ADD COLUMN IF NOT EXISTS bucket_start_utc"));
        assert!(UP_SQL.contains("ADD COLUMN IF NOT EXISTS source_hash"));
        assert!(UP_SQL.contains("ADD COLUMN IF NOT EXISTS hit_count"));
        assert!(UP_SQL.contains("ADD COLUMN IF NOT EXISTS sampled_count"));
        assert!(UP_SQL.contains("ux_honeypot_hits_aggregate_bucket"));
        assert!(UP_SQL.contains("ix_honeypot_hits_global_retention"));
        assert!(UP_SQL.contains("COALESCE(bucket_start_utc, hit_at_utc)"));
        assert!(!UP_SQL.contains("participation_id IS NULL\n      AND bucket_start_utc"));
    }

    #[tokio::test]
    #[ignore = "requires PostgreSQL via RSCTF_TEST_DATABASE_URL"]
    async fn postgres_upgrade_is_idempotent_on_the_shipped_table() {
        let database_url = std::env::var("RSCTF_TEST_DATABASE_URL")
            .expect("RSCTF_TEST_DATABASE_URL must point to disposable PostgreSQL");
        let admin = sqlx::postgres::PgPoolOptions::new()
            .max_connections(1)
            .connect_with(crate::migrations::test_pg_connect_options(&database_url))
            .await
            .unwrap();
        let schema = format!("rsctf_honeypot_buckets_{}", uuid::Uuid::new_v4().simple());
        sqlx::query(&format!(r#"CREATE SCHEMA "{schema}""#))
            .execute(&admin)
            .await
            .unwrap();
        let options = crate::migrations::test_pg_connect_options(&database_url)
            .options([("search_path", schema.as_str())]);
        let pool = sqlx::postgres::PgPoolOptions::new()
            .max_connections(2)
            .connect_with(options)
            .await
            .unwrap();
        sqlx::raw_sql(
            r#"
            CREATE TABLE "HoneypotHits" (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                game_id INTEGER NULL,
                participation_id INTEGER NULL,
                user_id UUID NULL,
                bait TEXT NOT NULL,
                remote_ip TEXT NOT NULL DEFAULT '',
                user_agent TEXT NULL,
                hit_at_utc TIMESTAMPTZ NOT NULL
            );
            "#,
        )
        .execute(&pool)
        .await
        .unwrap();

        sqlx::raw_sql(UP_SQL).execute(&pool).await.unwrap();
        sqlx::raw_sql(UP_SQL).execute(&pool).await.unwrap();

        let columns: i64 = sqlx::query_scalar(
            r#"SELECT COUNT(*)::BIGINT
                 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'HoneypotHits'
                  AND column_name IN (
                      'bucket_start_utc', 'source_hash',
                      'hit_count', 'sampled_count', 'last_hit_at_utc'
                  )"#,
        )
        .fetch_one(&pool)
        .await
        .unwrap();
        assert_eq!(columns, 5);
        let indexes: i64 = sqlx::query_scalar(
            r#"SELECT COUNT(*)::BIGINT
                 FROM pg_indexes
                WHERE schemaname = current_schema()
                  AND indexname IN (
                      'ux_honeypot_hits_aggregate_bucket',
                      'ix_honeypot_hits_global_retention'
                  )"#,
        )
        .fetch_one(&pool)
        .await
        .unwrap();
        assert_eq!(indexes, 2);

        pool.close().await;
        sqlx::query(&format!(r#"DROP SCHEMA "{schema}" CASCADE"#))
            .execute(&admin)
            .await
            .unwrap();
    }
}
