// Destructive organizer-hub acceptance plus a fixed-rate k6 phase. This runs
// only against an explicitly acknowledged disposable Compose project. It owns
// three temporary users, two Docker containers, two Containers rows, and the
// exact semantic audit rows generated by those users; cleanup proves all of
// them are absent before returning.
import { randomBytes, randomUUID } from 'node:crypto';

import {
  assertDisposableOrganizerTopology,
  assertNegotiateContract,
  assertOrganizerHubAcknowledgements,
  assertPrivilegedHubRuntimeCoverage,
  assertReceivedLog,
  consumeHubFrames,
  decodeReceive,
  hubFrame,
  normalizeOrigin,
  organizerByocMode,
  organizerWebTargets,
  positiveInteger,
  privilegedHubSurfaceId,
  scopedContainerExecPath,
} from './organizer-hubs.js';
import { dockerOwnershipLabelArgs, dockerScopeFromContainerEnv } from './docker-scope.js';
import {
  DEFAULT_BYOC_AGENT_IMAGE,
  docker,
  mintJwt,
  NET,
  PG,
  RSCTF,
  byocRsctfIp,
  runK6,
  sleep,
  sql,
  TARGET,
} from './lib.mjs';
import * as A from './applib.mjs';
import {
  acquireAdminLifecycleDatabaseLock,
  deleteDisposableLoadGame,
  inspectUnchangedServerRuntimeIdentity,
  inspectUniformServerRuntimeIdentity,
  originalServerRuntimeLogTargets,
  persistRecovery,
  removeRecovery,
  shouldRetainLifecycleManifest,
} from './admin-fixtures.mjs';
import { countContainerFatalLogs } from './log-audit.mjs';
import {
  dockerLabelArgs,
  fleetLabels,
  normalizeFleetScope,
  ownsFleetResource,
} from './fleet-ownership.js';
import { acquireExclusiveProcessLock, loadOrchestrationLockPath } from './process-control.mjs';

const tag = `oh${Date.now().toString(36)}${randomBytes(2).toString('hex')}`;
const recoveryPath = `/tmp/rsctf-organizer-hubs-${tag}.json`;
const runStartedAt = Date.now();
const adminTarget = normalizeOrigin(process.env.ORGANIZER_HUB_ADMIN_TARGET || TARGET, 'admin target');
const execTarget = normalizeOrigin(
  process.env.ORGANIZER_HUB_EXEC_TARGET || process.env.CONTROL_TARGET || TARGET,
  'exec target',
);
const adminContainer = String(process.env.ORGANIZER_HUB_ADMIN_CONTAINER || RSCTF).trim();
const execContainer = String(process.env.ORGANIZER_HUB_EXEC_CONTAINER || RSCTF).trim();
const pgContainer = String(process.env.ORGANIZER_HUB_PG_CONTAINER || PG).trim();
const redisContainer = String(
  process.env.ORGANIZER_HUB_REDIS_CONTAINER ||
    process.env.REDIS_CONTAINER ||
    PG.replace(/-db-(\d+)$/, '-redis-$1'),
).trim();
const stackMarker = String(process.env.ADMIN_LIFECYCLE_STACK_MARKER || '').trim();
const webTargets = organizerWebTargets(
  process.env.ORGANIZER_HUB_WEB_TARGETS || process.env.WEB_TARGETS,
  adminTarget,
);
const webContainers = String(process.env.ORGANIZER_HUB_WEB_CONTAINERS || adminContainer)
  .split(',')
  .map((container) => container.trim())
  .filter(Boolean);
if (
  webContainers.length !== webTargets.length ||
  new Set(webContainers).size !== webContainers.length ||
  webContainers[webTargets.indexOf(adminTarget)] !== adminContainer
) {
  throw new Error(
    'ORGANIZER_HUB_WEB_CONTAINERS must map one-to-one with ORGANIZER_HUB_WEB_TARGETS and bind the admin target',
  );
}
const fixtureImage = String(process.env.ORGANIZER_HUB_CONTAINER_IMAGE || 'alpine:3.20').trim();
const adNetwork = String(process.env.AD_NET || 'rsctf-ad').trim();
const loadRate = positiveInteger(process.env.ORGANIZER_HUB_RATE || process.env.RATE || 1, 'load rate');
const loadVus = positiveInteger(process.env.ORGANIZER_HUB_VUS || process.env.VUS || 4, 'load VUs');
const loadDuration = String(process.env.ORGANIZER_HUB_DURATION || process.env.DURATION || '20s').trim();
const runLoad = process.env.SKIP_ORGANIZER_HUB_LOAD !== '1';
const byocMode = organizerByocMode(process.env);
const reportableAcceptance = process.env.RSCTF_ACCEPTANCE_REPORTABLE === '1';
if (reportableAcceptance && (!runLoad || byocMode.skipped)) {
  throw new Error(
    'RSCTF_ACCEPTANCE_REPORTABLE=1 rejects SKIP_ORGANIZER_HUB_LOAD=1 and ' +
      'ORGANIZER_HUB_DIAGNOSTIC_SKIP_BYOC=1',
  );
}
const serverContainers = [...new Set([...webContainers, execContainer])];

const names = {
  owned: `rsctf-organizer-hub-owned-${tag}`,
  foreign: `rsctf-organizer-hub-foreign-${tag}`,
  fixtureLabel: 'org.rsctf.load.organizer-hubs',
  organizer: `${tag}admin`,
  ordinary: `${tag}user`,
  logProbe: `${tag}log`,
  organizerEmail: `${tag}.admin@organizer-hubs.invalid`,
  ordinaryEmail: `${tag}.user@organizer-hubs.invalid`,
  logProbeEmail: `${tag}.log@organizer-hubs.invalid`,
};

const state = {
  completed: false,
  reportable: reportableAcceptance && runLoad && !byocMode.skipped,
  cleanupVerified: false,
  scenarioFailure: null,
  cleanupFailure: null,
  verificationFailure: null,
  leaseFailures: [],
  users: [],
  auditRows: [],
  dockerContainers: [],
  containerGuid: null,
  containerRuntimeId: null,
  organizerToken: null,
  primaryToken: null,
  primaryName: null,
  logFloor: null,
  sockets: new Set(),
  byoc: null,
  crossGame: null,
  byocTitle: `LOADTEST-HUB-${tag}`,
  crossGameTitle: `LOADTEST-HUB-CROSS-${tag}`,
  scopedGameTitle: `LOADTEST-HUB-SCOPED-${tag}`,
  scopedGame: null,
  topologyAuthorized: false,
  evidence: {},
};
const coveredSurfaces = new Set();

function recoverySnapshot() {
  return {
    schemaVersion: 2,
    tag,
    startedAt: runStartedAt,
    completed: state.completed,
    reportable: state.reportable,
    completedAt: state.completedAt || null,
    cleanupVerified: state.cleanupVerified,
    failure: state.failure || null,
    scenarioFailure: state.scenarioFailure,
    cleanupFailure: state.cleanupFailure,
    verificationFailure: state.verificationFailure,
    leaseFailures: state.leaseFailures,
    targets: { admin: adminTarget, exec: execTarget },
    containers: {
      admin: adminContainer,
      exec: execContainer,
      postgres: pgContainer,
      redis: redisContainer,
      web: webContainers,
    },
    resources: {
      users: state.users.map(({ id, name, role }) => ({ id, name, role })),
      auditRows: state.auditRows,
      dockerContainers: state.dockerContainers,
      containerGuid: state.containerGuid,
      containerRuntimeId: state.containerRuntimeId,
      byoc: state.byoc,
      crossGame: state.crossGame,
      scopedGame: state.scopedGame,
    },
    loadSummaryPath: runLoad ? process.env.SUMMARY_JSON || null : null,
    evidence: state.evidence,
  };
}

function saveRecovery() {
  persistRecovery(recoveryPath, recoverySnapshot());
}
let lock;
let databaseLock;
let interrupted = null;
for (const signal of ['SIGINT', 'SIGTERM']) {
  process.once(signal, () => {
    interrupted = signal;
  });
}

function checkInterrupted() {
  if (interrupted) throw new Error(`organizer-hub scenario interrupted by ${interrupted}`);
}

function requireCondition(condition, message) {
  if (!condition) throw new Error(message);
}

function recordPrivilegedHubSurface(surfaceId, method, path) {
  const actualId = privilegedHubSurfaceId(method, path);
  requireCondition(
    actualId === surfaceId,
    `privileged hub surface ${surfaceId} was recorded for ${method} ${path} (${actualId})`,
  );
  requireCondition(!coveredSurfaces.has(surfaceId), `privileged hub surface ${surfaceId} was recorded twice`);
  coveredSurfaces.add(surfaceId);
}

function sqlLiteral(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function dockerMust(args, label) {
  const result = docker(args);
  if (result.status !== 0) {
    throw new Error(`${label} failed: ${(result.stderr || result.stdout || '').trim().slice(0, 500)}`);
  }
  return result.stdout.trim();
}

function inspectContainer(name, label) {
  const raw = dockerMust(['inspect', name], `inspect ${label}`);
  let records;
  try {
    records = JSON.parse(raw);
  } catch (error) {
    throw new Error(`invalid Docker inspection for ${label}: ${error.message}`);
  }
  requireCondition(Array.isArray(records) && records.length === 1, `${label} inspection is ambiguous`);
  const record = records[0];
  const ports = Object.values(record?.NetworkSettings?.Ports || {})
    .flatMap((bindings) => bindings || [])
    .map((binding) => Number(binding?.HostPort))
    .filter(Number.isSafeInteger);
  return {
    record,
    summary: {
      name,
      project: record?.Config?.Labels?.['com.docker.compose.project'],
      service: record?.Config?.Labels?.['com.docker.compose.service'],
      environment: record?.Config?.Env || [],
      addresses: Object.values(record?.NetworkSettings?.Networks || {}).flatMap((network) =>
        [network?.IPAddress, network?.GlobalIPv6Address].filter(Boolean)),
      hostPorts: ports,
      mounts: (record?.Mounts || []).map((mount) => ({
        source: mount.Source,
        destination: mount.Destination,
        rw: mount.RW,
      })),
    },
  };
}

function inspectNetwork(name, label) {
  const raw = dockerMust(['network', 'inspect', name], `inspect ${label}`);
  const records = JSON.parse(raw);
  requireCondition(Array.isArray(records) && records.length === 1, `${label} inspection is ambiguous`);
  return records[0];
}

function assertSafeTopology() {
  // Read-only Docker inspection is intentionally the first interaction with
  // the declared stack. No SQL, token mint, or authenticated request may move
  // above this gate.
  const admin = inspectContainer(adminContainer, 'admin hub container');
  const exec = adminContainer === execContainer
    ? admin
    : inspectContainer(execContainer, 'containerExec owner');
  const postgres = inspectContainer(pgContainer, 'PostgreSQL');
  const redis = inspectContainer(redisContainer, 'Redis');
  const webReplicas = webContainers.map((container, index) => ({
    target: webTargets[index],
    inspection: container === adminContainer
      ? admin
      : inspectContainer(container, `web replica[${index}]`),
  }));
  const composeProject = String(admin.summary.project || '').trim();
  requireCondition(TARGET === adminTarget, `TARGET must exactly match acknowledged admin target ${adminTarget}`);
  requireCondition(PG === pgContainer, `PG_CONTAINER must exactly match acknowledged PostgreSQL ${pgContainer}`);
  const scope = dockerScopeFromContainerEnv(exec.summary.environment);
  const configuredAdNetwork = exec.summary.environment
    .find((entry) => String(entry).startsWith('RSCTF_AD_VPN_SERVICES_NETWORK='))
    ?.slice('RSCTF_AD_VPN_SERVICES_NETWORK='.length);
  requireCondition(
    configuredAdNetwork === adNetwork,
    `AD_NET must equal the exec owner's RSCTF_AD_VPN_SERVICES_NETWORK (${configuredAdNetwork || '<missing>'})`,
  );
  const tunnelNetwork = inspectNetwork(NET, 'BYOC tunnel network');
  const checkerNetwork = inspectNetwork(adNetwork, 'A&D checker network');
  assertOrganizerHubAcknowledgements(process.env, {
    adminTarget,
    execTarget,
    webTargets,
    adminContainer,
    execContainer,
    webContainers,
    pgContainer,
    redisContainer,
    composeProject,
    network: NET,
    adNetwork,
  });
  assertDisposableOrganizerTopology({
    adminTarget,
    execTarget,
    composeProject,
    marker: stackMarker,
    admin: admin.summary,
    exec: exec.summary,
    webReplicas: webReplicas.map(({ target, inspection }) => ({
      target,
      container: inspection.summary,
    })),
    postgres: postgres.summary,
    redis: redis.summary,
  });
  requireCondition(
    tunnelNetwork?.Labels?.['com.docker.compose.project'] === composeProject,
    `BYOC tunnel network ${NET} is not owned by Compose project ${composeProject}`,
  );
  requireCondition(
    Object.hasOwn(tunnelNetwork?.Containers || {}, exec.record.Id),
    `containerExec owner ${execContainer} is not attached to acknowledged network ${NET}`,
  );
  requireCondition(
    checkerNetwork?.Labels?.['com.docker.compose.project'] === composeProject ||
      (checkerNetwork?.Labels?.['rsctf.managed'] === scope &&
        checkerNetwork?.Labels?.['rsctf.scope'] === scope),
    `A&D checker network ${adNetwork} is not owned by this RSCTF installation`,
  );
  requireCondition(
    Object.hasOwn(checkerNetwork?.Containers || {}, exec.record.Id),
    `containerExec owner ${execContainer} is not attached to acknowledged A&D network ${adNetwork}`,
  );
  return { composeProject, admin, exec, webReplicas, postgres, redis, scope };
}

async function request(baseUrl, method, path, { token, body, headers = {}, timeoutMs = 30_000 } = {}) {
  const requestHeaders = { ...headers };
  if (token) requestHeaders.authorization = `Bearer ${token}`;
  if (body !== undefined && !requestHeaders['content-type']) requestHeaders['content-type'] = 'application/json';
  const response = await fetch(`${baseUrl}${path}`, {
    method,
    headers: requestHeaders,
    body: body === undefined
      ? undefined
      : requestHeaders['content-type'] === 'application/json'
        ? JSON.stringify(body)
        : body,
    signal: AbortSignal.timeout(timeoutMs),
  });
  const text = await response.text();
  let json;
  try {
    json = text ? JSON.parse(text) : undefined;
  } catch {
    json = undefined;
  }
  return { status: response.status, text, json, headers: response.headers };
}

function responseError(response, label) {
  return new Error(`${label} returned ${response.status}: ${response.text.slice(0, 300)}`);
}

async function expectStatus(response, expected, label) {
  if (response.status !== expected) throw responseError(response, `${label} (expected ${expected})`);
  return response;
}

function userByEmail(email) {
  const raw = sql(
    `SELECT COALESCE(json_build_object('id',id::text,'stamp',security_stamp,` +
      `'role',role,'name',user_name)::text,'') FROM "AspNetUsers" ` +
      `WHERE normalized_email=upper(${sqlLiteral(email)})`,
  );
  if (!raw) throw new Error(`fixture user ${email} is absent`);
  return JSON.parse(raw);
}

function resolvePrimaryAdmin() {
  const supplied = String(process.env.ADMIN_TOKEN || '').trim();
  if (supplied) {
    let claims;
    try {
      claims = JSON.parse(Buffer.from(supplied.split('.')[1], 'base64url').toString('utf8'));
    } catch {
      throw new Error('ADMIN_TOKEN is not a decodable JWT');
    }
    requireCondition(/^[0-9a-f-]{36}$/i.test(claims?.sub || ''), 'ADMIN_TOKEN has no UUID subject');
    const row = sql(
      `SELECT COALESCE(json_build_object('id',id::text,'stamp',security_stamp,` +
        `'role',role,'name',user_name)::text,'') FROM "AspNetUsers" WHERE id=${sqlLiteral(claims.sub)}::uuid`,
    );
    requireCondition(Boolean(row), 'ADMIN_TOKEN subject does not exist');
    const admin = JSON.parse(row);
    requireCondition(admin.role === 3, 'ADMIN_TOKEN subject is not currently Admin');
    requireCondition(typeof admin.name === 'string' && admin.name.length > 0, 'ADMIN_TOKEN subject has no username');
    return { ...admin, token: supplied };
  }
  const raw = sql(
    `SELECT COALESCE(json_build_object('id',id::text,'stamp',security_stamp,` +
      `'role',role,'name',user_name)::text,'') FROM "AspNetUsers" ` +
      `WHERE role=3 ORDER BY register_time_utc,id LIMIT 1`,
  );
  if (!raw) throw new Error('no Admin account exists');
  const admin = JSON.parse(raw);
  requireCondition(typeof admin.name === 'string' && admin.name.length > 0, 'primary Admin has no username');
  return { ...admin, token: mintJwt(admin.id, admin.stamp, 3) };
}

function maxLogId() {
  return Number(sql('SELECT COALESCE(max(id),0) FROM "Logs"'));
}

function captureAuditRow(afterId, userName, message) {
  const raw = sql(
    `SELECT COALESCE(json_agg(json_build_object('id',id,'logger',logger,'name',user_name,` +
      `'message',message,'level',level,'status',status) ORDER BY id),'[]'::json)::text ` +
      `FROM "Logs" WHERE id>${afterId} AND logger='AdminController' ` +
      `AND user_name=${sqlLiteral(userName)} AND message=${sqlLiteral(message)}`,
  );
  const rows = JSON.parse(raw || '[]');
  requireCondition(rows.length === 1, `expected one exact audit row for ${userName}/${message}, got ${rows.length}`);
  state.auditRows.push(rows[0]);
  saveRecovery();
  return rows[0];
}

async function addUsers(token, models, actorName) {
  const before = maxLogId();
  const response = await request(adminTarget, 'POST', '/api/admin/users', { token, body: models, timeoutMs: 60_000 });
  await expectStatus(response, 200, 'add organizer-hub users');
  captureAuditRow(before, actorName, `Successfully added ${models.length} users`);
}

async function createIdentities(primary) {
  await addUsers(primary.token, [
    {
      userName: names.organizer,
      email: names.organizerEmail,
      password: `Org-${tag}-Admin!9`,
      realName: 'Organizer hub disposable admin',
    },
    {
      userName: names.ordinary,
      email: names.ordinaryEmail,
      password: `Org-${tag}-User!9`,
      realName: 'Organizer hub authorization probe',
    },
  ], primary.name);
  const organizer = userByEmail(names.organizerEmail);
  state.users.push(organizer);
  const ordinary = userByEmail(names.ordinaryEmail);
  state.users.push(ordinary);
  saveRecovery();
  const ordinaryToken = mintJwt(ordinary.id, ordinary.stamp, 1);

  const promoted = await request(adminTarget, 'PUT', `/api/admin/users/${organizer.id}`, {
    token: primary.token,
    body: { role: 'Admin' },
  });
  await expectStatus(promoted, 200, 'promote disposable organizer');
  const liveOrganizer = userByEmail(names.organizerEmail);
  requireCondition(liveOrganizer.role === 3 && liveOrganizer.stamp !== organizer.stamp, 'organizer promotion did not rotate its session stamp');
  state.users[0] = liveOrganizer;
  state.organizerToken = mintJwt(liveOrganizer.id, liveOrganizer.stamp, 3);
  saveRecovery();
  return { organizer: liveOrganizer, ordinary, ordinaryToken };
}

function websocketUrl(baseUrl, path, token, connectionToken) {
  const url = new URL(path, `${baseUrl}/`);
  url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:';
  if (connectionToken) url.searchParams.set('id', connectionToken);
  if (token) url.searchParams.set('access_token', token);
  return url.toString();
}

class SignalRClient {
  constructor(socket, label) {
    this.socket = socket;
    this.label = label;
    this.frames = [];
    this.remainder = '';
    this.waiters = new Set();
    this.closed = false;
    this.closeInfo = null;
    socket.addEventListener('message', (event) => this.accept(event.data));
    socket.addEventListener('close', (event) => {
      this.closed = true;
      this.closeInfo = { code: event.code, reason: event.reason };
      this.flushWaiters();
    });
  }

  accept(data) {
    let decoded;
    try {
      decoded = consumeHubFrames({ remainder: this.remainder }, data);
    } catch (error) {
      for (const waiter of this.waiters) waiter.reject(new Error(`${this.label} sent malformed JSON: ${error.message}`));
      this.waiters.clear();
      return;
    }
    this.remainder = decoded.remainder;
    this.frames.push(...decoded.frames);
    this.flushWaiters();
  }

  flushWaiters() {
    for (const waiter of [...this.waiters]) {
      const match = this.frames.slice(waiter.after).find(waiter.predicate);
      if (match) {
        clearTimeout(waiter.timeout);
        this.waiters.delete(waiter);
        waiter.resolve(match);
      } else if (this.closed && waiter.acceptClose) {
        clearTimeout(waiter.timeout);
        this.waiters.delete(waiter);
        waiter.resolve(this.closeInfo);
      } else if (this.closed) {
        clearTimeout(waiter.timeout);
        this.waiters.delete(waiter);
        waiter.reject(new Error(`${this.label} closed before ${waiter.description}`));
      }
    }
  }

  waitFor(predicate, description, { after = 0, timeoutMs = 8_000, acceptClose = false } = {}) {
    return new Promise((resolve, reject) => {
      const waiter = {
        predicate,
        description,
        after,
        acceptClose,
        resolve,
        reject,
        timeout: setTimeout(() => {
          this.waiters.delete(waiter);
          reject(new Error(`${this.label} timed out waiting for ${description}`));
        }, timeoutMs),
      };
      this.waiters.add(waiter);
      this.flushWaiters();
    });
  }

  send(value) {
    if (this.closed) throw new Error(`${this.label} is closed`);
    this.socket.send(hubFrame(value));
  }

  async invoke(target, args, invocationId) {
    const after = this.frames.length;
    const completion = this.waitFor(
      (frame) => frame?.type === 3 && String(frame.invocationId) === String(invocationId),
      `${target} completion`,
      { after },
    );
    this.send({ type: 1, invocationId: String(invocationId), target, arguments: args });
    const frame = await completion;
    if (frame.error) throw new Error(`${this.label} ${target} failed: ${frame.error}`);
    return frame;
  }

  waitClosed(timeoutMs = 18_000) {
    if (this.closed) return Promise.resolve(this.closeInfo);
    return this.waitFor(() => false, 'authorization revocation close', {
      after: this.frames.length,
      timeoutMs,
      acceptClose: true,
    });
  }

  async close() {
    if (this.closed) return;
    const closed = this.waitClosed(2_000).catch(() => undefined);
    this.socket.close(1000, 'test complete');
    await closed;
  }
}

async function connectHub(baseUrl, path, token, connectionToken, label, surfaceId = null) {
  const socket = new WebSocket(websocketUrl(baseUrl, path, token, connectionToken));
  await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error(`${label} WebSocket upgrade timed out`)), 8_000);
    socket.addEventListener('open', () => {
      clearTimeout(timeout);
      resolve();
    }, { once: true });
    socket.addEventListener('error', () => {
      clearTimeout(timeout);
      reject(new Error(`${label} WebSocket upgrade failed`));
    }, { once: true });
  });
  const client = new SignalRClient(socket, label);
  state.sockets.add(client);
  const after = client.frames.length;
  client.send({ protocol: 'json', version: 1 });
  await client.waitFor(
    (frame) => frame && typeof frame === 'object' && Object.keys(frame).length === 0,
    'SignalR handshake acknowledgement',
    { after },
  );
  if (surfaceId) recordPrivilegedHubSurface(surfaceId, 'GET', path);
  return client;
}

async function expectWebSocketRejected(baseUrl, path, token, label) {
  await new Promise((resolve, reject) => {
    const socket = new WebSocket(websocketUrl(baseUrl, path, token));
    let opened = false;
    const timeout = setTimeout(() => {
      socket.close();
      reject(new Error(`${label} did not reject the WebSocket`));
    }, 5_000);
    socket.addEventListener('open', () => {
      opened = true;
      clearTimeout(timeout);
      socket.close();
      reject(new Error(`${label} accepted an unauthorized WebSocket`));
    }, { once: true });
    const rejected = () => {
      if (opened) return;
      clearTimeout(timeout);
      resolve();
    };
    socket.addEventListener('error', rejected, { once: true });
    socket.addEventListener('close', rejected, { once: true });
  });
}

async function negotiate(baseUrl, path, token, expected, label, surfaceId = null) {
  const response = await request(baseUrl, 'POST', `${path}/negotiate?negotiateVersion=1`, {
    token,
    body: '',
    headers: { 'content-type': 'text/plain;charset=UTF-8' },
  });
  await expectStatus(response, expected, label);
  if (expected !== 200) return null;
  const connectionToken = assertNegotiateContract(response, label);
  if (surfaceId) recordPrivilegedHubSurface(surfaceId, 'POST', `${path}/negotiate`);
  return connectionToken;
}

async function expectUnmatched(response, label, allowed = [404]) {
  requireCondition(
    allowed.includes(response.status),
    `${label} is exposed (expected ${allowed.join('/')}, got ${response.status})`,
  );
}

async function expectWebGetAbsent(baseUrl, path, label) {
  const response = await request(baseUrl, 'GET', path);
  if ([404, 405].includes(response.status)) return;
  requireCondition(response.status === 200, `${label} returned unexpected ${response.status}`);
  requireCondition(
    /^text\/html(?:;|$)/i.test(response.headers.get('content-type') || '') &&
      /<(?:!doctype\s+html|html)(?:\s|>)/i.test(response.text),
    `${label} returned 200 without the web replica's SPA fallback`,
  );
}

async function inverseTopologyPreflight() {
  const scopedProbe = scopedContainerExecPath(1);
  for (const target of webTargets) {
    for (const path of ['/hub/containerExec', scopedProbe]) {
      await expectUnmatched(
        await request(target, 'POST', `${path}/negotiate?negotiateVersion=1`),
        `${target} ${path}/negotiate`,
        [404, 405],
      );
      await expectWebGetAbsent(target, path, `${target} ${path} plain GET`);
      await expectWebSocketRejected(target, path, null, `${target} ${path} stateful-route absence`);
    }
  }

  await expectUnmatched(
    await request(execTarget, 'POST', '/hub/admin/negotiate?negotiateVersion=1'),
    'control AdminHub negotiate',
  );
  await expectUnmatched(
    await request(execTarget, 'GET', '/hub/admin'),
    'control AdminHub GET',
  );
  await expectWebSocketRejected(execTarget, '/hub/admin', null, 'control AdminHub route absence');
  for (const path of ['/api/admin/teams?count=1&skip=0', '/api/edit/games']) {
    await expectUnmatched(
      await request(execTarget, 'GET', path),
      `control ordinary route ${path}`,
    );
  }
  state.evidence.inverseTopology = {
    webTargets,
    web: 'global/scoped containerExec negotiate absent; GET/upgrade rejected with SPA fallback accounted',
    control: 'AdminHub, /api/admin, and /api/edit absent',
  };
}

async function authorizationMatrix(ordinaryToken, organizerToken) {
  const surfaces = [
    { target: adminTarget, path: '/hub/admin', label: 'AdminHub' },
    { target: execTarget, path: '/hub/containerExec', label: 'ContainerExecHub' },
  ];
  const tokens = [
    { token: null, expected: 401, label: 'anonymous' },
    { token: ordinaryToken, expected: 403, label: 'ordinary user' },
  ];
  for (const surface of surfaces) {
    for (const identity of tokens) {
      await negotiate(
        surface.target,
        surface.path,
        identity.token,
        identity.expected,
        `${surface.label} ${identity.label} negotiate`,
      );
      await expectWebSocketRejected(
        surface.target,
        surface.path,
        identity.token,
        `${surface.label} ${identity.label}`,
      );
    }
    await negotiate(surface.target, surface.path, organizerToken, 200, `${surface.label} Admin negotiate`);
  }
  state.evidence.authorization = 'anonymous=401, ordinary=403, Admin negotiate+WebSocket accepted';
}

async function healthPreflight(topology) {
  for (const [label, target, roles] of [
    ...webTargets.map((target, index) => [`web[${index}]`, target, ['web']]),
    ['exec', execTarget, ['control', 'network']],
  ]) {
    const response = await request(target, 'GET', '/healthz');
    await expectStatus(response, 200, `${label} /healthz`);
    const role = response.headers.get('x-rsctf-role');
    requireCondition(roles.includes(role), `${label} target reports role ${role || '<missing>'}`);
  }
  state.evidence.topology = {
    composeProject: topology.composeProject,
    adminTarget,
    execTarget,
    adminContainer,
    execContainer,
    pgContainer,
    redisContainer,
    webTargets,
    webContainers,
    tunnelNetwork: NET,
    adNetwork,
  };
  saveRecovery();
}

async function receivedLogLifecycle(organizer, adminClient) {
  const after = adminClient.frames.length;
  const event = adminClient.waitFor(
    (frame) => frame?.type === 1 && frame.target === 'ReceivedLog' &&
      frame.arguments?.[0]?.msg === 'Successfully added 1 users' &&
      frame.arguments?.[0]?.name === organizer.name,
    'matching ReceivedLog event',
    { after, timeoutMs: 10_000 },
  );
  await addUsers(state.organizerToken, [{
    userName: names.logProbe,
    email: names.logProbeEmail,
    password: `Org-${tag}-Log!9`,
    realName: 'Organizer hub live log probe',
  }], organizer.name);
  state.users.push(userByEmail(names.logProbeEmail));
  const payload = assertReceivedLog(await event, {
    message: 'Successfully added 1 users',
    userName: organizer.name,
  });
  const logs = await request(
    adminTarget,
    'GET',
    `/api/admin/logs?count=20&skip=0&search=${encodeURIComponent(organizer.name)}`,
    { token: state.organizerToken },
  );
  await expectStatus(logs, 200, 'poll persisted ReceivedLog row');
  const rows = Array.isArray(logs.json) ? logs.json : logs.json?.data;
  const persisted = rows?.find((row) =>
    row.name === organizer.name && row.msg === 'Successfully added 1 users');
  requireCondition(Boolean(persisted), 'ReceivedLog action is absent from the persisted Admin log list');
  requireCondition(
    JSON.stringify(persisted) === JSON.stringify(payload),
    'ReceivedLog event is not byte-shape-identical to the persisted Admin log model',
  );
  state.evidence.receivedLog = payload;
  saveRecovery();
}

function createDockerFixtures(scope) {
  for (const containerName of [names.owned, names.foreign]) {
    const present = docker(['ps', '-aq', '--filter', `name=^/${containerName}$`]).stdout.trim();
    requireCondition(!present, `Docker fixture name ${containerName} already exists`);
  }
  const common = [
    'run', '-d', '--name', names.owned, '--network', 'none', '--read-only',
    '--tmpfs', '/tmp:rw,nosuid,nodev,size=16m', '--cap-drop', 'ALL',
    '--security-opt', 'no-new-privileges', '--pids-limit', '64', '--memory', '64m',
    '--label', `${names.fixtureLabel}=${tag}`,
  ];
  const ownedId = dockerMust([
    ...common,
    ...dockerOwnershipLabelArgs(scope),
    fixtureImage,
    'sh', '-c', 'trap "exit 0" TERM INT; while :; do sleep 3600; done',
  ], 'create RSCTF-owned exec fixture');
  state.dockerContainers.push({ id: ownedId, name: names.owned, owned: true });
  saveRecovery();

  const foreignId = dockerMust([
    'run', '-d', '--name', names.foreign, '--network', 'none', '--read-only',
    '--tmpfs', '/tmp:rw,nosuid,nodev,size=16m', '--cap-drop', 'ALL',
    '--security-opt', 'no-new-privileges', '--pids-limit', '64', '--memory', '64m',
    '--label', `${names.fixtureLabel}=${tag}`,
    fixtureImage,
    'sh', '-c', 'trap "exit 0" TERM INT; while :; do sleep 3600; done',
  ], 'create arbitrary raw-container fixture');
  state.dockerContainers.push({ id: foreignId, name: names.foreign, owned: false });
  saveRecovery();

  const ownedInspect = inspectContainer(ownedId, 'owned exec fixture').record;
  requireCondition(
    ownedInspect?.Config?.Labels?.['rsctf.managed'] === scope &&
      ownedInspect?.Config?.Labels?.['rsctf.scope'] === scope &&
      ownedInspect?.Config?.Labels?.[names.fixtureLabel] === tag,
    'owned exec fixture is missing exact RSCTF installation labels',
  );
  const foreignInspect = inspectContainer(foreignId, 'foreign exec fixture').record;
  requireCondition(
    foreignInspect?.Config?.Labels?.['rsctf.managed'] === undefined &&
      foreignInspect?.Config?.Labels?.['rsctf.scope'] === undefined &&
      foreignInspect?.Config?.Labels?.[names.fixtureLabel] === tag,
    'arbitrary raw fixture unexpectedly has RSCTF ownership labels',
  );
  state.containerGuid = randomUUID();
  state.containerRuntimeId = ownedId;
  const inserted = sql(
    `INSERT INTO "Containers" (` +
      `id,image,container_id,status,started_at,expect_stop_at,is_proxy,ip,port,` +
      `public_ip,public_port,game_instance_id,exercise_instance_id) VALUES (` +
      `${sqlLiteral(state.containerGuid)}::uuid,${sqlLiteral(fixtureImage)},${sqlLiteral(ownedId)},1,` +
      `now(),now()+interval '1 hour',false,'127.0.0.1',0,NULL,NULL,NULL,NULL) RETURNING id`,
  );
  requireCondition(inserted === state.containerGuid, 'failed to publish exact Containers fixture row');
  saveRecovery();
  const accidentalOwner = Number(sql(
    `SELECT (SELECT count(*) FROM "AdTeamServices" WHERE container_id=${sqlLiteral(foreignId)}) + ` +
      `(SELECT count(*) FROM "KothTargets" WHERE container_id=${sqlLiteral(foreignId)})`,
  ));
  requireCondition(accidentalOwner === 0, 'foreign raw fixture unexpectedly has a game owner');
  return { ownedId, foreignId };
}

async function waitDockerCommand(containerId, command, expected, label, timeoutMs = 5_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const result = docker(['exec', containerId, 'sh', '-c', command]);
    if (result.status === 0 && result.stdout.trim() === expected) return;
    await sleep(100);
  }
  throw new Error(`${label} was not observable in the exact Docker fixture`);
}

function dockerPathAbsent(containerId, path, label) {
  const result = docker(['exec', containerId, 'sh', '-c', `test ! -e ${sqlLiteral(path)}`]);
  requireCondition(result.status === 0, `${label} unexpectedly exists in raw-container fixture`);
}

async function containerExecLifecycle(execClient, fixtures) {
  let invocation = 1;
  const openAfter = execClient.frames.length;
  const opened = await execClient.invoke('Open', [state.containerGuid, 'sh'], invocation++);
  const sessionId = opened.result;
  requireCondition(/^[0-9a-f]{32}$/.test(sessionId || ''), 'Open did not return a SignalR exec session id');
  const welcomeFrame = await execClient.waitFor(
    (frame) => decodeReceive(frame, sessionId)?.includes('[rsctf] connected to'),
    'owned-container welcome',
    { after: openAfter },
  );
  requireCondition(!decodeReceive(welcomeFrame, sessionId).includes('unavailable'), 'owned container degraded to idle');

  await execClient.invoke('Resize', [sessionId, 101, 37], invocation++);
  await sleep(250);
  const markerPath = `/tmp/${tag}.input`;
  const sizePath = `/tmp/${tag}.size`;
  const input = Buffer.from(
    `touch ${markerPath}\nstty size > ${sizePath}\nprintf 'organizer-exec-ok\\n'\n`,
  ).toString('base64');
  const receiveAfter = execClient.frames.length;
  await execClient.invoke('Input', [sessionId, input], invocation++);
  await waitDockerCommand(fixtures.ownedId, `test -f ${markerPath} && echo yes`, 'yes', 'Input side effect');
  await waitDockerCommand(fixtures.ownedId, `cat ${sizePath}`, '37 101', 'Resize dimensions');
  await execClient.waitFor(
    (frame) => decodeReceive(frame, sessionId)?.includes('organizer-exec-ok'),
    'owned-container stdout',
    { after: receiveAfter },
  );
  await execClient.invoke('Close', [sessionId], invocation++);
  const afterClosePath = `/tmp/${tag}.after-close`;
  await execClient.invoke(
    'Input',
    [sessionId, Buffer.from(`touch ${afterClosePath}\n`).toString('base64')],
    invocation++,
  );
  await sleep(250);
  dockerPathAbsent(fixtures.ownedId, afterClosePath, 'post-Close Input side effect');

  const rawOpenAfter = execClient.frames.length;
  const rawOpened = await execClient.invoke('Open', [fixtures.foreignId, 'sh'], invocation++);
  const rawSession = rawOpened.result;
  const idle = await execClient.waitFor(
    (frame) => decodeReceive(frame, rawSession)?.includes('backend unavailable'),
    'arbitrary raw-container rejection notice',
    { after: rawOpenAfter },
  );
  requireCondition(decodeReceive(idle, rawSession).includes('terminal is idle'), 'raw-container rejection was not explicit');
  const bypassPath = `/tmp/${tag}.raw-bypass`;
  await execClient.invoke(
    'Input',
    [rawSession, Buffer.from(`touch ${bypassPath}\n`).toString('base64')],
    invocation++,
  );
  await execClient.invoke('Resize', [rawSession, 120, 50], invocation++);
  await execClient.invoke('Close', [rawSession], invocation++);
  await sleep(250);
  dockerPathAbsent(fixtures.foreignId, bypassPath, 'arbitrary raw-container bypass marker');

  state.evidence.containerExec = {
    open: true,
    inputSideEffect: true,
    resize: '37x101',
    closeRevokedSession: true,
    arbitraryRawContainer: 'idle/rejected',
  };
}

function externalAgentArtifactBlocked(error) {
  return /(?:pull access denied|manifest unknown|failed to authorize|failed to resolve|tls handshake timeout|i\/o timeout|network is unreachable|temporary failure|connection reset|unexpected eof|unexpected status|403 forbidden|error response from daemon: head)/i
    .test(String(error?.message || error));
}

async function waitFleetOffline(gameId, challengeId, participationId, timeoutMs = 12_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (A.tunnelsUpFor(gameId, challengeId, [participationId]) === 0) return;
    await sleep(100);
  }
  throw new Error('replaced BYOC relay retained a stale live endpoint');
}

async function replaceFleetRelayWithExecEnabled(gameId, challengeId, capability, serviceAddress) {
  const scope = normalizeFleetScope(gameId, challengeId, [capability.pid]);
  const relay = inspectContainer('lcbyoc_0', 'ownership-scoped BYOC relay').record;
  requireCondition(
    ownsFleetResource(relay?.Config?.Labels, scope, 'relay', capability.pid),
    'refusing to replace a BYOC relay without exact lifecycle ownership',
  );
  dockerMust(['rm', '-f', relay.Id], 'stop non-exec BYOC relay');
  await waitFleetOffline(gameId, challengeId, capability.pid);
  const endpoint = `ws://${byocRsctfIp()}:8080/api/Game/${gameId}/Ad/Byoc/Agent/` +
    `${capability.pid}/${challengeId}/${capability.token}`;
  const image = process.env.RSCTF_BYOC_AGENT_IMAGE || DEFAULT_BYOC_AGENT_IMAGE;
  dockerMust([
    'run', '-d', '--rm', '--name', 'lcbyoc_0',
    ...dockerLabelArgs(fleetLabels(scope, 'relay', capability.pid)),
    '--network', NET,
    '--security-opt', 'no-new-privileges',
    '-v', '/var/run/docker.sock:/var/run/docker.sock',
    '-e', 'RSCTF_BYOC_MODE=agent',
    '-e', `RSCTF_BYOC_TUNNEL_URL=${endpoint}`,
    '-e', `RSCTF_BYOC_SERVICE=${serviceAddress}`,
    '-e', 'RSCTF_BYOC_SERVICE_CONTAINER=lcbyoc_svc',
    image,
  ], 'start exec-enabled ownership-scoped BYOC relay');
}

async function provisionByocFixture() {
  requireCondition(
    RSCTF === execContainer,
    `BYOC helper safety requires RSCTF_CONTAINER=${execContainer} (got ${RSCTF})`,
  );
  const now = A.nowMs();
  const gameId = await A.createGame({
    title: state.byocTitle,
    hidden: false,
    practiceMode: false,
    acceptWithoutReview: true,
    start: now - 60_000,
    end: now + 3_600_000,
    adTickSeconds: 30,
    adFlagLifetimeTicks: 5,
    adGetflagWindowFraction: 0.9,
    adMinGracePeriodSeconds: 1,
  });
  state.byoc = { gameId, cid: null, pids: [], fleetStarted: false };
  saveRecovery();
  sql(
    `UPDATE "Games" SET ad_warmup_seconds=1,ad_tick_seconds=30,ad_flag_lifetime_ticks=5,` +
      `ad_getflag_window_fraction=0.9,ad_min_grace_period_seconds=1 WHERE id=${gameId}`,
  );
  const cid = await A.createChallenge(gameId, {
    title: `organizer-hub-byoc-${tag}`,
    category: 'Pwn',
    type: 'AttackDefense',
  });
  state.byoc.cid = cid;
  saveRecovery();
  const checker = A.prepareExactChecker(gameId, cid);
  await A.setChallenge(gameId, cid, {
    adSelfHosted: true,
    adAllowSelfReset: true,
    adCheckerImage: checker,
  });
  await A.addFlags(gameId, cid, [`flag{organizer_hub_${tag}}`]);
  await A.setChallenge(gameId, cid, { isEnabled: true });
  const cohort = A.seedCohort(gameId, 1);
  requireCondition(cohort.partIds?.length === 1, 'BYOC fixture did not create one accepted participation');
  state.byoc.pids = [Number(cohort.partIds[0])];
  saveRecovery();
  const service = A.startFleetService(gameId, cid);
  const [checkerHost, checkerPort] = service.checker.split(':');
  A.seedAdServices(gameId, cid, checkerHost, Number(checkerPort));
  state.byoc.fleetStarted = true;
  saveRecovery();
  const capabilities = A.startFleetForPids(gameId, cid, state.byoc.pids, service.tunnel);
  requireCondition(capabilities.length === 1, 'BYOC helper returned an ambiguous capability set');
  await A.waitForFleetReady(gameId, cid, state.byoc.pids);
  // Recreate through the same lifecycle ownership schema, with the two
  // team-host options that are intentionally opt-in in generated compose:
  // Docker socket access and the exact service-container name.
  await replaceFleetRelayWithExecEnabled(gameId, cid, capabilities[0], service.tunnel);
  await A.waitForFleetReady(gameId, cid, state.byoc.pids);
  return { gameId, cid, capability: capabilities[0] };
}

async function provisionCrossGameFixture(runtimeId) {
  const now = A.nowMs();
  const gameId = await A.createGame({
    title: state.crossGameTitle,
    hidden: true,
    practiceMode: true,
    acceptWithoutReview: true,
    start: now - 60_000,
    end: now + 3_600_000,
  });
  state.crossGame = { gameId, cid: null, containerGuid: null, runtimeId };
  saveRecovery();
  const cid = await A.createChallenge(gameId, {
    title: `organizer-hub-cross-${tag}`,
    category: 'Pwn',
    type: 'StaticContainer',
  });
  state.crossGame.cid = cid;
  saveRecovery();
  const containerGuid = randomUUID();
  state.crossGame.containerGuid = containerGuid;
  saveRecovery();
  const inserted = sql(
    `INSERT INTO "Containers" (` +
      `id,image,container_id,status,started_at,expect_stop_at,is_proxy,ip,port,` +
      `public_ip,public_port,game_instance_id,exercise_instance_id,ad_team_service_id) VALUES (` +
      `${sqlLiteral(containerGuid)}::uuid,${sqlLiteral(fixtureImage)},${sqlLiteral(runtimeId)},1,` +
      `now(),now()+interval '1 hour',false,'127.0.0.1',0,NULL,NULL,NULL,NULL,NULL) RETURNING id`,
  );
  requireCondition(inserted === containerGuid, 'failed to publish cross-game Containers fixture row');
  const attached = sql(
    `UPDATE "GameChallenges" SET test_container_id=${sqlLiteral(containerGuid)}::uuid ` +
      `WHERE id=${cid} AND game_id=${gameId} AND test_container_id IS NULL RETURNING id`,
  );
  requireCondition(Number(attached) === cid, 'failed to attach exact cross-game container fixture');
  return state.crossGame;
}

async function provisionDiagnosticScopedFixture() {
  requireCondition(
    byocMode.skipped,
    'the local scoped fixture is reserved for the explicitly non-reportable diagnostic mode',
  );
  const now = A.nowMs();
  const gameId = await A.createGame({
    title: state.scopedGameTitle,
    hidden: true,
    practiceMode: true,
    acceptWithoutReview: true,
    start: now - 60_000,
    end: now + 3_600_000,
  });
  state.scopedGame = { gameId, cid: null };
  saveRecovery();
  const cid = await A.createChallenge(gameId, {
    title: `organizer-hub-scoped-${tag}`,
    category: 'Pwn',
    type: 'StaticContainer',
  });
  state.scopedGame.cid = cid;
  saveRecovery();
  const attached = sql(
    `UPDATE "GameChallenges" SET test_container_id=${sqlLiteral(state.containerGuid)}::uuid ` +
      `WHERE id=${cid} AND game_id=${gameId} AND test_container_id IS NULL RETURNING id`,
  );
  requireCondition(Number(attached) === cid, 'failed to attach the diagnostic scoped container');
  return {
    gameId,
    cid,
    target: state.containerGuid,
    runtimeContainer: state.containerRuntimeId,
    backend: 'local diagnostic Docker',
    welcome: '[rsctf] connected to',
  };
}

async function byocExecLifecycle(execClient) {
  if (byocMode.skipped) {
    state.reportable = false;
    state.evidence.byocExec = {
      exercised: false,
      environmentBlocked: true,
      reportable: false,
      reason: 'ORGANIZER_HUB_DIAGNOSTIC_SKIP_BYOC=1 explicitly disabled the pinned agent fixture',
    };
    return null;
  }
  let fixture;
  try {
    fixture = await provisionByocFixture();
  } catch (error) {
    if (!externalAgentArtifactBlocked(error)) throw error;
    state.evidence.byocExec = {
      exercised: false,
      environmentBlocked: true,
      reportable: false,
      reason: `pinned BYOC agent artifact unavailable: ${error.message}`,
    };
    throw error;
  }

  let invocation = 100;
  const guid = `byoc:${fixture.capability.pid}:${fixture.cid}`;
  const openAfter = execClient.frames.length;
  const opened = await execClient.invoke('Open', [guid, 'sh'], invocation++);
  const sessionId = opened.result;
  requireCondition(/^[0-9a-f]{32}$/.test(sessionId || ''), 'BYOC Open did not return a session id');
  const welcome = await execClient.waitFor(
    (frame) => decodeReceive(frame, sessionId)?.includes('connected to your BYOC service'),
    'BYOC E-stream welcome',
    { after: openAfter, timeoutMs: 10_000 },
  );
  requireCondition(!decodeReceive(welcome, sessionId).includes('not connected'), 'BYOC Open degraded to idle');

  const marker = `/tmp/${tag}.byoc-input`;
  const afterReceive = execClient.frames.length;
  await execClient.invoke('Input', [
    sessionId,
    Buffer.from(`touch ${marker}\nprintf 'organizer-byoc-exec-ok\\n'\n`).toString('base64'),
  ], invocation++);
  await waitDockerCommand('lcbyoc_svc', `test -f ${marker} && echo yes`, 'yes', 'BYOC Input side effect', 10_000);
  await execClient.waitFor(
    (frame) => decodeReceive(frame, sessionId)?.includes('organizer-byoc-exec-ok'),
    'BYOC E-stream stdout',
    { after: afterReceive, timeoutMs: 10_000 },
  );
  // v1 acknowledges resize but the BYOC transport documents it as a no-op.
  await execClient.invoke('Resize', [sessionId, 99, 31], invocation++);
  await execClient.invoke('Close', [sessionId], invocation++);
  const afterClose = `/tmp/${tag}.byoc-after-close`;
  await execClient.invoke('Input', [
    sessionId,
    Buffer.from(`touch ${afterClose}\n`).toString('base64'),
  ], invocation++);
  await sleep(250);
  dockerPathAbsent('lcbyoc_svc', afterClose, 'post-Close BYOC Input side effect');
  state.evidence.byocExec = {
    exercised: true,
    reportable: true,
    open: true,
    inputSideEffect: true,
    output: true,
    resize: 'acknowledged v1 no-op',
    closeRevokedSession: true,
    gameId: fixture.gameId,
    challengeId: fixture.cid,
    participationId: fixture.capability.pid,
  };
  return fixture;
}

async function expectScopedOpenDenied(client, target, invocationId, label) {
  let denial = null;
  let opened = null;
  try {
    opened = await client.invoke('Open', [target, 'sh'], invocationId);
  } catch (error) {
    denial = error;
  }
  if (opened?.result) {
    await client.invoke('Close', [opened.result], `${invocationId}-cleanup`).catch(() => undefined);
  }
  requireCondition(
    denial && /not unambiguously owned by this game/i.test(denial.message),
    `${label} did not return the scoped ownership denial`,
  );
}

async function scopedManagerExecLifecycle(manager, managerToken, byocFixture, fixtures) {
  const routeFixture = byocFixture
    ? {
        gameId: byocFixture.gameId,
        target: `byoc:${byocFixture.capability.pid}:${byocFixture.cid}`,
        runtimeContainer: 'lcbyoc_svc',
        backend: 'same-game BYOC',
        welcome: 'connected to your BYOC service',
      }
    : await provisionDiagnosticScopedFixture();
  const cross = await provisionCrossGameFixture(fixtures.foreignId);
  const path = scopedContainerExecPath(routeFixture.gameId);
  const crossPath = scopedContainerExecPath(cross.gameId);

  await negotiate(execTarget, path, null, 401, 'missing scoped negotiate');
  await expectWebSocketRejected(execTarget, path, null, 'missing scoped upgrade');
  await negotiate(execTarget, path, managerToken, 403, 'unassigned manager scoped negotiate');
  await expectWebSocketRejected(
    execTarget,
    path,
    managerToken,
    'unassigned ordinary user scoped upgrade',
  );
  const grant = await request(
    adminTarget,
    'POST',
    `/api/edit/games/${routeFixture.gameId}/admins/${manager.id}`,
    { token: state.primaryToken },
  );
  await expectStatus(grant, 200, 'grant exact game manager membership');
  requireCondition(
    Number(sql(
      `SELECT count(*) FROM "GameManagers" WHERE game_id=${routeFixture.gameId} ` +
        `AND user_id=${sqlLiteral(manager.id)}::uuid`,
    )) === 1,
    'exact game manager membership was not persisted once',
  );

  await negotiate(execTarget, crossPath, managerToken, 403, 'cross-game manager negotiate');
  await expectWebSocketRejected(
    execTarget,
    crossPath,
    managerToken,
    'cross-game manager scoped upgrade',
  );
  await negotiate(execTarget, crossPath, state.organizerToken, 200, 'active-game Admin scoped negotiate');
  const fenced = sql(
    `UPDATE "Games" SET deletion_pending=TRUE ` +
      `WHERE id=${cross.gameId} AND deletion_pending=FALSE RETURNING id`,
  );
  requireCondition(Number(fenced) === cross.gameId, 'failed to fence the deletion-pending scoped game');
  try {
    await negotiate(
      execTarget,
      crossPath,
      state.organizerToken,
      403,
      'deletion-pending game Admin scoped negotiate',
    );
    await expectWebSocketRejected(
      execTarget,
      crossPath,
      state.organizerToken,
      'deletion-pending game Admin scoped upgrade',
    );
  } finally {
    const restored = sql(
      `UPDATE "Games" SET deletion_pending=FALSE ` +
        `WHERE id=${cross.gameId} AND deletion_pending=TRUE RETURNING id`,
    );
    requireCondition(Number(restored) === cross.gameId, 'failed to restore the scoped deletion fence');
  }
  await negotiate(execTarget, path, state.organizerToken, 200, 'Admin scoped negotiate');
  const connection = await negotiate(
    execTarget,
    path,
    managerToken,
    200,
    'game manager scoped negotiate',
    'scoped_container_exec_negotiate',
  );
  const client = await connectHub(
    execTarget,
    path,
    managerToken,
    connection,
    'GameManagerContainerExecHub E2E',
    'scoped_container_exec_upgrade',
  );

  let invocation = 200;
  const target = routeFixture.target;
  const openAfter = client.frames.length;
  const opened = await client.invoke('Open', [target, 'sh'], invocation++);
  const sessionId = opened.result;
  requireCondition(/^[0-9a-f]{32}$/.test(sessionId || ''), 'manager Open did not return a session id');
  await client.waitFor(
    (frame) => decodeReceive(frame, sessionId)?.includes(routeFixture.welcome),
    `manager ${routeFixture.backend} welcome`,
    { after: openAfter, timeoutMs: 10_000 },
  );
  const marker = `/tmp/${tag}.manager-input`;
  const receiveAfter = client.frames.length;
  await client.invoke('Resize', [sessionId, 103, 39], invocation++);
  await client.invoke('Input', [
    sessionId,
    Buffer.from(`touch ${marker}\nprintf 'manager-scoped-exec-ok\\n'\n`).toString('base64'),
  ], invocation++);
  await waitDockerCommand(
    routeFixture.runtimeContainer,
    `test -f ${marker} && echo yes`,
    'yes',
    `manager ${routeFixture.backend} Input side effect`,
    10_000,
  );
  await client.waitFor(
    (frame) => decodeReceive(frame, sessionId)?.includes('manager-scoped-exec-ok'),
    `manager ${routeFixture.backend} stdout`,
    { after: receiveAfter, timeoutMs: 10_000 },
  );
  await expectScopedOpenDenied(
    client,
    cross.containerGuid,
    invocation++,
    'cross-game public container',
  );
  await expectScopedOpenDenied(
    client,
    fixtures.foreignId,
    invocation++,
    'arbitrary raw host container',
  );
  dockerPathAbsent(fixtures.foreignId, `/tmp/${tag}.manager-bypass`, 'scoped manager bypass marker');

  state.evidence.scopedManagerExec = {
    exercised: true,
    reportable: Boolean(byocFixture),
    gameId: routeFixture.gameId,
    allowed: `${routeFixture.backend} Open/Input/output/Resize with the session retained through load`,
    anonymous: 'negotiate=401 and upgrade rejected',
    unassignedOrdinary: 'negotiate=403 and upgrade rejected',
    crossGameManager: 'negotiate=403 and upgrade rejected',
    deletionPendingGame: 'Admin negotiate=403 and upgrade rejected',
    crossGameTarget: 'denied',
    arbitraryRawTarget: 'denied',
    membershipRevocation: 'pending after fixed-rate load',
  };
  return {
    client,
    manager,
    managerToken,
    gameId: routeFixture.gameId,
    path,
    target,
    sessionId,
    invocation,
    runtimeContainer: routeFixture.runtimeContainer,
  };
}

async function revokeScopedManagerSession(context) {
  if (!context) return;
  const { client, gameId, manager, managerToken, path, runtimeContainer, sessionId } = context;
  const frameAfter = client.frames.length;
  const closedFrame = client.waitFor(
    (frame) => frame?.type === 1 && frame.target === 'Closed' && frame.arguments?.[0] === sessionId,
    'scoped session authorization-revoked Closed event',
    { after: frameAfter, timeoutMs: 8_000 },
  );
  const socketClosed = client.waitClosed(8_000);
  const revoke = await request(
    adminTarget,
    'DELETE',
    `/api/edit/games/${gameId}/admins/${manager.id}`,
    { token: state.primaryToken },
  );
  await expectStatus(revoke, 200, 'revoke exact game manager membership');
  requireCondition(
    Number(sql(
      `SELECT count(*) FROM "GameManagers" ` +
        `WHERE game_id=${gameId} ` +
        `AND user_id=${sqlLiteral(manager.id)}::uuid`,
    )) === 0,
    'revoked game manager membership still exists',
  );

  const afterRevokePath = `/tmp/${tag}.manager-after-revoke`;
  requireCondition(!client.closed, 'manager socket closed before the post-revocation Input probe');
  client.send({
    type: 1,
    invocationId: String(context.invocation),
    target: 'Input',
    arguments: [
      sessionId,
      Buffer.from(`touch ${afterRevokePath}\n`).toString('base64'),
    ],
  });
  const outboundClosed = await closedFrame;
  requireCondition(
    /authorization revoked/i.test(String(outboundClosed.arguments?.[1] || '')),
    'scoped session Closed event did not carry the authorization-revoked reason',
  );
  await socketClosed;
  await sleep(250);
  dockerPathAbsent(runtimeContainer, afterRevokePath, 'post-revocation manager Input side effect');
  await negotiate(execTarget, path, managerToken, 403, 'revoked manager scoped negotiate');

  state.evidence.scopedManagerExec.membershipRevocation =
    'active shell emitted Closed(authorization revoked), socket closed, no Input side effect, renegotiate=403';
}

async function loadPhase(organizerToken, scopedManager) {
  if (!runLoad) {
    state.reportable = false;
    state.evidence.load = {
      skipped: true,
      reportable: false,
      reason: 'SKIP_ORGANIZER_HUB_LOAD=1',
    };
    return;
  }
  const status = runK6('organizer-hubs.js', {
    ADMIN_TARGET: adminTarget,
    EXEC_TARGET: execTarget,
    ADMIN_TOKEN: organizerToken,
    CONTAINER_GUID: state.containerGuid,
    MANAGER_TOKEN: scopedManager?.managerToken || '',
    SCOPED_GAME_ID: scopedManager?.gameId || '',
    SCOPED_TARGET: scopedManager?.target || '',
    RATE: loadRate,
    VUS: loadVus,
    DURATION: loadDuration,
    ORGANIZER_HUBS_DISPOSABLE: '1',
    CONFIRM_ORGANIZER_HUB_ADMIN_TARGET: adminTarget,
    CONFIRM_ORGANIZER_HUB_EXEC_TARGET: execTarget,
    SUMMARY_JSON: process.env.SUMMARY_JSON || '',
  });
  requireCondition(status === 0, `organizer-hub k6 load gate exited ${status}`);
  state.evidence.load = {
    skipped: false,
    reportable: state.reportable,
    ratePerTwoSeconds: loadRate,
    vus: loadVus,
    duration: loadDuration,
    scopedManagerExec: Boolean(scopedManager),
  };
}

async function revokeOrganizerSessions(organizer, adminClient, execClient) {
  const adminClosed = adminClient.waitClosed(18_000);
  const execClosed = execClient.waitClosed(8_000);
  const response = await request(adminTarget, 'PUT', `/api/admin/users/${organizer.id}`, {
    token: state.organizerToken,
    body: { role: 'User' },
  });
  await expectStatus(response, 200, 'self-demote disposable organizer');
  const demoted = userByEmail(names.organizerEmail);
  requireCondition(demoted.role === 1 && demoted.stamp !== organizer.stamp, 'self-demotion did not rotate the session stamp');
  await sleep(1_100);
  // ContainerExec revalidates before every invocation. The old token must close
  // the socket without acknowledging this Input; AdminHub revalidates on its
  // bounded 15-second lease tick.
  if (!execClient.closed) {
    execClient.send({
      type: 1,
      invocationId: 'revoked-input',
      target: 'Input',
      arguments: ['missing-session', Buffer.from('true\n').toString('base64')],
    });
  }
  await execClosed;
  await adminClosed;
  state.evidence.revocation = 'role/stamp rotation closed AdminHub and ContainerExecHub';
}

async function ensureOrganizerDemoted() {
  if (!state.users[0] || !state.organizerToken) return;
  let current;
  try {
    current = userByEmail(names.organizerEmail);
  } catch {
    return;
  }
  if (current.role !== 3) return;
  const response = await request(adminTarget, 'PUT', `/api/admin/users/${current.id}`, {
    token: state.organizerToken,
    body: { role: 'User' },
  });
  if (response.status !== 200 && response.status !== 401) throw responseError(response, 'cleanup organizer demotion');
  const after = userByEmail(names.organizerEmail);
  requireCondition(after.role !== 3, 'cleanup could not demote disposable organizer');
}

function cleanupResidualSnapshot({
  cleanupAuditRows,
  cleanupByoc,
  cleanupCross,
  cleanupScoped,
  cleanupDocker,
}) {
  const emails = [names.organizerEmail, names.ordinaryEmail, names.logProbeEmail]
    .map(sqlLiteral)
    .join(',');
  const auditIds = [...cleanupAuditRows.keys()];
  return {
    users: Number(sql(`SELECT count(*) FROM "AspNetUsers" WHERE email IN (${emails})`)),
    primaryContainer: state.containerGuid
      ? Number(sql(`SELECT count(*) FROM "Containers" WHERE id=${sqlLiteral(state.containerGuid)}::uuid`))
      : 0,
    auditRows: auditIds.length
      ? Number(sql(`SELECT count(*) FROM "Logs" WHERE id IN (${auditIds.join(',')})`))
      : 0,
    dockerFixtures: [...cleanupDocker.values()].filter((fixture) =>
      docker(['ps', '-aq', '--filter', `name=^/${fixture.name}$`]).stdout.trim()).length,
    byocGame: cleanupByoc
      ? Number(sql(`SELECT count(*) FROM "Games" WHERE id=${cleanupByoc.gameId}`))
      : 0,
    crossGame: cleanupCross
      ? Number(sql(`SELECT count(*) FROM "Games" WHERE id=${cleanupCross.gameId}`))
      : 0,
    scopedGame: cleanupScoped
      ? Number(sql(`SELECT count(*) FROM "Games" WHERE id=${cleanupScoped.gameId}`))
      : 0,
    crossContainer: cleanupCross?.containerGuid
      ? Number(sql(
        `SELECT count(*) FROM "Containers" ` +
          `WHERE id=${sqlLiteral(cleanupCross.containerGuid)}::uuid`,
      ))
      : 0,
  };
}

function requireZeroResidualSnapshot(snapshot, label) {
  for (const [resource, count] of Object.entries(snapshot)) {
    requireCondition(count === 0, `${label}: ${resource} has ${count} residual rows/resources`);
  }
}

async function cleanup() {
  if (!state.topologyAuthorized) {
    state.evidence.cleanup = 'skipped before disposable marker/topology authorization';
    return;
  }
  const errors = [];
  for (const socket of [...state.sockets]) {
    try {
      await socket.close();
    } catch (error) {
      errors.push(`socket cleanup: ${error.message}`);
    }
  }
  let cleanupByoc = state.byoc;
  let cleanupCross = state.crossGame;
  let cleanupScoped = state.scopedGame;
  try {
    const discovered = sql(`SELECT id FROM "Games" WHERE title=${sqlLiteral(state.byocTitle)} ORDER BY id`)
      .split('\n')
      .filter(Boolean)
      .map(Number);
    if (discovered.length > 1) throw new Error('disposable BYOC game title is ambiguous');
    if (!cleanupByoc && discovered.length === 1) {
      cleanupByoc = { gameId: discovered[0], cid: null, pids: [] };
    } else if (cleanupByoc && discovered.length === 1 && discovered[0] !== cleanupByoc.gameId) {
      throw new Error('disposable BYOC game identity changed');
    }
  } catch (error) {
    errors.push(`discover BYOC namespace: ${error.message}`);
  }
  try {
    const discovered = sql(`SELECT id FROM "Games" WHERE title=${sqlLiteral(state.crossGameTitle)} ORDER BY id`)
      .split('\n')
      .filter(Boolean)
      .map(Number);
    if (discovered.length > 1) throw new Error('disposable cross-game title is ambiguous');
    if (!cleanupCross && discovered.length === 1) {
      cleanupCross = { gameId: discovered[0], cid: null, containerGuid: null, runtimeId: null };
    } else if (cleanupCross && discovered.length === 1 && discovered[0] !== cleanupCross.gameId) {
      throw new Error('disposable cross-game identity changed');
    }
  } catch (error) {
    errors.push(`discover cross-game namespace: ${error.message}`);
  }
  try {
    const discovered = sql(`SELECT id FROM "Games" WHERE title=${sqlLiteral(state.scopedGameTitle)} ORDER BY id`)
      .split('\n')
      .filter(Boolean)
      .map(Number);
    if (discovered.length > 1) throw new Error('disposable scoped-game title is ambiguous');
    if (!cleanupScoped && discovered.length === 1) {
      cleanupScoped = { gameId: discovered[0], cid: null };
    } else if (cleanupScoped && discovered.length === 1 && discovered[0] !== cleanupScoped.gameId) {
      throw new Error('disposable scoped-game identity changed');
    }
  } catch (error) {
    errors.push(`discover scoped-game namespace: ${error.message}`);
  }
  if (cleanupScoped?.cid && state.containerGuid) {
    try {
      const detached = sql(
        `UPDATE "GameChallenges" SET test_container_id=NULL ` +
          `WHERE id=${cleanupScoped.cid} AND game_id=${cleanupScoped.gameId} ` +
          `AND test_container_id=${sqlLiteral(state.containerGuid)}::uuid RETURNING id`,
      );
      if (detached && Number(detached) !== cleanupScoped.cid) {
        throw new Error('detached the wrong scoped-game challenge');
      }
    } catch (error) {
      errors.push(`scoped-game container fixture: ${error.message}`);
    }
  }
  if (cleanupCross?.containerGuid) {
    try {
      const detached = sql(
        `UPDATE "GameChallenges" SET test_container_id=NULL ` +
          `WHERE id=${cleanupCross.cid} AND game_id=${cleanupCross.gameId} ` +
          `AND test_container_id=${sqlLiteral(cleanupCross.containerGuid)}::uuid RETURNING id`,
      );
      if (detached && Number(detached) !== cleanupCross.cid) {
        throw new Error('detached the wrong cross-game challenge');
      }
      const removed = sql(
        `DELETE FROM "Containers" WHERE id=${sqlLiteral(cleanupCross.containerGuid)}::uuid ` +
          `AND container_id=${sqlLiteral(cleanupCross.runtimeId)} RETURNING id`,
      );
      if (removed && removed !== cleanupCross.containerGuid) {
        throw new Error('removed the wrong cross-game Containers row');
      }
    } catch (error) {
      errors.push(`cross-game container fixture: ${error.message}`);
    }
  }
  if (cleanupByoc || cleanupCross || cleanupScoped) {
    try {
      if (cleanupByoc) {
        A.teardownFleet({
          gameId: cleanupByoc.gameId,
          cid: cleanupByoc.cid,
          pids: cleanupByoc.pids,
        });
      }
    } catch (error) {
      errors.push(`BYOC fleet: ${error.message}`);
    }
    try {
      await A.teardownNamespace(
        [cleanupByoc?.gameId, cleanupCross?.gameId, cleanupScoped?.gameId]
          .filter(Number.isSafeInteger),
      );
    } catch (error) {
      try {
        if (cleanupByoc) {
          deleteDisposableLoadGame(cleanupByoc.gameId, state.byocTitle);
        }
        if (cleanupCross) {
          deleteDisposableLoadGame(cleanupCross.gameId, state.crossGameTitle);
        }
        if (cleanupScoped) {
          deleteDisposableLoadGame(cleanupScoped.gameId, state.scopedGameTitle);
        }
        state.evidence.historyRetentionCleanup =
          'public hard-delete preserved started evidence; exact disposable graph fallback completed';
      } catch (fallbackError) {
        errors.push(
          `organizer hub game namespaces: ${error.message}; ` +
          `exact disposable fallback: ${fallbackError.message}`,
        );
      }
    }
  }
  try {
    await ensureOrganizerDemoted();
  } catch (error) {
    errors.push(`organizer demotion: ${error.message}`);
  }
  const cleanupUsers = new Map(state.users.map((user) => [user.id, user]));
  try {
    const raw = sql(
      `SELECT COALESCE(json_agg(json_build_object('id',id::text,'stamp',security_stamp,` +
        `'role',role,'name',user_name)),'[]'::json)::text FROM "AspNetUsers" ` +
        `WHERE normalized_email IN (upper(${sqlLiteral(names.organizerEmail)}),` +
        `upper(${sqlLiteral(names.ordinaryEmail)}),upper(${sqlLiteral(names.logProbeEmail)}))`,
    );
    for (const user of JSON.parse(raw || '[]')) cleanupUsers.set(user.id, user);
  } catch (error) {
    errors.push(`discover fixture users: ${error.message}`);
  }
  const cleanupOrganizer = [...cleanupUsers.values()].find((user) => user.name === names.organizer);
  if (cleanupOrganizer?.role === 3) {
    try {
      const selfToken = state.organizerToken || mintJwt(cleanupOrganizer.id, cleanupOrganizer.stamp, 3);
      const response = await request(adminTarget, 'PUT', `/api/admin/users/${cleanupOrganizer.id}`, {
        token: selfToken,
        body: { role: 'User' },
      });
      if (response.status !== 200) throw responseError(response, 'cleanup discovered organizer demotion');
    } catch (error) {
      errors.push(`discovered organizer demotion: ${error.message}`);
    }
  }
  for (const user of [...cleanupUsers.values()].reverse()) {
    try {
      const response = await request(adminTarget, 'DELETE', `/api/admin/users/${user.id}`, {
        token: state.primaryToken,
        timeoutMs: 60_000,
      });
      if (![200, 404].includes(response.status)) throw responseError(response, `delete user ${user.id}`);
    } catch (error) {
      errors.push(`user ${user.id}: ${error.message}`);
    }
  }
  if (state.containerGuid && state.containerRuntimeId) {
    try {
      const removed = sql(
        `DELETE FROM "Containers" WHERE id=${sqlLiteral(state.containerGuid)}::uuid ` +
          `AND container_id=${sqlLiteral(state.containerRuntimeId)} RETURNING id`,
      );
      if (removed && removed !== state.containerGuid) throw new Error('removed the wrong Containers row');
    } catch (error) {
      errors.push(`Containers row: ${error.message}`);
    }
  }
  const cleanupDocker = new Map(state.dockerContainers.map((fixture) => [fixture.name, fixture]));
  for (const [name, owned] of [[names.owned, true], [names.foreign, false]]) {
    const discovered = docker(['ps', '-aq', '--filter', `name=^/${name}$`]).stdout.trim();
    if (discovered && !cleanupDocker.has(name)) cleanupDocker.set(name, { id: discovered, name, owned });
  }
  for (const fixture of [...cleanupDocker.values()].reverse()) {
    try {
      const inspected = inspectContainer(fixture.id, `cleanup fixture ${fixture.name}`).record;
      requireCondition(
        inspected?.Name === `/${fixture.name}` &&
          inspected?.Config?.Labels?.[names.fixtureLabel] === tag,
        `refusing to remove Docker fixture ${fixture.id}: exact ownership changed`,
      );
      dockerMust(['rm', '-f', fixture.id], `remove Docker fixture ${fixture.name}`);
    } catch (error) {
      // Docker inspect returning absent is acceptable only when the exact name is
      // also absent (for example, --rm after daemon shutdown).
      const stillNamed = docker(['ps', '-aq', '--filter', `name=^/${fixture.name}$`]).stdout.trim();
      if (stillNamed) errors.push(`Docker fixture ${fixture.name}: ${error.message}`);
    }
  }
  const cleanupAuditRows = new Map(state.auditRows.map((row) => [Number(row.id), row]));
  if (Number.isSafeInteger(state.logFloor) && state.primaryName) {
    try {
      const raw = sql(
        `SELECT COALESCE(json_agg(json_build_object('id',id,'logger',logger,'name',user_name,` +
          `'message',message,'level',level,'status',status) ORDER BY id),'[]'::json)::text ` +
          `FROM "Logs" WHERE id>${state.logFloor} AND logger='AdminController' AND (` +
          `(user_name=${sqlLiteral(state.primaryName)} AND message='Successfully added 2 users') OR ` +
          `(user_name=${sqlLiteral(names.organizer)} AND message='Successfully added 1 users'))`,
      );
      const discovered = JSON.parse(raw || '[]');
      const primaryRows = discovered.filter((row) => row.name === state.primaryName);
      const organizerRows = discovered.filter((row) => row.name === names.organizer);
      const known = new Set(state.auditRows.map((row) => Number(row.id)));
      if (primaryRows.length > 1 && primaryRows.some((row) => !known.has(Number(row.id)))) {
        throw new Error('primary Admin audit discovery is ambiguous; refusing to delete concurrent rows');
      }
      if (organizerRows.length > 1 && organizerRows.some((row) => !known.has(Number(row.id)))) {
        throw new Error('disposable organizer emitted an unexpected duplicate semantic audit row');
      }
      for (const row of discovered) cleanupAuditRows.set(Number(row.id), row);
    } catch (error) {
      errors.push(`discover fixture audit rows: ${error.message}`);
    }
  }
  for (const row of cleanupAuditRows.values()) {
    try {
      const removed = sql(
        `DELETE FROM "Logs" WHERE id=${Number(row.id)} AND logger=${sqlLiteral(row.logger)} ` +
          `AND user_name=${sqlLiteral(row.name)} AND message=${sqlLiteral(row.message)} RETURNING id`,
      );
      if (removed && Number(removed) !== Number(row.id)) throw new Error('removed the wrong audit row');
    } catch (error) {
      errors.push(`audit row ${row.id}: ${error.message}`);
    }
  }

  try {
    const emails = [names.organizerEmail, names.ordinaryEmail, names.logProbeEmail]
      .map(sqlLiteral)
      .join(',');
    requireCondition(
      Number(sql(`SELECT count(*) FROM "AspNetUsers" WHERE email IN (${emails})`)) === 0,
      'fixture users remain',
    );
    if (state.containerGuid) {
      requireCondition(
        Number(sql(`SELECT count(*) FROM "Containers" WHERE id=${sqlLiteral(state.containerGuid)}::uuid`)) === 0,
        'fixture Containers row remains',
      );
    }
    if (cleanupAuditRows.size) {
      const ids = [...cleanupAuditRows.keys()].join(',');
      requireCondition(Number(sql(`SELECT count(*) FROM "Logs" WHERE id IN (${ids})`)) === 0, 'fixture audit rows remain');
    }
    for (const fixture of cleanupDocker.values()) {
      requireCondition(
        !docker(['ps', '-aq', '--filter', `name=^/${fixture.name}$`]).stdout.trim(),
        `Docker fixture ${fixture.name} remains`,
      );
    }
    if (cleanupByoc) {
      requireCondition(
        Number(sql(`SELECT count(*) FROM "Games" WHERE id=${cleanupByoc.gameId}`)) === 0,
        'BYOC fixture game remains',
      );
    }
    if (cleanupCross) {
      requireCondition(
        Number(sql(`SELECT count(*) FROM "Games" WHERE id=${cleanupCross.gameId}`)) === 0,
        'cross-game fixture remains',
      );
      if (cleanupCross.containerGuid) {
        requireCondition(
          Number(sql(
            `SELECT count(*) FROM "Containers" ` +
              `WHERE id=${sqlLiteral(cleanupCross.containerGuid)}::uuid`,
          )) === 0,
          'cross-game Containers row remains',
        );
      }
    }
    if (cleanupScoped) {
      requireCondition(
        Number(sql(`SELECT count(*) FROM "Games" WHERE id=${cleanupScoped.gameId}`)) === 0,
        'scoped fixture game remains',
      );
    }
  } catch (error) {
    errors.push(`residual audit: ${error.message}`);
  }
  try {
    const delayMs = Number(process.env.ORGANIZER_HUB_CLEANUP_STABILITY_MS || 2_000);
    requireCondition(
      Number.isSafeInteger(delayMs) && delayMs >= 1_000 && delayMs <= 10_000,
      'ORGANIZER_HUB_CLEANUP_STABILITY_MS must be an integer from 1000 through 10000',
    );
    await sleep(delayMs);
    const first = cleanupResidualSnapshot({
      cleanupAuditRows,
      cleanupByoc,
      cleanupCross,
      cleanupScoped,
      cleanupDocker,
    });
    requireZeroResidualSnapshot(first, 'first delayed residual snapshot');
    await sleep(delayMs);
    const second = cleanupResidualSnapshot({
      cleanupAuditRows,
      cleanupByoc,
      cleanupCross,
      cleanupScoped,
      cleanupDocker,
    });
    requireZeroResidualSnapshot(second, 'second delayed residual snapshot');
    requireCondition(
      JSON.stringify(first) === JSON.stringify(second),
      'residual snapshots changed between delayed reads',
    );
    state.evidence.cleanupResidualSnapshots = { delayMs, first, second };
  } catch (error) {
    errors.push(`delayed residual snapshots: ${error.message}`);
  }
  if (errors.length) throw new Error(errors.join('; '));
}

async function main() {
  const topology = assertSafeTopology();
  state.evidence.runtimeIdentity = {
    before: inspectUniformServerRuntimeIdentity(serverContainers),
    after: null,
  };
  lock = await acquireExclusiveProcessLock(loadOrchestrationLockPath, {
    label: 'organizer-hub lifecycle',
    metadata: { tag, composeProject: topology.composeProject },
  });
  databaseLock = await acquireAdminLifecycleDatabaseLock();
  state.topologyAuthorized = true;
  state.evidence.topology = {
    composeProject: topology.composeProject,
    adminContainer,
    execContainer,
    pgContainer,
    redisContainer,
    webTargets,
    webContainers,
    tunnelNetwork: NET,
    adNetwork,
  };
  saveRecovery();
  await healthPreflight(topology);
  await inverseTopologyPreflight();
  saveRecovery();
  checkInterrupted();

  const primary = resolvePrimaryAdmin();
  state.primaryToken = primary.token;
  state.primaryName = primary.name;
  state.logFloor = maxLogId();
  const profile = await request(adminTarget, 'GET', '/api/account/profile', { token: primary.token });
  await expectStatus(profile, 200, 'primary Admin preflight');
  requireCondition(profile.json?.role === 'Admin', 'primary token did not resolve to Admin');

  const { organizer, ordinary, ordinaryToken } = await createIdentities(primary);
  await authorizationMatrix(ordinaryToken, state.organizerToken);
  saveRecovery();
  checkInterrupted();

  const adminConnection = await negotiate(
    adminTarget,
    '/hub/admin',
    state.organizerToken,
    200,
    'AdminHub E2E negotiate',
    'admin_negotiate',
  );
  const adminClient = await connectHub(
    adminTarget,
    '/hub/admin',
    state.organizerToken,
    adminConnection,
    'AdminHub E2E',
    'admin_upgrade',
  );
  await receivedLogLifecycle(organizer, adminClient);

  const fixtures = createDockerFixtures(topology.scope);
  const execConnection = await negotiate(
    execTarget,
    '/hub/containerExec',
    state.organizerToken,
    200,
    'ContainerExecHub E2E negotiate',
    'container_exec_negotiate',
  );
  const execClient = await connectHub(
    execTarget,
    '/hub/containerExec',
    state.organizerToken,
    execConnection,
    'ContainerExecHub E2E',
    'container_exec_upgrade',
  );
  await containerExecLifecycle(execClient, fixtures);
  saveRecovery();
  const byocFixture = await byocExecLifecycle(execClient);
  saveRecovery();
  const scopedManager = await scopedManagerExecLifecycle(
    ordinary,
    ordinaryToken,
    byocFixture,
    fixtures,
  );
  const runtimeCoverageCount = assertPrivilegedHubRuntimeCoverage(coveredSurfaces);
  state.evidence.privilegedHubRuntimeCoverage = {
    count: runtimeCoverageCount,
    surfaces: [...coveredSurfaces].sort(),
  };
  saveRecovery();
  checkInterrupted();

  await loadPhase(state.organizerToken, scopedManager);
  saveRecovery();
  await revokeScopedManagerSession(scopedManager);
  saveRecovery();
  await revokeOrganizerSessions(organizer, adminClient, execClient);
  saveRecovery();
}

let primaryError = null;
try {
  await main();
} catch (error) {
  primaryError = error;
  state.scenarioFailure = String(error?.stack || error?.message || error);
  state.failure = { phase: 'scenario', message: String(error?.stack || error?.message || error) };
  saveRecovery();
}
let cleanupError = null;
try {
  await cleanup();
} catch (error) {
  cleanupError = error;
  state.cleanupFailure = String(error?.stack || error?.message || error);
  state.failure = {
    phase: primaryError ? 'scenario-and-cleanup' : 'cleanup',
    message: String(error?.stack || error?.message || error),
  };
  saveRecovery();
}
let verificationError = null;
if (state.topologyAuthorized) {
  try {
    const startingRuntimeIdentity = state.evidence.runtimeIdentity.before;
    state.evidence.runtimeIdentity.after = inspectUnchangedServerRuntimeIdentity(
      startingRuntimeIdentity,
      serverContainers,
    );
    saveRecovery();
    const fatalLogsByContainer = Object.fromEntries(
      originalServerRuntimeLogTargets(startingRuntimeIdentity).map(({ name, containerId }) => [
        name,
        {
          containerId,
          fatalLineCount: countContainerFatalLogs(containerId, runStartedAt),
        },
      ]),
    );
    state.evidence.fatalLogAudit = fatalLogsByContainer;
    const fatalLogs = Object.values(fatalLogsByContainer)
      .reduce((sum, value) => sum + value.fatalLineCount, 0);
    requireCondition(fatalLogs === 0, `runtime log audit found ${fatalLogs} panic/fatal records`);
    state.evidence.runtimeIdentity.after = inspectUnchangedServerRuntimeIdentity(
      startingRuntimeIdentity,
      serverContainers,
    );
  } catch (error) {
    verificationError = error;
    state.verificationFailure = String(error?.stack || error?.message || error);
    saveRecovery();
  }
}
const leaseErrors = [];
for (const [label, lease] of [['database', databaseLock], ['process', lock]]) {
  if (!lease) continue;
  try {
    await lease.release();
  } catch (error) {
    const wrapped = new Error(`${label} organizer-hub lease release failed: ${error.message}`);
    leaseErrors.push(wrapped);
    state.leaseFailures.push(String(wrapped.stack || wrapped.message));
    saveRecovery();
  }
}

state.cleanupVerified = state.topologyAuthorized && cleanupError === null;
state.completed = primaryError === null && cleanupError === null &&
  verificationError === null && leaseErrors.length === 0;
state.completedAt = Date.now();
saveRecovery();

if (primaryError || cleanupError || verificationError || leaseErrors.length) {
  const failures = [];
  if (primaryError) failures.push(`scenario: ${primaryError.stack || primaryError.message}`);
  if (cleanupError) failures.push(`cleanup: ${cleanupError.stack || cleanupError.message}`);
  if (verificationError) failures.push(`verification: ${verificationError.stack || verificationError.message}`);
  failures.push(...leaseErrors.map((error) => `lease release: ${error.stack || error.message}`));
  throw new Error(failures.join('\n'));
}

console.log('\norganizer hub lifecycle passed');
console.log(`  AdminHub: negotiate + WebSocket auth + actual ReceivedLog (${state.evidence.receivedLog.msg})`);
console.log('  ContainerExecHub: Open + Input + Resize + Close on exact RSCTF-owned fixture');
console.log('  arbitrary raw container: rejected into an inert session; no command side effect');
console.log(`  session revocation: ${state.evidence.revocation}`);
console.log(`  fixed-rate load: ${JSON.stringify(state.evidence.load)}`);
console.log(`  BYOC exec: ${state.evidence.byocExec.exercised ? 'Open + Input/output + Resize + Close' : `environment-blocked — ${state.evidence.byocExec.reason}`}`);
console.log(`  scoped manager exec: ${state.evidence.scopedManagerExec.exercised ? 'same-game allowed; cross-game/raw denied; membership revoke closed socket' : state.evidence.scopedManagerExec.reason}`);
console.log('  cleanup: exact users, audit rows, Containers rows, game namespaces, and Docker fixtures absent');
console.log(`  recovery/audit manifest: ${recoveryPath}`);
if (!shouldRetainLifecycleManifest({
  completed: state.completed,
  cleanupVerified: state.cleanupVerified,
  keep: process.env.KEEP_ORGANIZER_HUB_MANIFEST,
})) removeRecovery(recoveryPath);
