{{- include "rsctf.validateValues" . }}
{{- if empty .Values.existingSecret.name }}
{{- $secretName := include "rsctf.fullname" . -}}
{{- $old := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $pgKey := .Values.existingSecret.postgresqlPasswordKey -}}
{{- $redisKey := .Values.existingSecret.redisPasswordKey -}}
{{- $pgPassword := .Values.postgresql.auth.password -}}
{{- if and .Values.postgresql.enabled (empty $pgPassword) -}}
  {{- if and $old $old.data (hasKey $old.data $pgKey) -}}
    {{- $pgPassword = (index $old.data $pgKey | b64dec) -}}
  {{- else -}}
    {{- $pgPassword = randAlphaNum 40 -}}
  {{- end -}}
{{- end -}}
{{- $redisPassword := .Values.redis.password -}}
{{- if and .Values.redis.enabled (empty $redisPassword) -}}
  {{- if and $old $old.data (hasKey $old.data $redisKey) -}}
    {{- $redisPassword = (index $old.data $redisKey | b64dec) -}}
  {{- else -}}
    {{- $redisPassword = randAlphaNum 40 -}}
  {{- end -}}
{{- end -}}
{{- $databaseUrl := .Values.database.url -}}
{{- if .Values.postgresql.enabled -}}
  {{- $databaseUrl = printf "postgres://%s:%s@%s:5432/%s" (.Values.postgresql.auth.username | urlquery) ($pgPassword | urlquery) (include "rsctf.postgresqlName" .) (.Values.postgresql.auth.database | urlquery) -}}
{{- end -}}
{{- $redisUrl := .Values.redis.url -}}
{{- if .Values.redis.enabled -}}
  {{- $redisUrl = printf "redis://:%s@%s:6379/0" ($redisPassword | urlquery) (include "rsctf.redisName" .) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "rsctf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecret.databaseUrlKey | quote }}: {{ $databaseUrl | quote }}
  {{ .Values.existingSecret.jwtSecretKey | quote }}: {{ .Values.secrets.jwtSecret | quote }}
  {{- if .Values.postgresql.enabled }}
  {{ .Values.existingSecret.postgresqlPasswordKey | quote }}: {{ $pgPassword | quote }}
  {{- end }}
  {{- if or .Values.redis.enabled (not (empty $redisUrl)) }}
  {{ .Values.existingSecret.redisUrlKey | quote }}: {{ $redisUrl | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  {{ .Values.existingSecret.redisPasswordKey | quote }}: {{ $redisPassword | quote }}
  {{- end }}
{{- end }}
