{{- if and (eq .Values.storage.backend "s3") (empty .Values.storage.s3.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rsctf.fullname" . }}-storage
  labels:
    {{- include "rsctf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.storage.s3.existingSecret.accessKeyKey | quote }}: {{ .Values.storage.s3.accessKey | quote }}
  {{ .Values.storage.s3.existingSecret.secretKeyKey | quote }}: {{ .Values.storage.s3.secretKey | quote }}
{{- end }}
